### DISCUSSION TITLE
Input body property default value

### DISCUSSION THREAD

**Discussion by stavrogin** [swagger-api/swagger-codegen#11213] [Q&A]
Hi, 
is it possible to define a default value of an input body property?
It should be something like this in Open API

```
type: object
description:
properties:
  input_number:
    type: number
    default: 1

```
but it seems to be ignored in the output generated Java code (using version 3.0.18)
