### DISCUSSION TITLE
Initialize fields of type object with default constructor

### DISCUSSION THREAD

**Discussion by manosntoulias** [swagger-api/swagger-codegen#11782] [Q&A]
**Description**

I have a model that is autogenerated by swagger to this:

```
ModelDto {
 private SomeOtherModelDto object = null;
}
```

How do I force the object field to be initialized with the default constructor instead, like this:

```
ModelDto {
 private SomeOtherModelDto object = new SomeOtherModelDto();
}
```

In swagger the spec looks like this so far:

```
ModelDto:
  type: object
  properties:
    SomeOtherModelDto:
          type: object
          ....
```
