### DISCUSSION TITLE
How to avoid generate the same java file with swagger gen

### DISCUSSION THREAD

**Discussion by davideferrari** [swagger-api/swagger-codegen#11883] [Q&A]
Let us suppose we have some yaml files like following:

```
Article.yml

GenericArticleDto:
  type: object
  properties:
    description: 
      type: string
[...]
```
**Order.yml**
```
EnglishArticleDto:
  type: object
  allOf:
    - $ref: '../Article.yml/components/schemas/GenericArticleDto'
[...]
```
I generate the Java classes from the Order.yml with swagger gen and specify the destination package, let's say '**com.test.order**' After this operation I have two classes in com.test.order, _EnglishArticleDto.java_ and _GenericArticleDto.java_

If I have another yml file with a dto that point to the same object GenericArticleDto

**Proposal.yml**
```
CustomerArticleDto:
  type: object
  allOf:
    - $ref: '../Article.yml/components/schemas/GenericArticleDto'
```
I generate the Java classes from the Proposal.yml and specify the destination package, let's say '**com.test.proposal**'. If I run the swagger script I have two classes in com.test.proposal, _CustomerArticleDto.java_ and _GenericArticleDto.java_

My doubt is: Is there a way with swagger gen to specify to avoid the creation of _another_ Java class for _GenericArticleDto_ and to **REUSE** the same present under the package com.test.order?

Swagger gen version: **2.2**

Thanks a lot!
