### DISCUSSION TITLE
csharp client code generator does not generated correct types for object fields

### DISCUSSION THREAD

**Discussion by dshirokov-wellsky** [swagger-api/swagger-codegen#12451] [General]
While openapi: 3.1.0 YAML specs has type info, generated c# client has object for most of the fields. Example:

```
Physician:
      type: object
      properties:
        name:
          type: string
          example: Phillis Physician
        email:
          type: string
          example: phillis@example.com
        phone:
          type: string
          example: "+12345559999"
```
          
         
It is pretty obvious that all fields of JSON object should be mapped to string properties of C# class, right?

This is the generated csharp class (comments removed)

```
public class Physician
{
    public Physician(Object name = default(Object), Object email = default(Object), Object phone = default(Object))
    {
        this.Name = name;
        this.Email = email;
        this.Phone = phone;
    }
    
    [DataMember(Name="name", EmitDefaultValue=false)]
    public Object Name { get; set; }

    [DataMember(Name="email", EmitDefaultValue=false)]
    public Object Email { get; set; }

    [DataMember(Name="phone", EmitDefaultValue=false)]
    public Object Phone { get; set; }
...
}
```
