### ISSUE TITLE
[JAVA/okhttp-gson] Bug generating noncompilable code when discriminator is used

### ISSUE THREAD

**Issue by eppjo** [swagger-api/swagger-codegen#10012]
##### Description

Generating swagger API for `okhttp-gson` with usage of `discriminator` in model definitions for inheritance and polymorphism will output non compilable code in the parent classes.

##### Swagger-codegen version
```groovy
swaggerCodegen 'io.swagger:swagger-codegen-cli:2.4.12'
```

##### Swagger declaration file content or url

```yaml
...
  SomeStatus:
    type: object
    discriminator: classType
    properties:
      statusText:
        description: The status as text
        type: string
      statusDetail:
        description: Additional information to given status.
        type: string
...
```
##### Possible fix

Changing the pojo.mustache solved the problem in my case:

```
  {{#parcelableModel}}
  public {{classname}}() {
  {{#parent}}
    super();
  {{/parent}}
  {{#gson}}
  {{#discriminator}}
//    this.{{discriminator}} = this.getClass().getSimpleName(); <-- should be removed, will cause compile error!
  {{/discriminator}}
  {{/gson}}
  }
  {{/parcelableModel}}
  {{^parcelableModel}}
  {{#gson}}
  {{#discriminator}}
  public {{classname}}() {
//    this.{{discriminator}} = this.getClass().getSimpleName(); <-- should be removed, will cause compile error!
  }
  {{/discriminator}}
  {{/gson}}
  {{/parcelableModel}}
```
