### ISSUE TITLE
[PHP] Generated APIs incorrectly encode commas in certain query parameters

### ISSUE THREAD

**Issue by Axent96** [swagger-api/swagger-codegen#10046]
I have the same json definition but by different swagger-codegen have the deffirent in source code of API:

Version 2.4.8:
```
        if (is_array($filter_number)) {
            $filter_number = ObjectSerializer::serializeCollection($filter_number, 'csv', true);
        }
        if ($filter_item_number !== null) {
            $queryParams['filter[number]'] = ObjectSerializer::toQueryValue($filter_number);
        }
```
Version 2.4.9 and more:
```
        if (is_array($filter_number)) {
            $queryParams['filter[number]'] = $filter_number;
        }
        if ($filter_item_number !== null) {
            $queryParams['filter[number]'] = ObjectSerializer::toQueryValue($filter_number);
        }
```

Swagger Parameter: "collectionFormat: csv"

##### Description

The problem exist only for query params but it work correct for header params. (same functionality by version 2.4.8 and starting at 2.4.9) 

##### Swagger-codegen version

starting at 2.4.9

##### Swagger declaration file content or url

```yaml
...
        - name: 'filter[number]'
          in: query
          required: false
          items:
            type: string
          type: array
          collectionFormat: csv
          uniqueItems: true
...
```

##### Command line used for generation

unknown. It used from https://app.swaggerhub.com/
I can reproduce with: java -jar swagger-codegen-cli-2.4.12.jar generate -i the.json -l php -o /tmp/test
