### ISSUE TITLE
Python bearerAuth not generated

### ISSUE THREAD

**Issue by esseti** [swagger-api/swagger-codegen#10060]
##### Description
in my description i've this
```
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
- basicAuth: []
- bearerAuth: []
```

however in the `auth_setting` function in the configuration.py there's no `bearerAuth`

```
    def auth_settings(self):
        """Gets Auth Settings dict for api client.

        :return: The Auth Settings information dict.
        """
        return {
            'basicAuth':
                {
                    'type': 'basic',
                    'in': 'header',
                    'key': 'Authorization',
                    'value': self.get_basic_auth_token()
                },
        }

```

while it should be something like 

```    def auth_settings(self):
        """Gets Auth Settings dict for api client.

        :return: The Auth Settings information dict.
        """
        return {
            'basicAuth':
                {
                    'type': 'basic',
                    'in': 'header',
                    'key': 'Authorization',
                    'value': self.get_basic_auth_token()
                },
            'bearerAuth':
                {
                    'type': 'http',
                    'in': 'header',
                    'key': 'Authorization',
                    'value': self.get_api_key_with_prefix('Jwt')
                },
        }
```

(not sure why there's an identifier to specify)

am I missing anything?
##### Swagger-codegen version

3.0.17

##### Swagger declaration file content or url
see above
##### Command line used for generation

`java -jar codegen/swagger-codegen-cli.jar generate -i scriba-openapi-api.yml -c python/python-config.json -DpackageVersion=2.2.0-13-g1e6a6bc -o python/api -l python`
