### ISSUE TITLE
[SPRING] Fields starting with _ are generated as duplicates

### ISSUE THREAD

**Issue by jordanwalsh23** [swagger-api/swagger-codegen#10093]
##### Description

When generating spring code using swagger-codegen-cli, fields starting with an _ appear in the generated response twice.

##### Swagger-codegen version

swagger-codegen-cli v3.0.18

##### Swagger declaration file content or url

```yaml
defaultmodel:
    description: Default response for the api
    properties:
      api_name:
        type: string
        example: "My Wonderful API"
      api_version:
        type: string
        example: v1.0
      api_released:
        type: string
        example: "2020-02-03"
      api_status:
        type: string
        example: "active"
      _links:
        type: array
        items:
          properties:
            rel:
              type: string
              example: organisation-units
            href:
              type: string
              example: /v1.0/organisation-units
            method:
              type: string
              example: GET
```

##### Command line used for generation

```
java -jar swagger-codegen-cli.jar generate -i ..\api.yaml -l spring -o ..\mock
```

##### Steps to reproduce

- Generate the spring code off the api definition
- cd into the mock directory
- run `mvn clean install`
- run the generated jar file `java -jar target\my-jar-file.jar`
- Browse to localhost:8080 
- Note that the `_links` will be present, but also another variable will be present in the response called `links`.

e.g. 

```
{
  "_links": [
    {}
  ],
  "api_name": "My Wonderful API",
  "api_released": "2020-02-03",
  "api_status": "active",
  "api_version": "v1.0",
  "links": [
    {}
  ]
}
```

##### Related issues/PRs

Can't find any.

##### Suggest a fix/enhancement

I've reviewed the generated code and can't see this extra parameter in any of the models.  It seems to be within the core swagger codegen project.
