### ISSUE TITLE
Client SDK generation fails when referenced domain contains schema with pattern

### ISSUE THREAD

**Issue by jeffreydking** [swagger-api/swagger-codegen#10119]
##### Description

Client SDK generation fails when referenced domain contains schema with pattern

If a domain contains an schema like this:

```yaml
components:
  schemas:
    countryCode:
      description: "An ISO 3166-1 Alpha-2 country code."
      type: 'string'
      pattern: '([A-Z]){2}' # inclusion of this line causes Client SDK generation to fail.
      example: 'US'
```

and  the domain schema is referenced in a API spec like this:

```yaml
paths:
  /example/path:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: 'https://example.com/path/to/domain#/components/schemas/countryCode'
```

Client SDK generation will fail with the following error:

```
Error.There was an error generating the clients csharp code. Please ensure that the definition and all external refs (inc. domains) are valid.
```

Commenting out the pattern will allow the SDK to generate as expected.

##### Swagger-codegen version

Whichever version is in current use by SwaggerHub. I assume it is current.

##### Swagger declaration file content or url

See description.

##### Command line used for generation

Whatever SwaggerHub uses when selecting the option to generate Client SDKs for an API.

##### Steps to reproduce

See description.

##### Related issues/PRs

Not to my knowledge.

##### Suggest a fix/enhancement

Unknown.
