### ISSUE TITLE
[typescript-angular] (swagger-codegen 3.0.18) Constrained query parameter values in YAML are not constrained in client

### ISSUE THREAD

**Issue by Smootium** [swagger-api/swagger-codegen#10148]
**Description**
When defining a query parameter, sometimes we also define the possible values that that parameter can be.
Using an endpoint that supports sorting on a `GET` operation as an example:
A client can get all `Note`s for a session.
A `Note` has two properties that we allow to be used for sorting: 
 * `CreatedOn`
 * `CreatedBy`

In Swagger 2, this was defined as such:
```yaml
- name: "sort"
  in: "query"
  description: "property that will be used for sorting; prefix with '-' to reverse"
  required: false
  type: "array"
  uniqueItems: true
  collectionFormat: multi
  items:
    type: "string"
    enum: ["createdOn", "createdBy"]
```
In this manner, a client can request sorting only on those 2 properties and not, e.g., a third property called "`content`".
The generated client code (from https://generator.swagger.io/) looked like this:
Note the `sort` param is "constrained" to those 2 properties -- `Array<'createdOn' | 'createdBy'>`
```ts
public getSessionNotes(sessionId: string, cursor?: string, limit?: number, sort?: Array<'createdOn' | 'createdBy'>, observe?: 'body', reportProgress?: boolean): Observable<Array<Note>>;
```
In OAS3 YAML (using the [online Swagger editor](https://editor.swagger.io/) to convert from Swagger 2 to OAS 3), this same parameter is defined as:
```yaml
- name: sort
  in: query
  description: property that will be used for sorting; prefix with '-' to reverse
  style: form
  explode: true
  schema:
    uniqueItems: true
    type: array
    items:
      type: string
      enum:
      - createdOn
      - createdBy
```
The generated client code (using [3rd generation online Swagger generator](https://generator3.swagger.io/index.html)) no longer constrains the value, allowing any value to be passed:
Note that `sort` is now `Array<string>`
```ts
public getSessionNotes(sessionId: string, cursor?: string, limit?: number, sort?: Array<string>, observe?: 'body', reportProgress?: boolean): Observable<Array<Note>>;
```

**Swagger-codegen version**
3.0.18 (using the "3rd Gen" online generator (https://generator3.swagger.io/index.html))
This worked fine using Swagger 2 (https://generator.swagger.io/)

**Swagger declaration file content or url**
[RestApi-constrained-sort.yml](https://gist.github.com/Smootium/2d7da16e7fbc7d5c3bfcb581c766f0ed)

**Options used for generation**
(note: not including the `spec` object, for simplicity; see subsequent note in Repro Steps)
```json
{
  "lang": "typescript-angular",
  "specURL": "string",
  "type": "CLIENT",
  "codegenVersion": "V3",
  "options": {
    "additionalProperties": {
      "sortParamsByRequiredFlag": false,
      "ensureUniqueParams": false,
      "supportsES6": true,
      "npmName": "test-client",
      "npmVersion": "0.0.1",
      "providedInRoot": true,
      "ngVersion": "7.2.8"
    }
  }
}
```

**Steps to reproduce**
❗️  For simplicity sake, I'm listing the easiest way to reproduce the issue. This is not the process we use "in real life" (but the results are the same).
1. Copy the [RestApi-constrained-sort.yml](https://gist.github.com/Smootium/2d7da16e7fbc7d5c3bfcb581c766f0ed) contents into [the online Swagger Editor](https://editor.swagger.io/)
1. Click on `Generate Client` drop-down menu.
1. Select `typescript-angular`.
1. Open the downloaded generated client content (zip file):
   1. Open the `api` folder
   1. Inspect the `calcSessions.service.ts` file.
  ℹ️  I copied the contents of the calcSessions.service.ts file [into a gist](https://gist.github.com/Smootium/ac7ea4f1dc0d02edcc1801f38fda0441), for easier inspection.

   1. Notice [on Lines 68-71](https://gist.github.com/Smootium/ac7ea4f1dc0d02edcc1801f38fda0441#file-calcsessions-service-ts-L68) the `sort` parameter is allowed to be any string (`Array<string>`) instead of constrained to `createdOn` and `createdBy` (`Array<'createdOn' | 'createdBy'>`)

**Related issues/PRs**
I was not able to find a related issue/PR.
