### ISSUE TITLE
swagger json to client conversion is not working if it has in:body as array string

### ISSUE THREAD

**Issue by ijaz20** [swagger-api/swagger-codegen#10172]
##### Description

I'm trying to generate a swagger client from swagger JSON but when I run swagger code-gen it throws error like could not complete the operation. Below is my swagger JSON

  "swagger": "2.0",

```yaml
"/api/{id}/MO/{MOid}/pop/api": {
      "post": {
        "tags": [
          "cam"
        ],
        "summary": "summay",
        "operationId": "ApiCamByIdMOByMOIdPOPApiPost",
        "consumes": [
          "application/json-patch+json",
          "application/json",
          "text/json",
          "application/*+json"
        ],
        "produces": [
          "text/plain",
          "application/json",
          "text/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "cam id",
            "required": true,
            "type": "string"
          },
          {
            "name": "moId",
            "in": "path",
            "description": "mo's id",
            "required": true,
            "type": "integer",
            "format": "int32"
          },
          {
            "name": "apiItemIds",
            "in": "body",
            "description": "List of api items",
            "schema": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "API pop report",
            "schema": {
              "$ref": "#/definitions/Operation"
            }
          },
        }
      }
    },
```
When I try to convert this JSON to java client using swagger code Gen. It fails with  _Could not process operation_.

Once I remove below part Code generation works fine
```
 {
            "name": "apiItemIds",
            "in": "body",
            "description": "List of api items",
            "schema": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
```
Code generation works fine. I don't know what's wrong with this part looks everything fine to me. I tried this request in postman and curl command it worked fine. I tried many things with no progress.
