### ISSUE TITLE
[Spring] Support @Email constraint

### ISSUE THREAD

**Issue by Alex-Wir** [swagger-api/swagger-codegen#10202]
### Description

Add support for `@javax.validation.constraints.Email`

**IF** `useBeanValidation` and `performBeanValidation` are `true`
**AND** `format: email` specified for path param
**THEN** should be `@Email` on parameter

### Swagger-codegen-maven-plugin version

3.0.18

### pom.xml
```xml
<plugins>
  <plugin>
    <groupId>io.swagger.codegen.v3</groupId>
    <artifactId>swagger-codegen-maven-plugin</artifactId>
    <executions>
      <execution>
        ...
        <configuration>
          ...
          <language>spring</language>
          <configOptions>
            <useBeanValidation>true</useBeanValidation>
            <performBeanValidation>true</performBeanValidation>
            ...
          </configOptions>
        </configuration>
      </execution>
    </executions>
  </plugin>
</plugins>
```
### Swagger declaration file content

```yaml
paths:
  /users/{email}:
    get:
      operationId: getUserByEmail
      parameters:
        - in: path
          name: email
          schema:
            type: string
            format: email
```
### Expected behavior

From yaml above should be method containing `@Email` constraint generated:
```java
import javax.validation.constraints.Email;
...
@RequestMapping(value = "/users/{email}", produces = { "application/json" }, method = RequestMethod.GET)
ResponseEntity<User> getUserByEmail(@Email @PathVariable("email") String email);
```
Currently `@Email` annotation is missing.

### Suggest a fix/enhancement

 * Add to `CodegenParameter.class` & `CodegenProperty.class` new variable `boolean isEmail` and implement all necessary logic.

 * Add to `beanValidationCore.mustache` next line:
```java
{{#useBeanValidation}}{{#performBeanValidation}}{{#isEmail}}@Email{{/isEmail}}{{/performBeanValidation}}{{/useBeanValidation}}
```
