### ISSUE TITLE
[jaxrs-cxf-cdi] Scope is not added properly in generating code from 

### ISSUE THREAD

**Issue by vithu30** [swagger-api/swagger-codegen#10225]
##### Description

I am generating code with language - jaxrs-cxf-cdi. The scope attribute is not populated properly in the generated API service. Is there any way to resolve this?

##### Swagger-codegen version
3.0.19

Snippet from my yaml file:
```yaml
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://example/oauth/authorize
          tokenUrl: https://example/oauth/token
          scopes:
            read: read scope
            write: write scope
```
The generated code does not have scopes associated with it.
```
@GET
        @Path("/{id}")
        @Produces({ "application/json" })
            @Operation( security = {
            @SecurityRequirement(name = "OAuth2", scopes = {
                        })            })
            @ApiResponses(value = { 
                @ApiResponse(responseCode = "200", description = "OK", content = @Content(schema = @Schema(implementation = Model.class))),
                @ApiResponse(responseCode = "400", description = "Invalid Request", content = @Content(schema = @Schema(implementation = Error.class))),
                @ApiResponse(responseCode = "404", description = "Not Found", content = @Content(schema = @Schema(implementation = Error.class))) })
```

Appreciate any help on this
