### ISSUE TITLE
[swagger 2.0][go server] validate enum function is not generated for 2-dimensional array

### ISSUE THREAD

**Issue by ka355** [swagger-api/swagger-codegen#10258]
##### Description

This yaml specification generates `validateTestItemsEnum()` correctly.
```
definitions:
  TestObject:
    type: object
    properties:
      test:
        type: array
        items:
          type: string
          enum: [AA, BB, CC]
```
But in case of 2-dimensional array, the validate function is not generated so that build error occurs.
```
m.validateTest2ItemsEnum undefined (type *TestObject has no field or method validateTest2ItemsEnum)
```
```
definitions:
  TestObject:
    type: object
    properties:
      test:
        type: array
        items:
          type: array
          items:
            type: string
            enum: [AA, BB, CC]
```
Of course, swagger validator does not show any errors on that.

##### Swagger-codegen version

```
version: v0.21.0
commit: 7c0fc3ee340f9d99d85573bc54a57e303a639692
```

##### Command line used for generation

`swagger -q generate server --exclude-main --spec-...`

##### Steps to reproduce

1. Add array of 'string array' in yaml file and define enum values for the 'string array'.
2. Generate code by swagger codegen.
3. codegen is done with success but build error occurs because there's no enum validation function.
