### ISSUE TITLE
[AspNetCore] Bug - Missing "]" in StringLength attribute 

### ISSUE THREAD

**Issue by fbridger** [swagger-api/swagger-codegen#10309]
##### Description

When generating a server stub controller with a parameter that have a MaxLength, swagger-code-generator is not including the ending "]" in the attribute

Example of wrongly generated method:
```c#
public virtual IActionResult ActivateSystem([FromRoute][Required][StringLength(32, MinimumLength=3)string systemIdentifier)
```

##### Swagger-codegen version

3.0

##### Swagger declaration file content or url

```yaml
parameters:
        - name: systemIdentifier
          in: path
          description: Identifier of the System
          required: true
          schema:
            type: string
            minLength: 3
            maxLength: 32
            example: 122XDSSAA222332
```

##### Command line used for generation

java -jar swagger-codegen-cli.jar generate -i api.yml -l aspnetcore -o s_t_net

##### Suggest a fix/enhancement

https://github.com/fbridger/swagger-codegen/commit/bf2a869cc945ec491c403da08dd59799ef1d3bab
