### ISSUE TITLE
[Dart] Object type not treated in a sensible manner

### ISSUE THREAD

**Issue by dllewellyn** [swagger-api/swagger-codegen#10369]
##### Swagger-codegen version

2.0 

##### Swagger declaration file content or url

```yaml
  Abc:
    type: object
    required:
      - A
      - B
      - C
    properties:
      A:
        type: integer
        example: 0
      B:
        type: integer
        example: 0
      C:
        type: object
```

  -->

##### Command line used for generation

java -jar swagger-codegen-cli.jar generate -l dart -i swagger.yaml -o . --additional-properties browserClient=false

##### Steps to reproduce

Run command above
Observe the class generated has Object.fromJson() (which is invalid)

##### Suggest a fix/enhancement

I have a fix in my codebase to work around this where instead of an object being mapped to a dart 'object' I map it to a 'dynamic' type, and make dynamic a complex type - this results in the following syntax being generated:

```dart
class ABC {
  int A = null;
  int B = null;

  dynamic C = {};
 
ABC.fromJson(Map<String, dynamic> json) {
    if (json == null) return;
    A =
        json['A']
    ;
    B =
        json['B']
    ;
    C =
        json['C']
    ;
  }
```

Which makes more sense to me as I can access the raw object and do any additional parsing by getting a reference to ABC.C and looking at the data as a map. In this specific example C can be one of a number of different classes so it means I can do 

```
if (c['type'] == "A") {
 return A.fromJson(c as Map<String, dynamic>)
}
```

As I say - I have the fix already in a branch, looking to see if this is a problematic approach for anyone
