### ISSUE TITLE
[Python]Generated code has naming conflict

### ISSUE THREAD

**Issue by Feng-Yin** [swagger-api/swagger-codegen#10368]
##### Description

The generated Python code renamed the camelCase property to under_score format and conflict with another property.

##### Swagger-codegen version

swagger-codegen-cli-2.4.14

##### Swagger declaration file content or url

<!-- if it is a bug, a json or yaml that produces it.
If you post the code inline, please wrap it with
```yaml
definitions:
  RestrictedBanInfo:
    type: object
    required:
      - ban_type
    properties:
      ban_type:
        type: string
      banType:
        type: string
        description: the same value as ban_type
        readOnly: true
```
##### Command line used for generation

java -jar swagger-codegen-cli-2.4.14.jar generate -i swagger.json -g python --library asyncio -o ./

##### Steps to reproduce

1. define an object with 2 properties. Using the camelCase and under_score case to name those 2 properties. e.g. xY and x_y
2. generate python client code
3. check generated model code
`class RestrictedBanInfo(object):`
    openapi_types = {
        'ban_type': 'str',
        'ban_type': 'str',
    }

    attribute_map = {
        'ban_type': 'ban_type',
        'ban_type': 'banType',
    }

    def __init__(self, ban_type=None, ban_type=None):
