### ISSUE TITLE
Java Client Code Generation: Wrong Timestamp import

### ISSUE THREAD

**Issue by shindemanoj** [swagger-api/swagger-codegen#10440]
##### Description

I have a definition of Timestamp object in my yaml file. But, when I am generating client for Java, 'java.sql.Timestamp' class is getting imported in models instead of user defined Timestamp.

##### Swagger-codegen version

swagger 2.0

##### Swagger declaration file content or url

```yaml
  Timestamp:
    description: |-
      A timestamp object representing a point on the ISO timeline in milliseconds
      since the Unix epoch.
    type: object
    properties:
      epochMillis:
        description: Milliseconds since the Unix epoch
        type: string
        format: int64
```

##### Steps to reproduce

1. Copy above Timestamp definition in Swagger Editor. 
2. Use it in a model. 
3. Generate Client for Java
4. java.sql.Timestamp class getting imported instead of user defined Timestamp class
