### ISSUE TITLE
kotlin-client uses $ sign in variable names

### ISSUE THREAD

**Issue by markusmoormann** [swagger-api/swagger-codegen#10484]
##### Description

Jetbrains somehow uses $ in some of their variable names. e.g.
```yaml
paths:
  /activities:
    description: This resource provides access to the activities with the possibility to filter them by various parameters.
    get:
      parameters:
....
        - name: fields
          in: query
          schema:
            type: string
          example: '$type,added,author($type,id,login,name,ringId),category($type,id),field($type,customField($type,fieldType($type,id),id,localizedName,name),id,name),id,removed,target,targetMember,timestamp'
        - name: $skip
          in: query
          schema:
            type: integer
            format: int32
        - name: $top
          in: query
          schema:
            type: integer
            format: int32
```
These get converted to 
```kotlin
fun adminCustomFieldSettingsBundlesBuildGet(fields: kotlin.String? = null, $skip: kotlin.Int? = null, $top: kotlin.Int? = null): kotlin.Array<BuildBundle> {
        val localVariableQuery: MultiValueMap = mapOf("fields" to listOf("$fields"), "$skip" to listOf("$$skip"), "$top" to listOf("$$top"))
        val localVariableConfig = RequestConfig(
                RequestMethod.GET,
                "/admin/customFieldSettings/bundles/build", query = localVariableQuery
        )
        val response = request<kotlin.Array<BuildBundle>>(
                localVariableConfig
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as kotlin.Array<BuildBundle>
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
```
which of cause fails to compile in 2 ways
1. parameters are not allowed to have `$` in their name
2. String interpolation is used in `"$skip"`

##### Swagger-codegen version

3.0.21

##### Swagger declaration file content or url

https://youtrack.jetbrains.com/api/openapi.json

##### Command line used for generation

```
java -jar swagger-codegen-cli.jar generate -i https://youtrack.jetbrains.com/api/openapi.json -l kotline-client -o kotlin
```

##### Steps to reproduce

```
java -jar swagger-codegen-cli.jar generate -i https://youtrack.jetbrains.com/api/openapi.json -l kotline-client -o kotlin
cd kotline
gradle build
```

any ideas?
