### ISSUE TITLE
[jaxrs-cxf-cdi] validations not working for the nested referneces in generated code

### ISSUE THREAD

**Issue by vithu30** [swagger-api/swagger-codegen#10494]
##### Description

I am generating code using swagger-codegen dependency version `2.3.1`. The swagger file is having nested reference as shown below:
``` yaml
Pet:
   title: Pet object
   properties:
      id: 
         type: string
         example: 01234567-0123-0123-0123-01234567892453
      info:
         $ref: '#/definitions/info'
```
``` yaml
info:
    title: Type object.
    properties:
      owner:
        type: string
        example: John
        maxLength: 40
```

Generated code snipper for Pet model:

``` java
  @ApiModelProperty(value = "")
  @JsonProperty("info")
  public InfoDTO getInfo() {
    return info;
  }
  public void setInfo(InfoDTO info) {
    this.info = info;
  }
```

Generated code snippet for `info` model:
``` java
  @ApiModelProperty(example = "owner", value = "")
  @JsonProperty("owner")
  @Size(max=40)  public String getOwner() {
    return owner;
  }
```

Even though the generated code is having the `@Size` annotation, when invoking the API, the request parameter is not getting validated. If I defined it inline, then it works.

Am I missing anything here? Appreciate any help on this.

##### Swagger-codegen version
2.3.1
