### ISSUE TITLE
[JAVA] JAXB annotations missing for JAVA enums

### ISSUE THREAD

**Issue by shaz-sk** [swagger-api/swagger-codegen#10501]
##### Description

When you add xml namespace in swagger for enum, the generated class doesnt get annotated with @XmlRootElement and @XmlAccessorType

##### Swagger-codegen version
latest version (3.0.22)

##### Swagger declaration file content or url
```yaml 
    jurisdiction:
      xml:
        namespace: 'http://example.com/schema/1'
      type: string
      "enum": [
        "VIC",
        "NSW"
      ]

```

##### Steps to reproduce
Create a swagger definition with an enum as provided in the code sample.
Generate a Java client using the maven plugin or the CLI
Observe that the Java enum classe generated do not have JAXB annotations

##### Suggest a fix/enhancement

The problem seems to be caused by the enumOuterclass.mustache not having {{>xmlAnnotation}} as the pojo.mustache.

swagger-codegen/modules/swagger-codegen/src/main/resources/JavaSpring/enumOuterClass.mustache
https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/JavaSpring/enumOuterClass.mustache

This issue can be resolved by adding the following to enumOuterClass.

In the import section
{{#withXml}}
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlElementWrapper;
{{/withXml}}

And before public enum declaration
{{>xmlAnnotation}}
