### ISSUE TITLE
[JAVA] Empty array not getting picked as default for the defined model in Open API AKA Swagger generated code

### ISSUE THREAD

**Issue by im-bhatman** [swagger-api/swagger-codegen#10874]
##### Description

While designing the API, I am defining a `UserGeo` model that contains two fields - `domain` (string array) and `country` (string array).

An empty List `[]` should be used in the request body if no value is provided for the `domain`.
But on defining the `default` property as `[]` the generates `Spring` code does not assign empty ArrayList<> aka `[]`. 

##### Swagger declaration file content or url
Attaching the code samples:

Swagger Definition:
```yaml
definitions:
  UserGeo:
    type: "object"
    properties:
      country:
        type: "array"
        items:
          type: "string"
      domain:
        type: "array"
        items:
          type: "string"
        default: []
```
This does not default the domain value to an empty list, check this generated Spring/Java code:
```java
.
.
public class Classification   {
  @JsonProperty("country")
  @Valid
  private List<String> country = null;

  @JsonProperty("domain")
  @Valid
  private List<String> domain = null;
.
.
```

Whereas when I define the domain field as `required` without even defining it with default, the generated code assigns an empty list as default for the `domain`.
```yaml
definitions:
  UserGeo:
    type: "object"
    required:
      - "domain"
    properties:
      country:
        type: "array"
        items:
          type: "string"
      domain:
        type: "array"
        items:
          type: "string"
```
And as mentioned the generated code has an empty list assigned for the domain.
```java
public class UserGeo   {
  @JsonProperty("country")
  @Valid
  private List<String> country = null;

  @JsonProperty("domain")
  @Valid
  private List<String> domain = new ArrayList<String>();
```

##### Steps to reproduce

Go to https://editor.swagger.io/ , paste the YAML in definitions and generate server code -> spring

##### Suggest a fix/enhancement

If a field is required in the model (even of type array), the generated code should not automatically assign an empty array when the field is missing.
And defaults should only be used when they are specifically asked to.

**Comment by natalie-zamani** [comment]
Still seem to be running into this issue.

**Comment by mariodmpereira** [comment]
I'm still facing the same issue, I saw in other posts elsewhere people mentioning that adding `required: true` served as workaround, but it's not working for me.

**Comment by asprouse5** [comment]
I don't understand why required is being used to determine whether or not the default value should show. I am using an edited version of pojo.mustache that makes this change (which essentially makes it the same as the "not container" section underneath):

```diff
{{#isContainer}}
- private {{{datatypeWithEnum}}} {{name}}{{#required}} = {{{defaultValue}}}{{/required}}{{^required}} = null{{/required}};
+ private {{{datatypeWithEnum}}} {{name}} = {{{defaultValue}}};
{{/isContainer}}
{{^isContainer}}
private {{{datatypeWithEnum}}} {{name}} = {{{defaultValue}}};
{{/isContainer}}
```
Sample swagger.yaml
```yaml
MyModel:
  properties:
    keywords:
      type: array
      items:
        type: string
      default: []
    id:
      type: string
```
In my case, this will use `new ArrayList<String>();` for properties like keywords and `null` for properties like id, which is what I need. Looking at the possible permutations:

Is It Required? | Is There A Default Value? | We Should Use
--- | --- | ---
Yes | Yes | Default Value
Yes | No | Null
No | Yes | Default Value
No | No | Null

So in my opinion, if there is a default value it should be used without condition. In the case that the default value does not exist, it will use null.
