### ISSUE TITLE
[java][feign] Code not compile after generate client

### ISSUE THREAD

**Issue by marysia16122** [swagger-api/swagger-codegen#10889]
##### Description

Java client after generate:
```
public ApiClient(String[] authNames) {
    this();
    for(String authName : authNames) {
      RequestInterceptor auth;
      if ("Bearer".equals(authName)) {
      } else if ("JwsSignature".equals(authName)) {
        auth = new ApiKeyAuth("header", "x-jws-signature");
      } else {
        throw new RuntimeException("auth name \"" + authName + "\" not found in available auth names");
      }
      addAuthorization(authName, auth);
    }
  }
```

error:
`Variable 'auth' might not have been initialized`

##### Swagger-codegen version
3.0.24

##### Swagger declaration file content or url

```yaml
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
    JwsSignature:
      type: apiKey
      in: header
      name: x-jws-signature
```
