### ISSUE TITLE
[python client] can't access enum fields that reference definition

### ISSUE THREAD

**Issue by yzats** [swagger-api/swagger-codegen#1088]
My response contains an enum field. In the spec, the field is defined via "ref" for reuse purpose (see example below). This field is mapped to an empty list in the python object generated by the client instead of a string. 

Here's an example of spec:

```
...
accessType:
  type: string
  description: access type 
  enum:
    - public
    - private

...

NetworkConfig:
  properties:
    accessType:
      $ref : '#/definitions/accessType'
    ...
```
