### ISSUE TITLE
[Java] enum values can be called _ which does not compile in Java 11

### ISSUE THREAD

**Issue by eb3nezer** [swagger-api/swagger-codegen#11011]
##### Description

If you declare a string enum, swagger-codegen tries to convert the value into an identifier. This may result in an identifier called just "_". This is a valid identifier in Java <= 8, but not in Java 11.

Java reports the error
```
as of release 9, '_' is a keyword, and may not be used as an identifier
```

Related issue shows a case where this happens, but it is a general problem with "_" identifiers and Java 11. https://github.com/swagger-api/swagger-codegen/issues/10493

##### Swagger-codegen version

Not a regression afaik.

##### Swagger declaration file content or url

```yaml
    FieldValueClause:
      required:
      - "operator"
      type: "object"
      properties:
        operator:
          type: "string"
          description: "The operator between the field and operand."
          enum:
          - "="
          - "~="
```

This generates code like

```java
  /**
   * The operator between the field and operand.
   */
  public enum OperatorEnum {
    EQUAL("="),
    _("~=");
  }
```

##### Command line used for generation

swagger-codegen generate \
    -i input.yaml \
    -l java \
    -o .

##### Steps to reproduce

Try to compile the resulting code with Java 11.

##### Related issues/PRs

This issue demonstrates the same problem. The identifier compiles in Java 8, but not Java 11. https://github.com/swagger-api/swagger-codegen/issues/10493

##### Suggest a fix/enhancement

A better way to make identifiers unique rather than prefix underscores, esp for Java >= 9.
