### ISSUE TITLE
jaxrs-resteasy server library generates broken string enums from definitions section of swagger file

### ISSUE THREAD

**Issue by Claudio-YouCo** [swagger-api/swagger-codegen#11042]
##### Description

Generating a server with the jaxrs-resteasy library via the swagger-cli interface results in a broken enum class with undesired characters that prevent correct building of the final artifact, here is an example of the result (this happens with all the enums of this swagger and the result is always the same).

package it.fastweb.oss.tmf641.services.model;

import java.util.Objects;
import java.util.ArrayList;
import io.swagger.v3.oas.annotations.media.Schema;
import com.fasterxml.jackson.annotation.JsonValue;
import javax.validation.constraints.*;
public enum ServiceOrderStateType {
    {values&#x3D;[acknowledged, rejected, pending, held, inProgress, cancelled, completed, failed, partial, assessingCancellation, pendingCancellation], enumVars&#x3D;[{name&#x3D;ACKNOWLEDGED, value&#x3D;&quot;acknowledged&quot;}, {name&#x3D;REJECTED, value&#x3D;&quot;rejected&quot;}, {name&#x3D;PENDING, value&#x3D;&quot;pending&quot;}, {name&#x3D;HELD, value&#x3D;&quot;held&quot;}, {name&#x3D;INPROGRESS, value&#x3D;&quot;inProgress&quot;}, {name&#x3D;CANCELLED, value&#x3D;&quot;cancelled&quot;}, {name&#x3D;COMPLETED, value&#x3D;&quot;completed&quot;}, {name&#x3D;FAILED, value&#x3D;&quot;failed&quot;}, {name&#x3D;PARTIAL, value&#x3D;&quot;partial&quot;}, {name&#x3D;ASSESSINGCANCELLATION, value&#x3D;&quot;assessingCancellation&quot;}, {name&#x3D;PENDINGCANCELLATION, value&#x3D;&quot;pendingCancellation&quot;}]}
}

##### Swagger-codegen version

swagger-codegen-cli-3.0.25

##### Swagger declaration file content or url

Here is the enum declaration in the swagger yaml (Open API 3.0.1) file:

```yaml
components:
  schemas:
    ServiceOrderStateType:
      type: string
      description: Possible values for the state of the order
      enum:
        - acknowledged
        - rejected
        - pending
        - held
        - inProgress
        - cancelled
        - completed
        - failed
        - partial
        - assessingCancellation
        - pendingCancellation
```

##### Command line used for generation

java -jar swagger-codegen-cli-3.0.25.jar generate -i /root/Desktop/WebServices/TMF641_Mobile5G/TMF641-Service_Ordering-v4.0.0.swagger.yaml -l jaxrs-resteasy -o /root/Desktop/WebServices/TMF641_Mobile5G/server_resteasy/ -c /root/Desktop/WebServices/TMF641_Mobile5G/config.json

##### Steps to reproduce

Generating the server stub results in the bad classes corresponding to all enum types.
