### ISSUE TITLE
[PHp] Use server variables

### ISSUE THREAD

**Issue by vasikgreif** [swagger-api/swagger-codegen#11082]
Trying to find out how to use the server variables in the generated client. The server section in the yaml is:

```yaml
servers:
  - url: https://{environment}.relaypay.io/api/v1
    variables:
        environment:
          enum:
            - sandbox-api
            - api
          default: sandbox-api
```

Is there a way to specify the variables somehow in the generated PHP client?
