### ISSUE TITLE
[codegen][JAVA] Missing @pattern in generated code for field with format date-time

### ISSUE THREAD

**Issue by lmarsalek** [swagger-api/swagger-codegen#11131]
##### Description

If you try to define field with type string and with format: date-time like below the generator does not create any @pattern annotation. (target is "somehow" limit possible values of field with format date-time)

##### Swagger-codegen version

2.2.2

##### Input for codegen (YAML)
```
startDate:
  type: string
  format: date-time
  pattern: '^(199\d{1}|20\d{2})'
```

##### Output from codegen
@JsonProperty("startDate")
  @NotNull

private DateTime startDate = null;

##### Suggest a fix/enhancement
Codegen addx pattern (or another) annotation as ability to limit range of values in date-time format.
