### ISSUE TITLE
[Bug] Enum with Integer types does not generate the right fromValue signature and comparison

### ISSUE THREAD

**Issue by sbilello** [swagger-api/swagger-codegen#11166]
##### Description

Enum generation with Integer types does not work properly and I had to manually fix the 
 FROM
 ```
    @JsonCreator
    public static ApprovalTypeEnum fromValue(String text) {
      for (ApprovalTypeEnum b : ApprovalTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
    
```

TO  

```
@JsonCreator
    public static ApprovalTypeEnum fromValue(Integer value) {
      for (ApprovalTypeEnum b : ApprovalTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return null;
    }
```

##### Swagger-codegen version

3.0.27

##### Swagger declaration file content or url

```yaml

type: object
description: The base meeting object.
properties:
  topic:
    type: string
    description: The meeting's topic.
  type:
    type: integer
    description: |-
      The type of meeting:
      * `1` — An instant meeting.
      * `2` — A scheduled meeting.
      * `3` — A recurring meeting with no fixed time.
      * `8` — A recurring meeting with fixed time.
    default: 2
    #### THIS CAUSES PROBLEM IN THE SERIALIZATION BECAUSE THE ENUMS VALUES ARE NUMBERS AND NOT STRINGS
    enum:
      - 1
      - 2
      - 3
      - 8
    x-enum-descriptions:
      - Instant meeting.
      - Scheduled meeting.
      - Recurring meeting with no fixed time.
      - Recurring meeting with fixed time.
```
from https://github.com/sbilello/swagger-gen-bug-enum-parameters/blob/main/bug-client/src/main/resources/requests/createMeeting/RequestCreateMeeting.yml#L18-L21

##### Command line used for generation
```mvn compile```

##### Steps to reproduce

https://github.com/sbilello/swagger-gen-bug-enum-parameters

```mvn clean install```

##### Suggest a fix/enhancement

The problem is on the generator of the enum when the type is an integer. 
I will invest some time to fix the generator unless some volunteer can take care of it.
