### ISSUE TITLE
[Go] Why array query with incorrect name?

### ISSUE THREAD

**Issue by alexander-melentyev** [swagger-api/swagger-codegen#11241]
Hello!
I have query param in spec:
```
-  in: query
    required: false
    schema:
    title: Tags
    type: array
    items:
        type: string
        name: tags
```
But generated client makes URL like that: ?tag=tag1&tag=tag2
Correct url: ?tags=tag1&tags=tag2
