### ISSUE TITLE
Error occurs while build generated typescript 

### ISSUE THREAD

**Issue by carmelohuesca** [swagger-api/swagger-codegen#11272]
##### Description

On use the header menu item: Generate Client/typescript-angular all the definitions... All the definitions types with type:"string" and format: "date-time" returns in the generated models (into the models folder) a model with type "Date" and it should returns "string". 

##### Swagger-codegen version

Version 4.0.1

##### Swagger declaration file content or url

```yaml
birthdate:
 properties:
  type: string
  format: date```

Generates a model .ts: 
```ts
birthDate: string; // Well done!
```

```yaml
birthdate:
 properties:
  type: string
  format: date-time
```

Generates a model .ts: 
```ts
birthDate: Date; // Wrong!
```
The format property isn't a Json primitive.

##### Steps to reproduce

1. Declare a property with type: **string** and format: **date**
2. Declare another property with type: **string** and format **date-time**
3. Go to Menu /Generate Client / typescript-angular
4. Open zip file and find into the /models folder the generated type is (string for date // Well and Date for date-time // Wrong)
