### ISSUE TITLE
[req] Add v3 composition not support, json schema not

### ISSUE THREAD

**Issue by spacether** [swagger-api/swagger-codegen#11770]
Request to add v3 composition not support, json schema not

##### Description

How about adding support for schemas like:
```
AnyTypeExceptNull:
not:
  type: 'null'
ObjectWithoutColor:
  type: object
  not:
    type: object
    properties:
      color: {}
    required:
      - color
```

##### Swagger-codegen version

3.0.34

##### Swagger declaration file content or url

See above component schema definition

##### Command line used for generation

N/A

##### Steps to reproduce

Generate any client with the above schemas

##### Related issues/PRs

I didn't find any

##### Suggest a fix/enhancement

One could do something like openapi-generator did here:
https://github.com/OpenAPITools/openapi-generator/issues/8758
