### ISSUE TITLE
Java (jaxrs-resteasy) codegen generate unicode character in java class for Enum type

### ISSUE THREAD

**Issue by charlesxu2000** [swagger-api/swagger-codegen#11817]
##### Description
Enum type in openAPI definition, such as:
```
components:
  schemas:
    TestEnum:
      type: string
      nullable: true
      enum: 
       - ONE
       - TWO
```
The Java (jaxrs-resteasy) codegen generate the TestEnum.java class, contains unicode character (=), such as:
```
public enum TestEnum {
    {values&#x3D;[ONE, TWO], enumVars&#x3D;[{name&#x3D;ONE, value&#x3D;&quot;ONE&quot;}, {name&#x3D;TWO, value&#x3D;&quot;TWO&quot;}]}
}
```
