### ISSUE TITLE
Some strings get converted to a number (bug)

### ISSUE THREAD

**Issue by danieleds** [swagger-api/swagger-codegen#11928]
##### Description

Some strings get converted to a number when running swagger-codegen. For example, the following

```yaml
    phone_number_param_number:
      type: object
      properties:
        number:
          type: string
          required: true
          description: The phone number in E164 format.
          example: !!str "+15558675309"
```

will become

```yaml
    phone_number_param_number:
      type: object
      properties:
        number:
          type: string
          required: true
          description: The phone number in E164 format.
          example: +15558675309
```

which is interpreted by most YAML parsers as the positive number 15558675309.

##### Swagger-codegen version

3.0.33
3.0.34
3.0.35

##### Swagger declaration file content or url

```yaml
    phone_number_param_number:
      type: object
      properties:
        number:
          type: string
          required: true
          description: The phone number in E164 format.
          example: !!str "+15558675309"
```

##### Command line used for generation

docker run -v (pwd):/local swagger-codegen-cli-v3 generate -i /local/index.yaml -l openapi-yaml -o /local/combined

##### Steps to reproduce

Run the above command on a YAML file which includes a string field with value `"+15558675309"`.
