### ISSUE TITLE
Error parsing time with format "Y-m-d H:i:s"  in generated go client

### ISSUE THREAD

**Issue by melodyabikhalil** [swagger-api/swagger-codegen#11950]
##### Description

I'm using swagger-codegen to generate go docs from Laravel project.

When using the generated go client, I keep getting error `parsing time "2022-10-11 10:29:16" as "2006-01-02T15:04:05Z07:00"` when trying to fill the model after calling an API
![313931130_656216879425024_8040270276904435990_n](https://user-images.githubusercontent.com/41291710/199657413-e39b97e1-ac84-4b95-8642-6dd78e670a72.png)![313278347_653761633051714_414523623287948515_n](https://user-images.githubusercontent.com/41291710/199657403-069ea5bf-dff2-4858-aa1c-f7adb1e42fc4.png)

In the initial project, the annotation set for this field is 
`* @OA\Property(property="purchase_date",type="string", format="date-time")`

In the generated go client by swagger, the field is
`PurchaseDate time.Time `json:"purchase_date,omitempty"``

##### Swagger-codegen version

3.0.34

##### Swagger declaration file content or url

snippet from yaml file

```yaml
PurchaseResource:
      title: purchase_resource
      properties:
        id:
          type: integer
        external_id:
          type: string
        purchase_date:
          type: string
          format: date-time
```

##### Command line used for generation

`swagger-codegen generate -i api-docs.json -l go --api-package SubscriptionsClient -o ./client-go`
