### ISSUE TITLE
[GO] optional array parameterToString question

### ISSUE THREAD

**Issue by marunrun** [swagger-api/swagger-codegen#12124]
##### Description

i  have set the optional query  array params `Ids` like: `[]string{"a1","b2"}`.

i expect  the query string  : `Ids=a1&Ids=b2` , but got `Ids=a1b2`.

##### Swagger-codegen version

 ```
swagger-codegen version
3.0.42
```

##### Swagger declaration file content or url

```yaml
    - name: Ids
      in: query
      description: id array
      required: false
      style: form
      explode: true
      schema:
        type: array
        items:
          type: string
```

##### Command line used for generation

`swagger-codegen generate -i ./api/swagger.yaml -l go  -o ./`

##### Steps to reproduce

```go

type DefaultPostOpts struct {
	Ids         optional.Interface
}

func (a *DefaultApiService) ApiPost(ctx context.Context, localVarOptionals *DefaultPostOpts) (Response, *http.Response, error) { 
        ....

	if localVarOptionals != nil && localVarOptionals.Ids.IsSet() {
		localVarQueryParams.Add("Ids", parameterToString(localVarOptionals.Ids.Value(), "multi"))
	}
       ....
}

```

```go
client.DefaultApi.ApiPost(ctx, &DefaultPostOpts{
	Ids: optional.NewInterface([]string{"a1","b2"}),
})
```

##### Suggest a fix/enhancement

```go


if localVarOptionals != nil && localVarOptionals.Ids.IsSet() {
               appendQueryParams(localVarQueryParams,localVarOptionals.Ids.Value(),"Ids")
}

func appendQueryParams(queryParams url.Values, obj interface{}, key string) {
	kind := reflect.TypeOf(obj).Kind()
	if kind == reflect.Slice || kind == reflect.Array || kind == reflect.Map {
		for _, v := range obj.([]interface{}) {
			queryParams.Add(key, fmt.Sprintf("%v", v))
		}
	} else {
		queryParams.Add(key, fmt.Sprintf("%v", obj))
	}
}
```
