### ISSUE TITLE
Request headers not displaying correctly in html generated documentation

### ISSUE THREAD

**Issue by abeer-f** [swagger-api/swagger-codegen#12209]
##### Description

I'm using Swagger Hub to generate html documentation. The generated html does not display request headers correctly. I looked at similar issues on github but the problem has not been resolved. 

##### Swagger-codegen version

3.0

##### Swagger declaration file content or url

<!-- if it is a bug, a json or yaml that produces it.
If you post the code inline, please wrap it with
```yaml
paths:
  /ping:
    get:
      summary: Checks if the server is alive
      parameters:
        - in: header
          name: userId
          schema:
            type: integer
          required: true
          description: Numeric ID of the user to get
```

##### Related issues/PRs

![image](https://github.com/swagger-api/swagger-codegen/assets/91761578/51dd1f56-d497-4ef7-b226-0ddf34263827)

<img width="937" alt="requestheaderhtml" src="https://github.com/swagger-api/swagger-codegen/assets/91761578/3d0d18f0-9443-4c6a-8a95-82fcdeb6201b">
