### ISSUE TITLE
[python-flask] discriminator not working

### ISSUE THREAD

**Issue by estuardolh** [swagger-api/swagger-codegen#12229]
##### Description

I would like to implement an endpoint that receives one of two data types/structure.  Request type is defined by **request_type** field, but no matter which value I use always returns **'is valid under each of'** between the request and spec objects.
I ensured that my request is correct and matches with the specification but the implementation always returns 400 status.

##### Swagger-codegen version

swagger-codegen-cli-3.0.46

##### Swagger declaration file content or url

```
    RequestA:
      type: object
      required:
        - request_type
      properties:
        request_type:
          type: string
        SAT:
          type: string
          example: 123412
        Test:
          type: string
      discriminator:
        propertyName: request_type
    RequestO:
      type: object
      required:
        - request_type
      properties:
        request_type:
          type: string
        SAT:
          type: string
          example: 123412
      discriminator:
        propertyName: request_type
```

[Please see yml file](https://gist.github.com/estuardolh/5822fc30ec157d51bbbed1e026dc703a)

Request:
```
{
  "request_type": "access",
  "SAT": "123412",
  "Test": "example"
}
```

Error Response:
```
{
    "detail": "{'request_type': 'access', 'SAT': '123412', 'Test': 'example'} is valid under each of {'required': ['request_type'], 'type': 'object', 'properties': {'request_type': {'type': 'string'}, 'SAT': {'type': 'string', 'example': '123412'}, 'Test': {'type': 'string'}}, 'discriminator': {'propertyName': 'request_type'}}, {'required': ['request_type'], 'type': 'object', 'properties': {'request_type': {'type': 'string'}, 'SAT': {'type': 'string', 'example': '123412'}}, 'discriminator': {'propertyName': 'request_type'}}",
    "status": 400,
    "title": "Bad Request",
    "type": "about:blank"
}
```

I tried:
- Changing Discriminator statement order
- Checking generated .json file is correct
- Using allOf for inherence of the discriminator object
- Increasing logs but no explanation of the error
- Trimming my API except the endpoint where I have the problem
- Generating code with swagger-codegen-cli-**3.0.36**.jar instead of swagger-codegen-cli-**3.0.46**.jar

##### Command line used for generation

./jdk-20.0.2/bin/java -jar ./swagger-codegen-cli-3.0.46.jar generate -i ./rdt-api.yaml -l python-flask -t ./custom_templates -DpackageName=rdt_app_api

##### Steps to reproduce

1.  Draft a simple API to accept a request which can be one of two data structures.
2.  Generate code using swagger-codegen-cli-3.0.46.jar for python-flask and run it
3.  Send a request using Postman.

Please, help
