### ISSUE TITLE
Conversion from v2 to v3 incorrectly changes additionalProperties: {} into additionalProperties: type: object

### ISSUE THREAD

**Issue by veqryn** [swagger-api/swagger-codegen#12468]
##### Description
I have an OpenAPI v2 yaml that is being converted to v3 by swagger-codegen-cli, and it ends up changing the behavior of my models from allowing any freeform additional properties of any type, to only allowing properties of type object.

##### Swagger-codegen version
3.0.61

##### Swagger declaration file content or url
My [openapi v2 yaml](https://github.com/veqryn/awesome-go-api/blob/b7251b13af2bad90c593302d83036b5dac6a1149/protobufv3/openapiv2/gen/awesome.swagger.yaml#L147) includes:
```yaml
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
```

This is converted by swagger-codegen-api into [this yaml](https://github.com/veqryn/awesome-go-api/blob/b7251b13af2bad90c593302d83036b5dac6a1149/protobufv3/openapiv3/gen/openapi.yaml#L160-L161):
```yaml
    protobufAny:
      type: object
      properties:
        '@type':
          type: string
      additionalProperties:
        type: object
```

##### Command line used for generation
`swagger-codegen-cli generate -i ./openapiv2/gen/awesome.swagger.yaml -l openapi-yaml -o ./openapiv3/gen/`

##### Steps to reproduce
See above

##### Related issues/PRs
N/A

##### Suggest a fix/enhancement
This v2 yaml should convert to `additionalProperties: {}` or `additionalProperties: true`
