### ISSUE TITLE
[Java][ENUM] it doesn't expose ENUM VALUES inside the class

### ISSUE THREAD

**Issue by tabetan** [swagger-api/swagger-codegen#1357]
Hi,
When I build java source code for the following snippet:
  
```
loyaltyCardType:
    type: string
    enum:
      - LOYALTY
      - PASS
      - NONE
  addressType:
    type: string
    enum: ["BILLING", "DELIVERY", "DELIVERY_AND_BILLING"] 
```

The Java classes do not expose the values. Is this a bug?

THANK YOU

Below the generated Java class.
```
package io.swagger.client.model;
import io.swagger.client.StringUtil;

import io.swagger.annotations.*;
import com.fasterxml.jackson.annotation.JsonProperty;

@ApiModel(description = "")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2015-10-08T13:03:30.881Z")
public class AddressType   {
  
  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddressType {\n");
    
    sb.append("}");
    return sb.toString();
  }
}
```

**Comment by fehguy** [comment]
Please share more of your spec, it doesn't look like that's valid.  I expect to see something like this:

```yaml
  properties:
    loyaltyCardType:
      type: string
      enum:
      - LOYALTY
      - PASS
      - NONE
    addressType:
      type: string
      enum: 
      - BILLING
      - DELIVERY
      - DELIVERY_AND_BILLING
```
