### ISSUE TITLE
qt5cpp codegen assigns values to double/float points in init

### ISSUE THREAD

**Issue by baverbud** [swagger-api/swagger-codegen#1461]
When using the qt5cpp codegen target doubles and floats are specified in the generated class definitions as pointers. 

In the ::init method though, floating point literals are assigned to the pointers. This can't be compiled.

Either doubles/floats shouldn't be pointers, or ::init should handle allocation/set to NULL.

Example:

SWGMyModel.h:
```cpp
  double* height;
  float*     width;
```
SWGMyModel.cpp:
```cpp
SWGMyModel::init() {
height = 0.0;
width  = 0.0f;
}
```

swagger yaml:
```yaml
      height:
        description: Height of the box
        type: number
        format: double
      width:
        description: Width of the box
        type: number
        format: float
```
