### ISSUE TITLE
Generating List of Enums

### ISSUE THREAD

**Issue by himanshuy** [swagger-api/swagger-codegen#1542]
Swagger 2 does not generate List of Enums. For example:
```
services:
    type: array
      items:
        type: string
         enum:
            - TEST1
            - TEST2
            - TEST3
```

Generates `List<String> services;` without any enums.
