### ISSUE TITLE
Valid yaml file generates API error in node js server

### ISSUE THREAD

**Issue by deefactorial** [swagger-api/swagger-codegen#1631]
Original issue posted on editor.
https://github.com/swagger-api/swagger-editor/issues/731

basically a Large integer value in the yaml file gets converted to scientific notation in the generate server function and returns an API Error in the node js server because it thinks there is an error in the yaml file.

**Comment by wing328** [comment]
Thanks for reporting the issue. I'm able to repeat the issue and the parameter with incorrect setting is shown below:
```
      parameters:
      - name: "size"
        in: "query"
        description: "Size of array"
        required: true
        type: "integer"
        minimum: 1.448727080024E12
        format: "int64"
```
To fix the issue, a good starting point is https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/NodeJSServerCodegen.java#L241

May I know if you've time to contribute a fix ?
