### ISSUE TITLE
why return null in  io.swagger.codegen.DefaultCodegen.toDefaultValue(Property) 

### ISSUE THREAD

**Issue by Mumutu** [swagger-api/swagger-codegen#1663]
I saw this in `io.swagger.codegen.DefaultCodegen.toDefaultValue(Property) `
```
        if (p instanceof StringProperty) {
            return "null";
        } else if (p instanceof BooleanProperty) {
            return "null";
        } else if (p instanceof DateProperty) {
            return "null";
        } else if (p instanceof DateTimeProperty) {
            return "null";
       }
```
I think this makes the `default` property  in `definition` not working. when the type in above types
maybe the `StringProperty` can return a non-null value if `default` has been set?
Am I misunderstanding something?

**Comment by fehguy** [comment]
i believe this is for initializing variables, not setting the default value from the spec.

**Comment by Mumutu** [comment]
Thanks for replying~  the `defaultValue` in mustache confused me ~ so how can I set default value to ensure sane the `definition` I defined. I can't find a way anywhere except the default.

**Comment by wing328** [comment]
@Mumutu Can you demonstrate the issue with a Swagger spec?

**Comment by Mumutu** [comment]
@wing328 Sorry for replying so late. I am using a modified 2.1.4 snapshot which give the maven plugin an option of `library` , and I am using `java retrofit library`.
```
 @SerializedName("{{baseName}}")
  private {{{datatypeWithEnum}}} {{name}} = {{{defaultValue}}};
```
my domain definition is 
```
Worksummary:
    description: work summary of the order
    type: object
    properties:
      datestr:
        type: string
        description: date String for display
        default: abc2
      beautician_id:
        type: integer
        description: beautician id
      beautician_name:
        type: string
        description: beautician name
        default: abc
      beautician_head:
        type: integer
        format: int32
        description: imageId of the beautician
        default: 0
      content:
        type: string
        description: content
        default: ""
      order_id:
        type: string
        description: associated order Id
        default: ""
    required:
      - beautician_id
      - content
      - order_id
```
I excepted the default would take effect, and  fehguy said
|   initializing variables, not setting the default value from the spec

and i believe it now.  In fact the integer property `beautician_head` 's  default value was not passed in the `toDefault` method, so definitely I used a wrong way to set `defaultValue`.

Though currently I change the `toDefault` method to return the default Value with 
···
   \"+  sp.getDefault() +\"
```
and I achieve what I want ( in a wrong way~~  so I want to know the right way to ensure sane the model. ( maybe only the Enum has a default Value?
