### ISSUE TITLE
Swagger enum definition is not correctly mapped to Java Client

### ISSUE THREAD

**Issue by hiveship** [swagger-api/swagger-codegen#1746]
I am trying to generate a Java client to a Swagger definition of an API.

In my Swagger file, I have the following:
```yaml
    definitions:
    MediumStatus:
    type: string
        enum:
          - CLOSED
          - OPEN_AVAILABLE
          - OPEN_NOT_AVAILABLE
          - NOT_AVAILABLE
```
      

so in Java language, I excpect to get something like:
```java
public enum MediumType
{
	CLOSED,
	OPEN_AVAILABLE,
	OPEN_NOT_AVAILABLE,
	NOT_AVAILABLE;

	public String value()
	{
		return name();
	}

	public static MediumType fromValue(String v)
	{
		return valueOf(v);
	}
}
```
but with Swagger codegen I got:
```java
@ApiModel(description = "")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2015-12-21T14:03:23.470Z")
public class MediumType   {
  
  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class MediumType {\n");
    
    sb.append("}");
    return sb.toString();
  }
}
```
wich I think is not really correct :(

I am missing something ?
