### ISSUE TITLE
javascript - incorrect process examples section

### ISSUE THREAD

**Issue by PavelPolyakov** [swagger-api/swagger-codegen#1968]
Hi,

Here is my yaml:
```yaml
  responses:
    200:
      description: "industries"
      schema:
        type: object
        properties:
          metadata:
            $ref: ../../../definitions/structures/metadata.yaml
          items:
            type: array
            items:
              $ref: ../../../definitions/structures/industry.id.yaml
      examples:
        application/json: |-
          {
               "metadata": {
                   "offset": 0,
                   "limit": 10,
                   "totalCount": 2
               },
               "items": [{
                   "id": 5,
                   "name": "Computer sience",
                   "country": "PL",
                   "locale": "pl_PL"
               }, {
                   "id": 10,
                   "name": "Chemistry",
                   "country": "PL",
                   "locale": "pl_PL"
               }]
           }
```

Hereis the code generated by swagger-codegen:
```javascript
  examples['application/json'] = "{\n     \"metadata\": {\n         \"offset\": 0,\n         \"limit\": 10,\n         \"totalCount\": 2\n     },\n     \"items\": [{\n         \"id\": 5,\n         \"name\": \"Computer sience\",\n         \"country\": \"PL\",\n         \"locale\": \"pl_PL\"\n     }, {\n         \"id\": 10,\n         \"name\": \"Chemistry\",\n         \"country\": \"PL\",\n         \"locale\": \"pl_PL\"\n     }]\n }";

```

And, the issue is, that it's treated as string, so, when I generate mock and launch the server, I receive a text, not JSON, when querying the mock server.
![image](https://cloud.githubusercontent.com/assets/839290/12552073/9f844f86-c36f-11e5-9f63-e534ee0c926a.png)
![image](https://cloud.githubusercontent.com/assets/839290/12552066/8f27a886-c36f-11e5-8c26-585d79fb469f.png)

So, it should be processed in the different way, to allow it reply with proper JSON, like this:
![image](https://cloud.githubusercontent.com/assets/839290/12552094/cee3b302-c36f-11e5-8ee4-a63079fbe54b.png)

Regards,

**Comment by webron** [comment]
What if the mime type was `plain/text`? Or `application/xml`? Not sure it makes sense to cover all mime type cases.

**Comment by PavelPolyakov** [comment]
Yes, but the current approach has no sense, because it's not possible to use the current output.

If we don't want to cover all the possible outputs, then we should have option to pass some custom processor or somehow extend the generated code.

It's possible to do right now manually updating the generated code, but it would be overwritten with the new mock generation.

**Comment by xhh** [comment]
Hi @PavelPolyakov, were you using the `nodejs` server codegen?

It seems the *example* in your spec is indeed of type `string`, could you try something like this?
```yaml
      examples:
        application/json:
          metadata:
            offset: 0
            limit: 10
            totalCount: 2
          items: # ommitted
```

**Comment by PavelPolyakov** [comment]
@xhh 

it works, but - how can I describe the array this way?
please, help :)

tried like this:
```
       application/json:
          metadata:
            offset: 0
            limit: 10
            totalCount: 2
          items:
            type: array
            items:
              hello:
                a: 1
                b: 2
```

however, go the object as output

Regards,

**Comment by xhh** [comment]
@PavelPolyakov you can refer to the accepted answer here: [YAML equivalent of array of objects in JSON](http://stackoverflow.com/a/33989696/243797)

**Comment by PavelPolyakov** [comment]
@xhh 

Thanks, man. It works!

So the conclusion is: if you want to get JSON as output - use plain YAML, not wrap anything in {}.

Here is the complete example:
```yaml
      examples:
        application/json:
          metadata:
            offset: 0
            limit: 10
            totalCount: 2
          items:
            - hello: a
              bello: b
            - hello: 3
              bello: 4
```
