### ISSUE TITLE
[Haskell-Servant] generator creates code that does not compile due to invalid data types

### ISSUE THREAD

**Issue by jhedev** [swagger-api/swagger-codegen#2319]
I used the master branch (commit: a4ec9b9) to generate the haskell-servant code for the API defined here: http://data.deutschebahn.com/apis/fahrplan/db-fahrplan-api-specification.yaml

The generated code does not compile due some problems with the generated record data types:

### Invalid names of record fields

For example: 

```yaml
LocationList:
    type: object
    required:
      - StopLocation
    properties:
      StopLocation:
        type: array
        items:
          $ref: '#/definitions/StopLocation'
```
produces code with upper case record field names:

```haskell
data LocationList = LocationList
    { StopLocation :: [StopLocation]
    } deriving (Show, Eq, Generic)
```

which is invalid code.

Another problem arises with the spec (is this actually allowed?):

```yaml
Note:
    type: object
    required:
      - key
      - priority
      - routeIdxFrom
      - routeIdxTo
      - $
    properties:
      key:
        type: string
      priority:
        type: integer
        format: int32
      routeIdxFrom:
        type: integer
        format: int32
      routeIdxTo:
        type: integer
        format: int32
      $:
        type: string
```

which produces

```haskell
data Note = Note
    { key :: String
    , priority :: Integer
    , routeIdxFrom :: Integer
    , routeIdxTo :: Integer
    , $ :: String
    } deriving (Show, Eq, Generic)
```

`$` is not a valid field name.

### Data types without fields

The spec 

```yaml
  LocalTime:
    type: string
  LocalDate:
    type: string
```

will generate empty data types, like this:

```haskell
data LocalTime = LocalTime
    { 
    } deriving (Show, Eq, Generic)
```

I'm not sure if this is really a problem with the code generator or if the specification is the problem. Maybe someone else can help me.
