### ISSUE TITLE
Swift code generator can't handle an enum field having a reserved word for a name

### ISSUE THREAD

**Issue by conet** [swagger-api/swagger-codegen#2362]
Since PR #1993 was merged which fixed issue #1992 the swift code generator can't handle properties named using a reserved word. For example an enum property named type will produce uncompilable code. For example adding this perfectly valid property to any model will generate uncompilable code:
`"type":{"type":"string","enum": ["Type1","Type2"]}`
Will result in:
`Testing failed:
    '_type' used within its own type
** TEST FAILED **`

**Comment by conet** [comment]
See PR #2363 which adds a test case for this.

**Comment by dylan-colaco** [comment]
Is there any update on this? I'm getting the same error because the generated swift code uses the same name "_type" for a property as well an enum name.

**Comment by bobrosoft** [comment]
same sick issue ... fortunately found old swagger JAR to generate in old way.

**Comment by wing328** [comment]
If you can share a spec to help us easily reproduce the issue, we will look into this further.

@jaz-ah @Edubits

**Comment by bobrosoft** [comment]
Sorry, haven't time to create full swagger spec, but if you add next object
```
  SocialProfile:
    type: object
    properties:
      type:
        type: string
        example: facebook
        enum:
          - facebook
          - google
          - twitter
          - linkedin
          - instagram
          - github
          - email
          - phone
          - custom
      user:
        type: string
        example: '1567677783'
      accessToken:
        type: string
        example: gh76576567thjkjhjkjhwkjehewqo9uwq666787878678
      attributes:
        type: object
        properties: {}
```
and generate Swift sources, it will generate
```
public class SocialProfile: JSONEncodable {

   public enum _type: String { 
       case Facebook = "facebook"
       case Google = "google"
       case Twitter = "twitter"
       case Linkedin = "linkedin"
       case Instagram = "instagram"
       case Github = "github"
       case Email = "email"
       case Phone = "phone"
       case Custom = "custom"
   }
   
   public var _type: _type? // <-- here will be compilation error "'_type' used within its own type"
```
and will throw "'_type' used within its own type" compilation error, because class can't have property and nested type definition of same name.

Possible solution is to have next in the end: `public var type: _Type?` (`type` word is allowed in Swift, `Type` is not) or `public var _type: _Type?`. enum should be named correspondingly.
