### ISSUE TITLE
Enum values OFF and ON not getting generated properly.

### ISSUE THREAD

**Issue by Heedster** [swagger-api/swagger-codegen#2559]
I observed this weird issue today when generating java client using maven codegen plugin, that enum values like OFF and ON are somehow ignored. Lets say in my YAML definition, there is: 
```
laziness:
        description: Flag to denote whether laziness should be enabled or disabled.
        type: string
        enum: [ ON, OFF ]
```

In the above scenario, no enum type is generated, and the class member laziness have the type String.
But, If the definition was as follows: 
```
laziness:
        description: Flag to denote whether laziness should be enabled or disabled.
        type: string
        enum: [ ON, OFF, MEH ]
```

Codegen generates the enum with just one value - MEH, and the class member is assigned the enum type. 

But if I put quotes around them, like:
```
laziness:
        description: Flag to denote whether laziness should be enabled or disabled.
        type: string
        enum: [ "ON", "OFF", "MEH" ]
```
All values are included in the generated enum. 

I use the latest version of swagger-codegen-maven-plugin, version 2.1.6

**Comment by webron** [comment]
Well, here's an interesting bit of information about YAML - values such as `yes`, Yes`, `On`, `on` and their respective negative forms are actually considered boolean `true`/`false` values. What? Yes. 
So when translating

```yaml
laziness:
        description: Flag to denote whether laziness should be enabled or disabled.
        type: string
        enum: [ ON, OFF ]
```
to JSON, you'd actually get....

```json
{
  "laziness": {
    "description": "Flag to denote whether laziness should be enabled or disabled.",
    "type": "string",
    "enum": [
      true,
      false
    ]
  }
}
```
And those aren't really valid values for a string-typed property are they? So they inadvertently  end up being ignored.

How to work around it? Just like you did - you have to wrap the values in quotes. This is not really a bug with the codegen, this is just how YAML works.

For reference - http://yaml.org/type/bool.html
