### ISSUE TITLE
Problem with dashes in header params

### ISSUE THREAD

**Issue by BernhardBln** [swagger-api/swagger-codegen#2585]
Hey,

I'm using the header param "X-Auth-Token":

```
parameters:
  x-auth-token:
    name: X-Auth-Token
    in: header
    description: The authorisation token
    required: true
    type: string
```

However, when generating Spring MVC Server, it generates this code:

```
@RequestHeader(value="xAuthToken", required=true) String xAuthToken
```

Seems like by mistake, the variable name (which correctly was turned into "xAuthToken") is wrongly used as the value in @RequestHeader. In my opinion, the original name "X-Auth-Token" should be used there.
