### ISSUE TITLE
password in toString in generated model

### ISSUE THREAD

**Issue by BernhardBln** [swagger-api/swagger-codegen#2662]
When using format "password", e.g.

```
  credentials:
    type: object
    properties:
      username:
        type: string
      password:
        type: string
        format: password
    required:
    - username
    - password

```

the field "password" is contained in the toString method of the generated model class.

In my opinion, that's a security issue (you don't want client passwords appearing in log files etc.)

Would it make sense to change the corresponding line in toString to:

`        sb.append("  password: ").append("<protected>").append("\n");`

whenever the format "password" is used?

**Comment by wing328** [comment]
Agree with you that password should be not captured in the log file.

Technically it's possible by introducing a new boolean flag `isPassword` that can be used in the template.

**Comment by BernhardBln** [comment]
But why do you need this extra flag? You already have the "password" format, as shown in my example above. IMHO, that should be enough to exclude the password.

Otherwise you end up always setting up both:

```
password:
        type: string
        format: password
        isPasswort: true
```

But I don't think that is necessary.
