### ISSUE TITLE
Generate enums with integer values assigned

### ISSUE THREAD

**Issue by kenjitayama** [swagger-api/swagger-codegen#2690]
I want to generate enum with integer values assigned.

Swift:
```swift
enum Weather: Int {
    case Sunny = 1
    case Cloudy = 2
    case Rainy = 3
}
```

Java:
```java
public enum Weather {
    Sunny(1),
    Cloudy(2),
    Rainy(3);

    private final int type;

    private Weather(final int price) {
        this.type = type;
    }

    public type getType() {
        return type;
    }
}
```

But I couldn't figure out how to do this.

In the [Swagger 2.0 specs](http://swagger.io/specification/), it references [JSON Schema specs](http://json-schema.org/latest/json-schema-validation.html#anchor76) for `enum`.
It says any type can be used, but it seems like `type` needs to be `string` for generating enums. Like this:

```
definitions:
  weather:
    type: object
    required:
      - type
    properties:
      type:
        type: string
        enum:
          - Sunny
          - Cloudy
          - Rainy
```

If I change `type` to `integer`, no enum is generated, and it will be a plain integer property.

Firstly, I couldn't find how to assign integers to enum items using Swagger specs.

Are there any plans or workarounds to support this kind of enum?

**Comment by wing328** [comment]
@kenjitayama For Java, it will be taken care of by https://github.com/swagger-api/swagger-codegen/pull/2508, which adds better support for enum (number, string, special characters) in PHP, C# and Java.

For Swift, we want to do it as part of https://github.com/swagger-api/swagger-codegen/pull/2508 as well. Currently, we're adding better enum support for JS in that PR.

**Comment by kenjitayama** [comment]
Thanks for the quick response! I will be watching the issue 👍

**Comment by wing328** [comment]
@kenjitayama  https://github.com/swagger-api/swagger-codegen/pull/2508 has been merged into master so it should cover at least Java. Please pull the latest master and give it a try.

**Comment by kenjitayama** [comment]
@wing328 
Thanks for the notice! 
Looking forward for Swift support too :)

I wasn't sure of the supported yaml syntax and I tried the following.
Only weather3 generated an enum.

```yaml
definitions:
  weather1:
    type: object
    required:
      - type
    properties:
      type:
        type: integer
        enum:
          - Sunny
          - Cloudy
          - Rainy
  weather2:
    type: object
    required:
      - type
    properties:
      type:
        type: integer
        enum:
          - 1
          - 2
          - 3
  weather3:
    type: object
    required:
      - type
    properties:
      type:
        type: integer
        format: int32
        enum:
          - 1
          - 2
          - 3
  weather4:
    type: object
    required:
      - type
    properties:
      type:
        type: integer
        format: int32
        enum:
          - Sunny
          - Cloudy
          - Rainy
```

weather3 produced Java code :

```java
public enum TypeEnum {
    NUMBER_1(1),
    NUMBER_2(2),
    NUMBER_3(3);

    private Integer value;

    TypeEnum(Integer value) {
      this.value = value;
    }

    @Override
    @JsonValue
    public String toString() {
      return String.valueOf(value);
    }
  }
```
Is there any syntax for having custom names for each enum items?

weather3 caused exception for Swift (I guess not supported yet) :
```
Exception in thread "main" java.lang.RuntimeException: Could not process model 'weather3'
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:244)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:223)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:36)
Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
	at io.swagger.codegen.languages.SwiftCodegen.fromProperty(SwiftCodegen.java:331)
```

**Comment by wing328** [comment]
For weather1 and weather4, I don't think it's valid as the enum is string but the type is integer.

For enum naming convention, is there any reference? The most common one I saw is adding the "Enum" suffix (e.g. StatusEnum).

**Comment by kenjitayama** [comment]
> For weather1 and weather4, I don't think it's valid as the enum is string but the type is integer.

I agree. Tried them in case I could find out something.

> For enum naming convention, is there any reference? The most common one I saw is adding the "Enum" suffix (e.g. StatusEnum).

Looks like I couldn't express my question correctly.
Is there a way to get
```
public enum TypeEnum {
    Sunny(1),
    Cloudy(2),
    Rainy(3);
```

Instead of 
```
public enum TypeEnum {
    NUMBER_1(1),
    NUMBER_2(2),
    NUMBER_3(3);
```
?

**Comment by wing328** [comment]
Don't think we support that at the moment.

Should be mapping be done in the server side, which means the client will send the string "Sunny" and the server will map it to 1 (in database, etc)?

**Comment by kenjitayama** [comment]
> Don't think we support that at the moment.

This was what I was looking for…, but thanks for sharing.

> Should be mapping be done in the server side, which means the client will send the string "Sunny" and the server will map it to 1 (in database, etc)?

In my case, the client needs to send and retrieve `1` knowing that it means "Sunny".
Maybe this kind of server API design is considered not good, but I need to stick with it.
I guess the best that I can do is to describe them with `description:`, and write enums manually.

**Comment by wing328** [comment]
@kenjitayama technically we can support it via vendor extension with code changes in how to handle the enum mapping.

**Comment by kenjitayama** [comment]
I see that the Swagger specs itself doesn't support this use case.
I think the vendor extension could be something like this:

```
properties:
  type:
    type: integer
    format: int32
    enum:
      - 1
      - 2
      - 3
    x-enumNames:
      - Sunny
      - Cloudy
      - Rainy 
```

I saw swagger-codegen supporting a vendor extension before (x-swagger-router-controller) , so I recognize that it's position is not closed for supporting vendor extensions.
It will be great if I can see this happen in the future.
Maybe this is something that can go into Open API 3.0 specs?
