### ISSUE TITLE
Python client codegen can silently ignore enums

### ISSUE THREAD

**Issue by icefoxen** [swagger-api/swagger-codegen#2700]
I have a data type definition:
```yaml
  TaskResult:
    type: object
    properties:
      task_id:
        description: The ID number of the task
        type: string
        format: uuid
      status:
        description: The current state of the task
        enum:
          - PENDING
          - RUNNING
          - COMPLETE
          - FAILED
      result:
        description: The result of the task, if any.
        type: object
```

And yet when my generated python client runs against this API, I get:

```python
{'result': None, 'task_id': '...'}
```

With the TaskResult class having no mention of the `status` property at all.

**Comment by icefoxen** [comment]
Fixed by changing the status section of my definition to:
```yaml
   status:
        description: The current state of the task
        type: string
        enum:
          - PENDING
          - RUNNING
          - COMPLETE
          - FAILED
```

But it'd be really nice to have Swagger or the generator output a warning in this case...
