### ISSUE TITLE
Python client codegen doesn't even try to handle formats it doesn't recognize

### ISSUE THREAD

**Issue by icefoxen** [swagger-api/swagger-codegen#2701]
I have a data type definition:

```yaml
  TaskResult:
    type: object
    properties:
      task_id:
        description: The ID number of the task
        type: string
        format: uuid
      status:
        description: The current state of the task
        enum:
          - PENDING
          - RUNNING
          - COMPLETE
          - FAILED
      result:
        description: The result of the task, if any.
        type: object
```

The Swagger client doesn't specify the "uuid" string format.  But it still generates references to a "UUID" object which doesn't exist:

```python
# from python_client/models/task_result.py"
class TaskResult(object):
    def __init__(self):
        self.swagger_types = {
            'task_id': 'UUID',
            'status': 'str',
            'result': 'object'
        }
```

It seems it would be more sensible to simply use a "str" object rather than referring to a UUID object which doesn't exist, or generate a stub UUID object that is just a "str".  Or maybe even generate a UUID object with hooks that the user can override from a different module without digging into the machine-generated code...
