### ISSUE TITLE
Bug with -l qt5cpp and datatype "Date"

### ISSUE THREAD

**Issue by philicious** [swagger-api/swagger-codegen#2706]
I have in my Swagger definition

```
  TransactionsObject:
    type: object
    properties:
      from:
        type: string
        format: date
      to:
        type: string
        format: date
```

and in my generated code 
```
#include "SWGDate.h"
......
    SWGDate* getFrom();
    void setFrom(SWGDate* from);
   SWGDate* getTo();
    void setTo(SWGDate* to);

private:
    SWGDate* from;
    SWGDate* to;
```

but there is no `SWGDate.h`file. Also https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/Qt5CPPGenerator.java#L114 suggests that Date should be mapped to Qts own datatype `QDate`

I tried with master HEAD aswell as http://editor.swagger.io
