### ISSUE TITLE
Root security object not in output Swagger.yaml

### ISSUE THREAD

**Issue by vipera** [swagger-api/swagger-codegen#2821]
Hi, I'm having an issue with applying a root-level security scheme to my API. I have this in my Swagger 2.0 file:

```yaml
securityDefinitions:
  my_auth:
    type: oauth2
    description: Two-legged OAuth
    tokenUrl: http://localhost:3000/oauth2/token
    flow: application
security:
- my_auth
```

And yet when I run it through the (Sinatra) server codegen, the outputted yaml looks like this (I'm using the default `{{{swagger-yaml}}}` template):
```yaml
# ... (securityDefinitions object unchanged)
securityRequirement:
- {}
```

I can't seem to find any documentation for `securityRequirement`, whatever it is. Is this a bug, unsupported or am I doing something wrong? Cheers!
