### ISSUE TITLE
[swift] enum properties results in empty file

### ISSUE THREAD

**Issue by romk1n** [swagger-api/swagger-codegen#2897]
in 2.1.5 and 2.1.6 if our yaml file declares enum as 

```
state:
    type: string
    enum:
      - "ON"
      - "OFF"
      - "N/A"
```

the resulting file generates for state.swift is 
```
//
// StreamState.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class State: JSONEncodable {

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
```
