### ISSUE TITLE
[Qt5/C++] Wrong default value for integers

### ISSUE THREAD

**Issue by philicious** [swagger-api/swagger-codegen#3192]
##### Description

datatypes `qint32` and `qint64` are rendered with default value `= NULL;` but should be `0`

##### Swagger-codegen version

latest from editor.swagger.io

##### Suggest a Fix

I think it somehow has to do with https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/Qt5CPPGenerator.java#L254 but for some reason it doesnt walk into the `} else if (p instanceof IntegerProperty) `

**Comment by wing328** [comment]
@philicious editor.swagger.io is not using the latest version of swagger codegen.

Mind sharing the spec so that we can more easily reproduce the issue?

**Comment by philicious** [comment]
@wing328 ye I know. But I've seen it being `=NULL` also with code generated from swagger-codegen/master ~2 weeks ago.

I didnt share any spec as its trivial and doesnt require any special case. Simply have integer properties like
```
  NewsListObject:
    type: object
    properties:
      categoryId:
        type: integer
      page:
        type: integer
      favorites:
        type: boolean
```
which results in 
```
private:
    qint32 categoryId;
qint32 page;
bool favorites;
// thats fine
```
and
```
void
SWGNewsListObject::init() {
    categoryId = NULL;  // this isnt the best default value for an int
page = NULL; // likewise
favorites = false;
}
```

**Comment by YetAnotherMinion** [comment]
Confirmed this bug is still present off master as of 4e20bd9bab43ce21f21954a45402ca49df5a2a64

**Comment by YetAnotherMinion** [comment]
It looks like this happens when the property is a `BaseIntegerProperty`. I am unfamiliar with how code generators are supposed to be written, so I do not know if the fix here is just to add a check for the `BaseIntegerProperty` to the else tree, which will solve this, or if the generator should always be choosing a specialization for integer.

**Comment by wing328** [comment]
@philicious @YetAnotherMinion PR merged into master. Please pull the latest master to give it a try.

**Comment by wing328** [comment]
Thanks again for the PR from @YetAnotherMinion

**Comment by philicious** [comment]
awesome @YetAnotherMinion ! I cant try myself right now but it would certainly make sense to also try with

```
definitions:
  NewsListObject:
    type: object
    properties:
      categoryId:
        type: integer
        format: int32
      page:
        type: integer
        format: int64
      favorites:
        type: boolean
```

but maybe only having `type: integer` is a `BaseIntegerProperty` and with a format specified its `IntegerProperty` and was working before already. cc @wing328
