### ISSUE TITLE
php slim generator - models

### ISSUE THREAD

**Issue by gsantner** [swagger-api/swagger-codegen#3200]
##### Description

Generated Model code for PHP - Slim contains only `private` members, and no constructor.  
Usually you use the models and set the properties, please add boilerplate code, so this doesn't need to be done every time after generating.
I first thought of default public, because I mostly use it just as data container (..wrong way to resolve the issue). A simple constructor would be enough, which includes all members of the model class.

Please provide in the PHP Slim codegen
- Empty default constructor for models
- Constructor for models with all members
##### Swagger-codegen version

2.10.1
##### Swagger declaration file content or url

Default from swagger.io.
Model Example:

```
  Product:
    type: object
    properties:
      product_id:
        type: string
        description: Unique identifier representing a specific product for a given latitude & longitude. For example, uberX in San Francisco will have a different product_id than uberX in Los Angeles.
      description:
        type: string
        description: Description of product.
      display_name:
        type: string
        description: Display name of product.
      capacity:
        type: string
        description: Capacity of product. For example, 4 people.
      image:
        type: string
        description: Image URL representing the product.
```
##### Suggest a Fix

For example above:

```
<?php
/*
 * Product
 */
namespace SwaggerServer\lib\Models;

/*
 * Product
 */
class Product {
    /* @var string $productId Unique identifier representing a specific product for a given latitude &amp; longitude. For example, uberX in San Francisco will have a different product_id than uberX in Los Angeles. */
    private $productId;
/* @var string $description Description of product. */
    private $description;
/* @var string $displayName Display name of product. */
    private $displayName;
/* @var string $capacity Capacity of product. For example, 4 people. */
    private $capacity;
/* @var string $image Image URL representing the product. */
    private $image;

/** NEW 
    function __construct() {
        // Default constructor
    }

    function __construct($productId, $description, $displayName, $capacity, $image) {
        $this->productId = $productId;
        $this->description = $description;
        $this->displayName = $displayName;
        $this->capacity = $capacity;
        $this->image = $image;
    }
** NEW END **/
}
```
