### ISSUE TITLE
Android Client - Post request doesn't work

### ISSUE THREAD

**Issue by gsantner** [swagger-api/swagger-codegen#3208]
##### Description
Post requests with the generated android client do not work. It always makes some kind of GET request, or fail because of an Null Pointer (HttpEntitiy = null).
There is absolutely **NO documentation**, no examples and nothing that would describe if I did something wrong or right.

Just as a note: GET-Requests work as intended, I receive the right data.

##### Swagger-codegen version
2.10.1

##### Swagger declaration file content or url

```
  /entry/add:
    post:
      summary: Add an entry
      description: text
      parameters:
        - name: userId
          in: query
          type: integer
          format: int64
          required: true
          description: user id 
        - name: latitude
          in: query
          type: number
          format: double
          required: true
          description: latitude of client
        - name: longitude
          in: query
          type: number
          format: double
          required: true
          description: Longitude of client
```

##### Steps to reproduce

* Initalize API, make new EntriesApi Object (Done in own/nonUi Thread)
* Call entriesApi.entryAddPost(arg1,arg2....)
* Crash..

##### Suggest a Fix

Note: https://github.com/swagger-api/swagger-codegen/pull/3131 tried to workaround that issue with the HttpEntity problem, but entity is ALWAYS null, the object never gets initialized with an instance.
