### ISSUE TITLE
[Java] Propertie __name and name overlaps

### ISSUE THREAD

**Issue by Project0** [swagger-api/swagger-codegen#3290]
Assume it exists two properties with similar names (and yes this happens really...): 
```
properties:
    name:
        description: NO DESCRIPTION
        readOnly: true
        type: string
    __name:
        description: NO DESCRIPTION
        readOnly: true
        type: string
```
The code generator will generate the propertie "name" with setter and getter twice
```
  private String name = null;
  private String name = null;

  @ApiModelProperty(example = "null", value = "NO DESCRIPTION")
  @JsonProperty("__name")
  @Override
  public String getName() {
    return name;
  }

  @ApiModelProperty(example = "null", value = "NO DESCRIPTION"")
  @JsonProperty("name")
  public String getName() {
    return name;
  }
```
