### ISSUE TITLE
[Qt5/C++] Arrays of primitive types not working

### ISSUE THREAD

**Issue by philicious** [swagger-api/swagger-codegen#3410]
##### Description

this swagger

```
  Product:
    type: object
    properties:
      categories:
        type: array
        description: Category Ids
        items:
          type: integer
```

results in 

```
//.h
QList<qint32>* categories;  // ok !
//.cpp
obj->insert("categories", QJsonValue(categories));  // bad
```

instead of obj->insert.. it should use `toJsonArray` from SWGHelpers

Its working fine if the arrays items are SWG\* objects
##### Swagger-codegen version

latest from git
##### Command line used for generation

`java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -t modules/swagger-codegen/src/main/resources/qt5cpp -i ../retailers.yaml -l qt5cpp -o ../generated-retailer`
##### Steps to reproduce

generate an SDK based on a spec with primitive type in array
##### Suggest a Fix

model-body.mustache template needs to be adjusted. I lack swagger-codegen internals knowledge
