### ISSUE TITLE
[Go] [Bug] Generated code case-ifies parameter name.

### ISSUE THREAD

**Issue by neilotoole** [swagger-api/swagger-codegen#3462]
##### Description

My swagger file has a query param `project_id`. The generated code sends this as `projectId`.

##### Swagger-codegen version

`master`

##### Swagger declaration file content or url

```yaml
post:
      summary: xxx
      description: |
      operationId: add_notification_target
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: project_id
          in: query
          description: XXX
          required: true
          type: integer
          format: int32
```

Results in Go code:

```go
	queryParams.Add("projectId", a.Configuration.APIClient.ParameterToString(projectId, ""))
```

##### Suggest a Fix

We should not sanitize/caseify parameters.
