### ISSUE TITLE
[YAML] Allow for "one of the following is required" when marking parameters as required

### ISSUE THREAD

**Issue by janxious** [swagger-api/swagger-codegen#3542]
##### Description

Feature Request! One of our APIs takes two different parameters, and it is built such that if either is present, it is a valid requrest, but if neither or both are present, if it is not valid.

##### Swagger-codegen version

`v2.2.0`

##### Swagger declaration file content

I might imagine something like the following (and I'm adding in a "one or more" option, too, just for kicks):
```yaml
definitions:
  MashedYam:
    type: object
    required:
      - yam
    required_one:
       - [garlic, onion]
       - [butter, milk]
    required_n:
       - [salt, pepper, chalula]
```

I am playing fast and loose with yaml, but hopefully that is demonstrative. It says to make a successful mashed yam, I need: a yam; one of garlic or onion; one of butter or milk; one or more of salt, pepper, and chalula. So, maybe not a great recipe!
