### ISSUE TITLE
[SPRING] Enum used in List generated incorrectly

### ISSUE THREAD

**Issue by timothd** [swagger-api/swagger-codegen#3575]
##### Description:

A property defined as enum, type integer, generates correctly, but the moment the property is a List, containing enums (of type integer), the code that gets generated are incorrect.

The "FilteredAggregationsEnum" correctly creates a constructor with type Integer, but the enums declares, e.g. _0("0"), calls constructor with a String "0" instead of Integer 0. Any ideas why this happens?

See below snippets:

This yaml:

``` yaml
AcceptanceStatus:
    format: int32
    enum:
    - 0
    - 1
    - 2
    - 3
    type: integer
```

Produce the following java code:

``` java

  public enum AcceptanceStatusEnum {
    NUMBER_0(0),

    NUMBER_1(1),

    NUMBER_2(2),

    NUMBER_3(3);

    private Integer value;

    AcceptanceStatusEnum(Integer value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }
```

Whereas this yaml:

``` yaml
  FilteredAggregations:
    type: array
    items:
      format: int32
      enum:
      - 0
      - 1
      - 2
      - 100
      - 200
      type: integer
```

Produce the following java code:

``` java

  public enum FilteredAggregationsEnum {
    _0("0"),

    _1("1"),

    _2("2"),

    _100("100"),

    _200("200");

    private Integer value;

    FilteredAggregationsEnum(Integer value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  private List<FilteredAggregationsEnum> filteredAggregations = new ArrayList<FilteredAggregationsEnum>();
```

This is the maven plugin detail used:

``` xml
<plugin>
    <groupId>io.swagger</groupId>
    <artifactId>swagger-codegen-maven-plugin</artifactId>
    <version>2.2.1</version>
    <executions>
        <execution>
            <goals>
                <goal>generate</goal>
            </goals>
            <configuration>
                <inputSpec>src/main/resources/api.yaml</inputSpec>
                <language>spring</language>
                <modelPackage>org.mypackage.model</modelPackage>
                <output>target</output>

                <configOptions>
                    <sourceFolder>generated-sources</sourceFolder>
                </configOptions>

                <environmentVariables>
                    <!-- models to generate -->
                    <models></models>
                </environmentVariables>
            </configuration>
        </execution>
    </executions>
</plugin>
```
