### ISSUE TITLE
Integer type default ignored on Spring Server generation

### ISSUE THREAD

**Issue by mherb63** [swagger-api/swagger-codegen#3633]
##### Description
When generating Spring Server code from swaggerhub, default value is not being generated.

The YAML:

``` yaml
       "oneWayIfdvCounter": {
          "description": "One-way IFDV counter per configured IFDV Measurement Bin - A 32-bit counter per Measurement Bin that counts the number of IFDV measurements that fall within the configured bin",
          "type": "integer",
          "default": -1
        },
```

The Spring generated code
```java
  private Integer oneWayIfdvCounter = null;
```

##### Swagger-codegen version

swaggerhub.com as of 23-Aug-2016
