### ISSUE TITLE
[Ruby, PHP] Errors with slashes in pattern

### ISSUE THREAD

**Issue by scop** [swagger-api/swagger-codegen#3703]
##### Description

For this in YAML syntax:
```yaml
pattern: '^a/b$'
```
...the PHP code generated is:
```php
if (!preg_match("/^a/b$/", ...
```
...and for Ruby:
```ruby
Regexp.new(/^a/b$/)
```
The problem with both is that the slash between `a` and `b` should be backslash escaped to avoid errors. I tried this in `DefaultCodegen.addRegularExpressionDelimiter`:
```java
return "/" + pattern.replace("/", "\\/") + "/";
```
...but it makes no difference on the eventual output.

##### Swagger-codegen version

Current master

**Comment by wing328** [comment]
Your fix should work.
```
scala> var a = "^a/b$"
a: String = ^a/b$

scala> a.replace("/", "\\/")
res0: String = ^a\/b$
```
Please submit a PR and I'll do some tests

**Comment by scop** [comment]
I agree it _should_ work, but as said, in my tests it did not end up resulting any changes to those problematic ruby and php code spots -- for some reason, the slash remained unescaped there. Anyway, #3707 is the PR.

**Comment by wing328** [comment]
@scop I did some tests with your PR and have no idea either as it failed to escape forward slash.

@cbornet when you've time, I wonder if you can take a look to see if you've any clue why the replace does not work as intended

**Comment by ePaul** [comment]
I debugged this a bit ... the problem might be that the result of this method gets later passed through DefaultCodegen.escapeText, which does (between others) this: `.replace("\\/", "/"))` – i.e. it undoes the transformation.

input | method | output 
---|------|------
`[A-Z]/.*` | `addRegularExpressionDelimiter` | `/[A-Z]\/.*/`
`/[A-Z]\/.*/` | `escapeJava(...)` | `/[A-Z]\\/.*/`
`/[A-Z]\\/.*/` | `.replace("\\/", "/"))` | ` /^[A-Z]\/.*/`
` /^[A-Z]\/.*/` | `unescapeJava(...)` | `/^[A-Z]/.*/`
`/^[A-Z]/.*/` | `.replaceAll("[\\t\\n\\r]", " ")` | `/^[A-Z]/.*/`
`/^[A-Z]/.*/` | `.replace("\\", "\\\\")` | `/^[A-Z]/.*/`
`/^[A-Z]/.*/` | .replace("\"", "\\\"") | `/^[A-Z]/.*/`
`/^[A-Z]/.*/` | escapeUnsafeCharacters(...) | `/^[A-Z]/.*_/` 
`/^[A-Z]/.*_/` | .trim() | `/^[A-Z]/.*_/`

This is about the same result as we get when not adding the escaping before.
I'm not sure what the idea of this `escapeText` method in DefaultCodegen is – it unescapes, replaces, escapes again, replaces some more, and again escapes. It looks quite brittle, and is likely not made for regular expressions.

**Comment by wing328** [comment]
@ePaul thanks for the detailed troubleshooting results. We'll try to address this after the 2.2.2 release.

**Comment by gierschv** [comment]
+1 on this issue for the Ruby Client:

A pattern `^[A-Za-z0-9\-_.]+$` will be transformed to:

```

**Comment by 4n70w4** [comment]
The same problem with io.swagger.codegen.languages.SymfonyServerCodegen

```
definitions:
  FiltersRow:
    type: object
    properties:
      arguments:
        type: string
        pattern: '^[a-z0-9-_\s]*$'
```

generated

```
/**
 * Class representing the FiltersRow model.
 *
 * @package Swagger\Server\Model
 * @author  Swagger Codegen team
 */
class FiltersRow 
{

    /**
     * @var string|null
     * @SerializedName("arguments")
     * @Assert\Type("string")
     * @Type("string")
     * @Assert\Regex("/^[a-z0-9-_\\s]*$/")
     */
    protected $arguments;
```

and incorrect regexp don't work!

**Comment by haminhcong** [comment]
I have same issue with python client:

This is my swagger `yaml` document:

```
  User:
    required:
      - username
      - password
    type: object
    properties:
      id:
        title: ID
        type: integer
        readOnly: true
      username:
        title: Username
        description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_
          only.
        type: string
        pattern: ^[\w.@+-]+$
        maxLength: 150
        minLength: 1
      first_name:
        title: First name
        type: string
        maxLength: 30
      last_name:
        title: Last name
        type: string
        maxLength: 150
      email:
        title: Email address
        type: string
        format: email
        maxLength: 254
      is_active:
        title: Active
        description: Designates whether this user should be treated as active. Unselect
          this instead of deleting accounts.
        type: boolean
      password:
        title: Password
        type: string
        maxLength: 128
        minLength: 1
```

and this is python client code gennerated by swagger codegen:

```python


class User(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'username': 'str',
        'first_name': 'str',
        'last_name': 'str',
        'email': 'str',
        'is_active': 'bool',
        'password': 'str'
    }

    attribute_map = {
        'id': 'id',
        'username': 'username',
        'first_name': 'first_name',
        'last_name': 'last_name',
        'email': 'email',
        'is_active': 'is_active',
        'password': 'password'
    }

    def __init__(self, id=None, username=None, first_name=None, last_name=None, email=None, is_active=None, password=None):  # noqa: E501
        """User - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._username = None
        self._first_name = None
        self._last_name = None
        self._email = None
        self._is_active = None
        self._password = None
        self.discriminator = None

        if id is not None:
            self.id = id
        self.username = username
        if first_name is not None:
            self.first_name = first_name
        if last_name is not None:
            self.last_name = last_name
        if email is not None:
            self.email = email
        if is_active is not None:
            self.is_active = is_active
        self.password = password

    @property
    def id(self):
        """Gets the id of this User.  # noqa: E501


        :return: The id of this User.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this User.


        :param id: The id of this User.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def username(self):
        """Gets the username of this User.  # noqa: E501

        Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.  # noqa: E501

        :return: The username of this User.  # noqa: E501
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this User.

        Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.  # noqa: E501

        :param username: The username of this User.  # noqa: E501
        :type: str
        """
        if username is None:
            raise ValueError("Invalid value for `username`, must not be `None`")  # noqa: E501
        if username is not None and len(username) > 150:
            raise ValueError("Invalid value for `username`, length must be less than or equal to `150`")  # noqa: E501
        if username is not None and len(username) < 1:
            raise ValueError("Invalid value for `username`, length must be greater than or equal to `1`")  # noqa: E501
        if username is not None and not re.search(r'^[\\w.@+-]+$', username):  # noqa: E501
            raise ValueError(r"Invalid value for `username`, must be a follow pattern or equal to `/^[\\w.@+-]+$/`")  # noqa: E501

        self._username = username


```
