### ISSUE TITLE
[Scalatra] collectionFormat=csv not handled correctly

### ISSUE THREAD

**Issue by jtnystrom** [swagger-api/swagger-codegen#3806]
##### Description

When collectionFormat is explicitly set, incorrect code is generated by the Scalatra generator.
For example, with this specification:

```
      parameters:
      - name: assayIds
        description: "Assay IDs to retrieve metadata for"
        in: query
        type: array
        collectionFormat: csv
```

the following code is generated:

```
      val assayIdsString = params.getAs[String]("assayIds")
      val assayIds = if("csv".equals("default")) {
        assayIdsString match {
          case Some(str) => str.split(",")
          case None => List()
        }
      }
      else
        List()
```

The main issue here is that the comparison "csv" == "default" will clearly never be true, so the string will never be split. We will always get an empty list back.
According to the swagger specification, supported values for collectionFormat are 'csv', 'tsv', 'ssv', 'pipes' and 'multi'. 

This is in the latest github snapshot.

A secondary issue is that the type of assayIds is inferred to be simply Serializable in this case, which is not very helpful (the value becomes unusable). This is because Array[String] and List[Any] do not unify to a common supertype.
This can be solved, for example, by generating either this code (which I tested):

```
     assayIdsString match {
          case Some(str) => str.split(",").toSeq
          case None => Seq()
        }
```

Or this:

```
     assayIdsString match {
          case Some(str) => str.split(",")
          case None => Array[String]()
        }
```
