### ISSUE TITLE
[Swift] Question

### ISSUE THREAD

**Issue by papageo** [swagger-api/swagger-codegen#3920]
##### Description

POST/PUT image with swift generated code.
##### Swagger-codegen version

Version 2.1.3

I want to post an image using the generated swift-client. After a lot of researching I think the best way to specify this is:

```
/user/profilepicture:
    put:
      description: |
        upload profile picture of user
      consumes:
        - multipart/form-data
      parameters:
        - name: profilePhoto
          in: formData
          type: file
```

The generated swift client function signature is:
`public class func usersProfilepicturePut(profilePhoto profilePhoto: NSURL? = nil, completion: ((error: ErrorType?) -> Void))`

The problem I am having is the NSURL type. The reason is that it seems very difficult to get an NSURL out of a UIImage, especially if the photo has been taken from the camera with the UIImagePickerController and not yet saved.

Then again I do not want to change the type of the parameter to a string, and use a base64 encoding because it adds a lot of overhead to convert the image to a string.
1. Could someone verify that my yaml spec is correct? (I am choosing file type, because the only other data type I could use to upload a photo is string, with format Byte, but that would lead in an overhead to convert the photo in string.
2. Is there a way to change/override the generated NSURL type?

Thanks
