### ISSUE TITLE
Question: Creating immutable model objects by yaml files.

### ISSUE THREAD

**Issue by aliemrahpekesen** [swagger-api/swagger-codegen#3937]
##### Question

Is it possible to generate immutable objects by yaml modification?

##### Usage example

    ```yaml
     CreatePerson
         type: object
         **immutable: true**  -- Is this possible?
         ...
         properties:
                     ....

**Comment by fehguy** [comment]
Yes, per https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#schema-object

```
 CreatePerson
     type: object
     readOnly: true
     properties:
        myId:
          # also legal in properties
          readOnly: true
```
