### ISSUE TITLE
Path parameter named "path" breaks generated Go client code

### ISSUE THREAD

**Issue by mlamina** [swagger-api/swagger-codegen#4079]
##### Description

If you have a path parameter called "path", the generated Go client will not compile, because the API client methods try to declare a variable called "path", which clashes with the method argument, which is also named "path".
##### Swagger-codegen version

2.2.1
##### Swagger declaration file content or url

``` yaml
paths:
  /{path}:
    parameters:
      - name: path
        in: path
        description: Absolute path of an object.
        type: string
        required: true
    put:
      summary: Create an object
      operationId: uploadObject
      tags:
        - Objects
```

Generated Go code:

``` go
func (a ObjectsApi) UploadObject(path string) (*ObjectMetaData, *APIResponse, error) {

    var httpMethod = "Put"
    // create path and map variables
    path := a.Configuration.BasePath + "/{path}"
    path = strings.Replace(path, "{"+"path"+"}", fmt.Sprintf("%v", path), -1)

        // ... //
}
```
##### Command line used for generation

`java -jar swagger-codegen-cli.jar generate -i swagger.yaml -l go`
##### Steps to reproduce

Generate the code and try to compile it
##### Suggest a Fix

Implement a check which prevents the generation of method arguments that might clash with local variable names.
