### ISSUE TITLE
JAX-RS Swagger codegen does not handle enum defined in external json file

### ISSUE THREAD

**Issue by abhijith-prabhakar** [swagger-api/swagger-codegen#4123]
If an enum is added into external json file Swagger Codegen does not generate model correctly.
Example project:  https://github.com/abhijith-prabhakar/swagger-ref-error-demo/blob/master/src/main/resources/v1/schema/title/title.json#L43

```
 "media_types": {
      "description": "different media types",
      "type": "array",
      "items" : {
        "type" : "string",
        "enum" : [ "application/pdf", "application/json" ]
      }
    },
```
Generated Code
```java
/**
   * different media types
   */
  public enum List&lt;MediaTypesEnum&gt; {
    PDF("application/pdf"),

        JSON("application/json");
    private List&lt;String&gt; value;

    List&lt;MediaTypesEnum&gt;(List&lt;String&gt; value) {
      this.value = value;
    }

    @Override
    @JsonValue
    public String toString() {
      return String.valueOf(value);
    }
  }
```

**Comment by omarzina** [comment]
Hi, I'm having same problem i think. Tried generating resteasy server from yaml with:
```
TaskType:
        type: string
        description: "Tipo de tarea asociada. cancelación, agenda, etc."
        enum:
          - cancelation
          - schedule
```
with resulting generated enum:
```
public enum TaskType {
    {values&#x3D;[cancelation, schedule], enumVars&#x3D;[{name&#x3D;CANCELATION, value&#x3D;&quot;cancelation&quot;}, {name&#x3D;SCHEDULE, value&#x3D;&quot;schedule&quot;}]}, 
}
```
If i use jaxrs server generator instead of resteasy it works fine.
