### ISSUE TITLE
Array of string values as query parameter is not generated in jersey2 server side code

### ISSUE THREAD

**Issue by shailendrajain24** [swagger-api/swagger-codegen#4148]
Please suggest how to pass List into GET type method.

```
paths:
'/test':
get:
   parameters:
      - name: test1
          in: query
          description: 'This field can contain List of test item.'
          required: true
          schema:
            type: array
            items:
              type: string
          collectionFormat: "multi"
```

```
Output:
@ApiParam(value = "This field can contain List of test item.",required=true) @QueryParam("test1") 
  @NotNull String test1

```

But we want List<String> instead of String like this:
```
@ApiParam(value = "This field can contain List of test item.",required=true) @QueryParam("test1") 
  @NotNull List<String> test1
```
