### ISSUE TITLE
[Java] Property name 'no' renamed to 'false' during code generation

### ISSUE THREAD

**Issue by Sunracer** [swagger-api/swagger-codegen#4180]
##### Description

I have a YAML file with a definition with property named '**no**'. When generating Java code from the YAML file, the property '**no**' is renamed to '**false**' which leads to various problems during Java compilation.

##### Swagger-codegen version

swagger-codegen-cli-2.2.1.jar

##### Swagger declaration file content or url

```yaml
MyDefinition:
    type: object
    properties:
      no:
        type: string
```
Generated code:
```java
@SerializedName("false")
private String false = null;
...
public void setFalse(String false) {
    this.false = false;
}
```
##### Command line used for generation

java -jar ~/swagger-codegen-cli-2.2.1.jar generate -i my_yaml_file.yaml -l java -o .

##### Suggest a Fix

It would seem that swagger-codegen translates 'yes'/'no' to 'true'/'false', but it shouldn't do it for name definitions.

**Comment by Sunracer** [comment]
Swagger-codegen generates code like this from the definition above:
```
@SerializedName("false")
private String false = null;
...
public void setFalse(String false) {
    this.false = false;
}
```

**Comment by wing328** [comment]
@Sunracer I can repeat the issue and will submit a fix after revising the logic on renaming property name.

**Comment by ePaul** [comment]
That looks like a YAML "feature". `n`, `FALSE`, `No`, `off` are interpreted as boolean false, `Y`, `true`, `Yes`, `ON` as boolean true.

These don't make much sense in property names (which should be strings anyways), but the YAML parser doesn't know that.
@Sunracer try to use quotation marks in your YAML:

```yaml
MyDefinition:
    type: object
    properties:
      'no':
        type: string
```
