### ISSUE TITLE
[typescript-angular2] Bug generating namespace with specific types 

### ISSUE THREAD

**Issue by reinerRubin** [swagger-api/swagger-codegen#4182]
Bug generating namespace with specific types.

##### Description

I have swagger "ObjectPreview" type. According [this line](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/TypeScriptAngular2ClientCodegen.java#L149) it starts with "LanguageSpecificPrimitiv" (Object). And there is not "model." prefix in generated code.

##### Swagger-codegen version

master

##### Swagger declaration file content or url

```yaml
definitions:
  ObjectPreview:
    type: object
    properties:
      ID:
        type: integer
        format: int64  
```

```typescript
// ...
    list?: Array<ObjectPreview>;
// ...
    objectsPreview?: ObjectPreviews;
// ...
// etc.
```

##### Suggest a Fix

It was [array fix commit](https://github.com/swagger-api/swagger-codegen/commit/d84c1cdfd797774b2ebe6912b66e606e55e94bb0). So I think we need additional check type for generic via "<".

Can I make pr with this fix?
