### ISSUE TITLE
[Java] Bug generating Java model with '_class' property

### ISSUE THREAD

**Issue by menchauser** [swagger-api/swagger-codegen#4236]
##### Description

This issue is similar to #2841. swagger-codegen may produce invalid code for model like
```
  test:
    type: object
    properties:
      '_class':
        type: string
```

Result code contains inelligible overload for method Object.getClass():
```
    public String getClass() {
        return _class;
    }
```

##### Swagger-codegen version

Latest (2.2.2-SNAPSHOT)
