### ISSUE TITLE
[jaxrs-(resteasy|spec)] Bug generating arrays of enums

### ISSUE THREAD

**Issue by alechenninger** [swagger-api/swagger-codegen#4315]
##### Description

Objects with a property that is an array of enums generates code that does not compile with server JAXRS code generation.

Client code generation (at least the default -l java configuration) does not have the same issue.

##### Swagger-codegen version

2.2.2-SNAPSHOT

##### Swagger declaration file content or url

```yaml
EnumArrayTest:
  type: object
  properties:
    enums:
      type: array
      items:
        type: string
        enum:
          - test1
          - test2
```

```java
public class EnumArrayTest   {


  /**
   * Gets or Sets enums
   */
  public enum List&lt;EnumsEnum&gt; {
    TEST1("test1"),

        TEST2("test2"),
    private List&lt;String&gt; value;

    List&lt;EnumsEnum&gt;(List&lt;String&gt; value) {
      this.value = value;
    }

    @Override
    @JsonValue
    public String toString() {
      return String.valueOf(value);
    }
  }


  /**
   * Gets or Sets enums
   */
  public enum EnumsEnum {
    TEST1("test1"),

        TEST2("test2"),
    private String value;

    EnumsEnum(String value) {
      this.value = value;
    }

    @Override
    @JsonValue
    public String toString() {
      return String.valueOf(value);
    }
  }

  private List<EnumsEnum> enums = new ArrayList<EnumsEnum>();
```

##### Command line used for generation

swagger-codegen generate -i swagger.yaml -l jaxrs-resteasy -o server-resteasy/

##### Steps to reproduce

Use yaml from above.
Generate -l jaxrs-resteasy using command from above.
