### ISSUE TITLE
Proposal: Assist  escapeReservedWord with custom mappings

### ISSUE THREAD

**Issue by alexandern** [swagger-api/swagger-codegen#4416]
##### Description

The escapeReservedWord  method does its job fairly well, but in some cases  "reserved words" make some properties look a bit odd in some languages. 

##### Swagger-codegen version
Master

##### Swagger declaration file content or url

```
definitions:
  Pet:
    required:
      - id
    properties:
      id:
        type: integer
        format: int64
     name: 
        type: string
```

```
  Car:
    required:
      - id
      - name
      - range
    properties:
      range:
        type: array
        items:  
          type: integer
      id:
        type: integer
        format: int64
      name:
        type: string
```

##### Command line used for generation
`java -jar swagger-codegen-cli.jar generate -i pet.yaml -l objc -o output`
`java -jar swagger-codegen-cli.jar generate -i car.yaml -l go -o output`

##### Suggest a Fix
The method escapeReservedWord could be assisted through an additional command line parameter (reserved-words-mappings).

In the case of Objective-C, the definition below would create a property named _id which could mistakenly be interpreted as an iVar.

```
definitions:
  Pet:
    required:
      - id
    properties:
      id:
        type: integer
        format: int64
     name: 
        type: string
```

which in turn yields

```
@interface SWGPet : SWGObject
@property(nonatomic) NSNumber* _id;
@property(nonatomic) NSString* name;
@end
```
The escapeReservedWord method could look up what _id should be substituted with instead.

For example,
`java -jar swagger-codegen-cli.jar generate -i pet.yaml -l objc --reserved-words-mappings id=identifier -o output`

The new output

```
@interface SWGPet : SWGObject
@property(nonatomic) NSNumber* identifier;
@property(nonatomic) NSString* name;
@property(nonatomic) NSString* tag;
@end
```

GoLang can also benefit from this, for example
```
  Car:
    required:
      - id
      - name
      - range
    properties:
      range:
        type: array
        items:  
          type: integer
      id:
        type: integer
        format: int64
      name:
        type: string
```

Instead of this
```
type Car struct {
	Range_ []int32 `json:"range,omit empty"
	Id int64 `json:"id,omit empty"
	Name string `json:"name,omit empty"
}
``````
It could generate

```
type Car struct {
	Ranges []int32 `json:"range,omit empty"
	Id int64 `json:"id,omit empty"
	Name string `json:"name,omit empty"
}
``````
by using
`java -jar swagger-codegen-cli.jar generate -i car.yaml -l go --reserved-words-mappings Range=Ranges -o output`

I've implemented this in my own fork/branch, but I would like to hear your opinion. A preliminary implementation can be seen here

https://github.com/alexandern/swagger-codegen/commit/ed886b58d208eba861f0bcb917da6795109360a3

Commits: https://github.com/alexandern/swagger-codegen/commits/issue-4416
