### ISSUE TITLE
[java/spring] codegen for parameters with square brackets not correct (jsonapi)

### ISSUE THREAD

**Issue by stevecookform3** [swagger-api/swagger-codegen#4460]
##### Description

Parameters with square brackets (as used by jsonapi) e.g. filter[account_number]=12345 are not generated with correct request mapping. In this example the code generated is ```@RequestParam(value = "filterAccountNumber")```. Changing this to ```@RequestParam(value = "filter[account_number]")``` resolves the issue (though I'm not sure if this causes other problems).

##### Swagger-codegen version

2.2.2-SNAPSHOT

##### Swagger declaration file content or url

```
      parameters:
        - name: filter[account_number]
          in: query
          description: Filter by account number
          required: false
          type: array
          items:
            type: string
          collectionFormat: csv
```

##### Command line used for generation

`java -jar swagger-codegen-cli.jar generate -v -i ./swagger.yaml -l spring -o .`

##### Steps to reproduce

Run codegen to generate a spring server. Run the spring server and pass the parameter e.g. 

`http://localhost:8090/v1/accounts?filter[account_number]=ABC123`

You can see that the `List<String> filterAccountNumber` is always null.

Changing the RequestParam mapping in the controller resolves the issue.

##### Suggest a Fix

Updating queryParams.mustache seems to fix:

`... @RequestParam(value = "{{baseName}}"...`
