### ISSUE TITLE
[Java/Android] date/dateTime are generated as String

### ISSUE THREAD

**Issue by gsantner** [swagger-api/swagger-codegen#4465]
##### Description
I have setup this field in a model:
```
      creationDate:
        type: string
        format: datetime
        description: Entry ** Timestamp of creation
      modificationDate:
        type: string
        format: datetime
        description: Entry ** Timestamp of modification
```
Generated Code:
```
  @SerializedName("creationDate")
  private String creationDate = null;

  @SerializedName("modificationDate")
  private String modificationDate = null;
```

* I tried multiple date libraries, all generate `String`. (legacy and Joda). Seems not to change anything at all / is ignored.

```
java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate \
-D hideGenerationTimestamp=true \
-D serializableModel=true \
-i ../swagger.yaml \
-D dateLibrary=joda \
-l java --library=okhttp-gson \
-o /tmp/code/ 
```

Expected is a Date object (depending on lib.)

##### Swagger-codegen version

<https://github.com/swagger-api/swagger-codegen/commit/aed21bba733bcabeeda0e05331a24e32ec1edc4f>

##### Swagger declaration file content or url
Posted above

##### Command line used for generation

Posted above

##### Steps to reproduce

Run codegen
