### ISSUE TITLE
default for Primitive types instead of wrapper classes

### ISSUE THREAD

**Issue by luke83** [swagger-api/swagger-codegen#4475]
##### Description

I would like to generate java code (retrofit2 library) with java primitive types instead of java wrapper classes.

Integer -> int
Boolean -> boolean
Float -> float

##### Swagger-codegen version

2.2.1

##### Swagger declaration file content or url

```yaml
    ForbiddenResponse:
    properties:
      success:
        type: boolean
        default: false
      data:
        type: object
        properties:
          code:
            type: integer
            default: 0
```

##### Command line used for generation

```
java
  -jar ./modules/swagger-codegen-cli/target/swagger-codegen-cli.jar  
    generate 
      -i path/to/api 
      -l java 
      -c retrofit2.json 
      -o path/to/out
      --language-specific-primitives boolean,int,float 
      --type-mappings Integer=int,Boolean=boolean,Float=float
```

#### Generated code:

Default for boolean primitive is correctly handled with

```java
public class ForbiddenResponse {
  @SerializedName("success")
  private boolean success = false;
```

Default for int primitive is not correctly handled (null instead 0, setted as default)
```java
public class ForbiddenResponseData {
  @SerializedName("code")
  private int code = null;
```

#### Desired code:

```java
public class ForbiddenResponse {
  @SerializedName("success")
  private boolean success = false;
```

```java
public class ForbiddenResponseData {
  @SerializedName("code")
  private int code = 0;
```

**Comment by wing328** [comment]
@luke83 thanks for the feedback. It's definitely reasonable to use primitive type instead of wrapper class. In your swagger/openapi spec, have you set a proper default value for the property?

Ref: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/Java/pojo.mustache#L30

**Comment by luke83** [comment]
@wing328 thanks for your response. I have an integer property (code) and i set its default this way (this is a snippet):

```
ForbiddenResponse:
    properties:
      success:
        type: boolean
        default: false
      data:
        type: object
        properties:
          code:
            type: integer
            default: 0
```

Reading the spec i found only reference to ``default``, is this *definition* for ``code`` property correct? The definition above give me null instead of 0 for property code, same result if i move code one level up, directly inside ForbiddenResponse (model/pojo) definition

**Comment by fehguy** [comment]
@luke83 it'll be hard to do this within the generator because of how we treat nulls, etc.  I'd suggest looking into sending a PR to add this.

**Comment by capsur** [comment]
@luke83 @fehguy @wing328 This issue exactly doesn't seem to be related to swagger codegen, the problem is that `BaseIntegerProperty` doesn't support a default value: https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-models/src/main/java/io/swagger/models/properties/BaseIntegerProperty.java

For example:

```yaml
Competition:
    properties:
      id:
        type: integer
        format: int32
        default: 0
```
will lead to:
```java
public class Competition {
  @SerializedName("id")
  private int id = 0;
```
Do you know why `BaseIntegerProperty` doesn't support default values?
