### ISSUE TITLE
Allowable values not returned correctly in error message

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-codegen#4645]
##### Description

This is a non-operational issue, but in the php client, the `allowableValues` are listed in a response error message when a model property is constrained by `enum`.  In the current (2.2.2-SNAPSHOT) version, this value is not correct, which gives an incorrect error message to the caller

For example:

```yaml
definitions:
  PaymentMethods:
    properties:
      cardTypes:
        type: string
        enum:
        - Visa
        - Discover
        - Amex
```

The generated code looks like this:

```php
    public function listInvalidProperties()
    {
        $invalid_properties = [];
        $allowed_values = ["Visa", "Discover", "Amex"];
        if (!in_array($this->container['card_types'], $allowed_values)) {
            $invalid_properties[] = "invalid value for 'card_types', must be one of #{allowed_values}.";
        }

        return $invalid_properties;
    }
```
