### ISSUE TITLE
additionalProperties using ref to file does not generate correctly

### ISSUE THREAD

**Issue by JLLeitschuh** [swagger-api/swagger-codegen#4688]
##### Description

Generating a map type in swagger where `additionalProperties` references a file results in the resulting simplified swagger file being wrong:

**Result of the yaml generator**
```yaml
definitions:
  FabricControllerMap:
    type: "object"
    additionalProperties:
      $ref: "./definitions/FabricController.yaml#/FabricController"
  FabricController:
    allOf:
    - $ref: "#/definitions/PlexxiObject"
    - properties:
        apiVersion:
          type: "string"
        connectionFailedCount:
          type: "integer"
          format: "int64"
          readOnly: true
        # Ect.....
```

Result of the spring code generator
```java
/**
 * FabricControllerMap
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2017-01-31T13:48:25.402-05:00")

public class FabricControllerMap extends HashMap<String, DefinitionsFabricControllerYamlFabricController>  {
    // ....
```

##### Swagger-codegen version

Latest master

##### Swagger declaration file content or url

**./definitions/FabricController.yaml**
```yaml
FabricController:
  type: object
  description: |
    The abstract representation of all types of Ports.
  allOf:
  - $ref: './definitions/PlexxiObject.yaml#/PlexxiObject'
  - properties:
      apiVersion:
        type: string
      connectionFailedCount:
        type: integer
        format: int64
        readOnly: true
     # ect.....
```

**./definitions/FabricControllerMap.yaml**
```yaml
FabricControllerMap:
  type: object
  additionalProperties:
    $ref: './definitions/FabricController.yaml#/FabricController'
```

**./swagger.yaml**
```yaml
# More above
parameters:
  FabricControllerListBody:
    name: fabricController
    in: body
    required: true
    schema:
      type: array
      items:
        $ref: './definitions/FabricControllerMap.yaml#/FabricControllerMap'
```

##### Command line used for generation

`lang = "io.swagger.codegen.languages.SwaggerYamlGenerator"`

##### Steps to reproduce

Try to create a map that makes reference to a type declared in a different file.

##### Suggest a Fix

Whatever type resolution for `$ref` that happens on `properties` in objects needs to also happen in `additionalProperties`.
