### ISSUE TITLE
Keep linebreaks in the contract in generated Java code

### ISSUE THREAD

**Issue by jfiala** [swagger-api/swagger-codegen#4714]
##### Description

Line-breaks in yaml contracts currently get lost in the javadoc comment (they are replaced by a blank). 
To keep line-breaks also in dynamically generated contracts, they should be replaced by \n.

##### Swagger-codegen version

2.2.2

##### Swagger declaration file content or url
Example (adapted 2.0\petstore.yaml)
```yaml
paths:
  /pet:
    post:
      tags:
        - pet
      summary: 'Add a new pet to the store
      test second line'
```

output:
```java
    @io.swagger.annotations.ApiOperation(value = "Add a new pet to the store test second line", notes = "", response = Void.class, authorizations = {
...
```

##### Suggest a Fix

1. Keep line breaks by generating \n instead of " " for line breaks
2. To also keep line breaks in dynamically generated contracts, an escaped line break needs to be added ("\n").
