### ISSUE TITLE
Same object not allowed within same api-request

### ISSUE THREAD

**Issue by ToreJohansson** [swagger-api/swagger-codegen#4783]
##### Description

If the same object are placed in several places within an API request there will only one occurrence produced by the ExampleGenerator.
There is an infinite loop in the Junit test for ExampleGenerator that is inhibited by allowing only one occurence of an object within an example. 

##### Swagger-codegen version

2.2.2-SNAPSHOT

##### Swagger declaration file content or url
    ```
QueryUserGroups:
  type: object
  title: QueryUserGroups
  properties:
    status:
      type: string
    data:
      type: object
      title: QueryUserGroups
      properties:
        userGroups:
          type: array
          items:
            type: string
      required:
      - userGroups
  required:
  - status
    ```

##### Command line used for generation

java -jar swagger-codegen/modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -l jaxrs-cxf -i api.yaml

##### Suggest a Fix

In DefaultGenerator.java:
     public Object resolveModelToExample(String name, String mediaType, Model model, Set<String> processedModels) {
//        if (processedModels.contains(name)) {
//            return "";
//        }

In ExampleGeneratorTest.java:
@@ -26,11 +27,17 @@ public class ExampleGeneratorTest {
         final String JSON = "application/json";
         final String XML = "application/xml";
         final String nodeType = "Node";
-        final RefProperty ref = new RefProperty(nodeType);
+
+        final String nodeTypeParent = "NodeParent";
+        final String nodeTypeChild = "NodeChild";
+
+        final RefProperty refParent = new RefProperty(nodeTypeParent);
+        final RefProperty refChild = new RefProperty(nodeTypeChild);
+
         final Model node = new ModelImpl().name(nodeType).property("name", new StringProperty())
-                .property("parent", ref)
-                .property("children", new ArrayProperty(ref))
-                .property("wrappedChildren", new ArrayProperty(ref).xml(new Xml().wrapped(true)));
+                .property("parent", refParent)
+                .property("children", new ArrayProperty(refChild))
+                .property("wrappedChildren", new ArrayProperty(refChild).xml(new Xml().wrapped(true)));
         final String pairType = "Pair";
         final ModelImpl pair = new ModelImpl().name(pairType);
         for (Map.Entry<String, String> item : ImmutableMap.of("first", "First", "second", "Second").entrySet()) {

In XmlExampleGenerator.java:
@@ -170,6 +169,9 @@ public class XmlExampleGenerator {
                 sb.append(closeTag(name));
             }
         }
+        if(sb.toString().equals("null")){
+            return "";
