### ISSUE TITLE
[JAVA] Generated getter method for boolean types doesn't follow naming convention

### ISSUE THREAD

**Issue by jospdeleon** [swagger-api/swagger-codegen#4882]
##### Description

Is there a way to generate the getter method for a boolean primitive type such that it is prefixed with the convention "is" instead of "get"? e.g. isSoldOut() instead of getSoldOut()

##### Swagger-codegen version

2.2.1

##### Swagger declaration file content or url

```yaml
    FareInformation:
      type: object
      properties:
        NotOffered:
          type: boolean
        SoldOut:
          type: boolean
        Refundable:
          type: boolean
```

##### Command line used for generation

```
    java
      -jar ./modules/swagger-codegen-cli/target/swagger-codegen-cli.jar  
      generate 
        -i path/to/api 
        -l java 
        -o path/to/out
      --language-specific-primitives boolean
      --type-mappings Boolean=boolean
```

##### Generated code

```java
    public boolean getSoldOut() {
      return soldOut;
    }
```

##### Desired code

```java
    public boolean isSoldOut() {
      return soldOut;
    }
```
