### ISSUE TITLE
[Java] doesnt generate correct classes for models with same nested properties

### ISSUE THREAD

**Issue by stevecookform3** [swagger-api/swagger-codegen#4883]
##### Description

If there are two models in the swagger definition whose subproperties are the same, the code generator always uses the first one.

e.g. take the following two definitions

```
  house:
    type: object
    properties:
      has_walls:
        type: boolean
      attributes:
        type: object
        properties:
          name:
            type: string
  
  person:
    type: object
    properties:
      has_legs:
        type: boolean
      attributes:
        type: object
        properties:
          name:
            type: string
```

Swagger doesnt generate a PersonAttributes class at all, and instead generates:

```
public class Person   {
  @JsonProperty("has_legs")
  private Boolean hasLegs = null;

  @JsonProperty("attributes")
  private HouseAttributes attributes = null;
```

##### Swagger-codegen version

Latest snapshot 2.2.2

##### Swagger declaration file content or url

```
swagger: '2.0'
info:
  version: 0.0.0
  title: Simple API
paths:
  /:
    get:
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/house"
        400:
          description: OK
          schema:
            $ref: "#/definitions/person"

definitions:
  
  house:
    type: object
    properties:
      has_walls:
        type: boolean
      attributes:
        type: object
        properties:
          name:
            type: string
  
  person:
    type: object
    properties:
      has_legs:
        type: boolean
      attributes:
        type: object
        properties:
          name:
            type: string

```
##### Command line used for generation

java -jar bin/swagger-codegen-cli.jar generate -v -i ./swagger.yaml -l spring -Dmodels -o .

##### Steps to reproduce

Copy the above swagger.yaml into http://editor.swagger.io/#!/ or use the latest CLI to build as above.

**Comment by stevecookform3** [comment]
On second thoughts this might be a parser error, since I've tried generating a few other types of servers and they all have the same issue (e.g. ASPNET, Flask).

**Comment by stevecookform3** [comment]
@wing328 any idea where the issue might lie?

**Comment by wing328** [comment]
@stevecookform3 I think that's because you're defining the model inline and swagger codegen will try to generate only 1 model if both inline models appear to be the same.

You can try to add the `title` attribute to have a better control on the naming of the inline object or try to define the model separately instead of inline.

**Comment by stevecookform3** [comment]
@wing328 where would the title attribute go? In the spec I can only see the title attribute used as the title of the app, not at individual model levels (title: "Swagger Sample App")..

**Comment by wing328** [comment]
Something like this:
```
      attributes:
        title: NewNameHere
        type: object
        properties:
          name:
            type: string
```
I would recommend defining the model separately instead of inline.
