### ISSUE TITLE
[Swift3] Additional Properties in Swagger specs generating non compiling code

### ISSUE THREAD

**Issue by dwoodel** [swagger-api/swagger-codegen#4907]
##### Description
[Swift3] Additional Properties in Swagger specs generating non compiling code.  When using additionalProperties in the swagger specification. 

We are using String additonal properties on a model to add generic string fields.  This works fine in java where the model use inheritance to extend a HashMap.  In swift the primitive dictionary [String : String] is used.  This code will not compile, this cannot be done like this.  An NSDictionary could be used like this.  Unfortunately this is not the only problem.

##### Swagger-codegen version

Milestone release: 2.2.2 

Building the latest 2.2 branch.  Commit in question: 
6963bf874877aa8a009079a89845c5a3a06ebea7

Pull Request that seems to have broken the generator.
https://github.com/swagger-api/swagger-codegen/pull/4052

Already merged into master.

##### Swagger declaration file content or url

Example Yaml which generates the problem: 

```yaml
UserResponse:
    type: object
    properties:
      email:
        type: string
        example: jdoe@mail.com
        description: "User's email address"
      firstName:
        type: string
        example: John
        description: First name
      surname:
        type: string
        example: Doe
        description: Surname
      secondName:
        type: string
        description: Second name
      secondSurname:
        type: string
        description: Second surname
      birthday:
        type: string
        example: '1982-05-26'
        description: "User's birthday"
      username:
        type: string
        example: jdoe
        description: Name of user
      phoneNumber:
        type: string
        example: '+375291112233'
        description: "User's phone number"
      status:
        type: string
        example: REGISTERED
        description: "User's status"
    description: Response user model
    additionalProperties:
      type: string
```
 
##### Command line used for generation

generate --input-spec XXXX --lang swift3 --output ./ --artifact-id biid-ios-sdk-public-api-client --group-id com.biid --invoker-package /com.biid.ios.sdk.core.publicapi.client.gen --api-package /com.biid.ios.sdk.core.publicapi.client.api --model-package /com.biid.ios.sdk.core.publicapi.client.model --artifact-version 0.7.48

##### Steps to reproduce

Make a swagger file which contains additonal properties.  Generate the swift3 code.  Try to compile!!  Collect prize! 

##### Related issues

No releated

##### Suggest a Fix
