### ISSUE TITLE
[scala] collectionFormat not supported for tsv, pipes, ssv, multi

### ISSUE THREAD

**Issue by jtnystrom** [swagger-api/swagger-codegen#4976]
##### Description

Generated code for collection parameters can only parse the csv format at the moment. Other formats, such as pipes, are not supported.

##### Swagger-codegen version

Latest github snapshot as of 2017-03-08

##### Swagger declaration file content or url

```yaml

  /pathologies:
    get:
      summary: "Information about pathological findings."
      parameters:
        - name: sampleIdFilter
          description: "Sample IDs to get pathologies for"
          in: query
          type: array
          collectionFormat: pipes
          required: false
          items:
            type: string

```

##### Related issues

https://github.com/swagger-api/swagger-codegen/pull/4426

##### Suggest a Fix

I will try to submit a PR soon.
