### ISSUE TITLE
[JAVA] Content-Type is overwritten

### ISSUE THREAD

**Issue by jdupouy** [swagger-api/swagger-codegen#4978]
The Content-Type is always overwritten even if it has been supplied.

If a header parameter is described as follow

```
parameters:
    content-type:
        name: Content-Type
        in: header
        description: Content type
        type: string
        required: true
```

The client should be able to specify the content type of the request but this gets overwritten by the Java API. See https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/Java/libraries/okhttp-gson/api.mustache#L95

Maybe we should check if a Content-Type has already been supplied before overwriting assuming that if a client is supplying a Content-Type he knows what he is doing.

**Comment by wing328** [comment]
@jdupouy you should define the `content-type` in `consumes` instead, e.g. https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.yaml#L37

**Comment by jdupouy** [comment]
Thank you for your prompt reply but I want my service to be able to consume any type of content-type and I do not want to provide a finite list of content-type.

**Comment by wing328** [comment]
To clarify a bit, if the developer sets "context-type" to `application/xml`, the API client will automatically represent the model in the form of XML?

**Comment by jdupouy** [comment]
I must have precised that I use the following definition for the body
```
parameters:
  body:
    name: body
    in: body
    description: Request body
    schema:
      type: string
      format: binary
```
