### ISSUE TITLE
[JAVA, jaxrs-spec] @DefaultValue missing in API for query parameters

### ISSUE THREAD

**Issue by foxx1337** [swagger-api/swagger-codegen#5023]
##### Swagger-codegen version

<= 2.2.3-SNAPSHOT (latest available here on master)

##### Swagger declaration file content or url

```yaml
paths:
  /health:
    post:
      operationId: postHealth
      tags:
        - Health
      parameters:
        - name: phoey
          in: query
          type: string
          default: foobar
```
##### Command line used for generation

`generate -l jaxrs-spec -i myapi.yaml -o jaxrs-spec-stub`

##### Steps to reproduce

It always happens because the template `swagger-codegen/modules/swagger-codegen/src/main/resources/JavaJaxRS/spec/queryParams.mustache` doesn't output `@DefaultValue("{{{defaultValue}}}")`

##### Related issues

Not really, this one is simpler than the other "defaultValue" issues reported here.

##### Suggest a Fix

Change `swagger-codegen/modules/swagger-codegen/src/main/resources/JavaJaxRS/spec/queryParams.mustache` from

```java
{{#isQueryParam}}@QueryParam("{{baseName}}"){{#useBeanValidation}}{{>beanValidationQueryParams}}{{/useBeanValidation}} {{{dataType}}} {{paramName}}{{/isQueryParam}}
```

to

```java
{{#isQueryParam}}@QueryParam("{{baseName}}"){{#useBeanValidation}}{{>beanValidationQueryParams}}{{/useBeanValidation}} {{#defaultValue}}@DefaultValue("{{{defaultValue}}}"){{/defaultValue}} {{{dataType}}} {{paramName}}{{/isQueryParam}}
```
