### ISSUE TITLE
[JAVA][jaxrs-spec] enumerated String values for QueryParams should render as enums instead of Strings

### ISSUE THREAD

**Issue by foxx1337** [swagger-api/swagger-codegen#5075]
##### Description

In Jersey it's possible to have an API like:
```Java
    enum SortingDirection {
    	ASC("asc"),
    	DESC("desc");

    	// ...
    }

    // ...

    @GET
    @Consumes({ "application/json" })
    @Produces({ "application/json" })
    public Response getSomething(@QueryParam("order") @DefaultValue("asc") SortingDirection direction) {
    	// ...
    }
```
and the runtime makes sure to convert the url `?order=asc` or `?order=desc` string to type `SortingDirection` provided some criteria are met - https://jsr311.java.net/nonav/javadoc/javax/ws/rs/QueryParam.html.
##### Swagger-codegen version

<=2.3.0-SNAPSHOT (current master)

##### Swagger declaration file content or url

```yaml
/something:
    get:
      operationId: getSomething
      parameters:
        - name: order
          description: How to sort the thing.
          in: query
          type: string
          enum: [asc, desc]
          default: asc
```
The current swagger-codegen implementation will simply generate
```Java
    @GET
    @Consumes({ "application/json" })
    @Produces({ "application/json" })
    public Response getSomething(@QueryParam("order") @DefaultValue("asc") String direction) {
    	// ...
    }
```
(please note that the `@DefaultValue("asc")` is part of pull request #5024, so it will be just missing without that one merged). In my opinion we should take advantage of the extra type safety provided by generating an enum, especially since the Java parser already has everything in memory for it.
##### Command line used for generation

`generate -l jaxrs-spec -i myapi.yaml -o jaxrs-spec-stub`

##### Steps to reproduce

It always happens, this is asking for an enhancement.

##### Suggest a Fix

I'll come by momentarily with a pull request for this.
