### ISSUE TITLE
[typescript-angular2] Support multiple apiKeys

### ISSUE THREAD

**Issue by dinvlad** [swagger-api/swagger-codegen#5093]
##### Description

Currently (as of 2.2.2), typescript-angular2 only supports a single `apiKey` parameter. This breaks compatibility with APIs that require 2 or more keys (through different headers).

Has it been (or planned to be) addressed in 2.3? I found #3983 and #4005, but they're talking about Fetch (I'm interested in 'regular' XHR, is that any different?).

Thanks

##### Swagger-codegen version

2.2.2

##### Swagger declaration file content or url
```
securityDefinitions:
  auth_token:
    type: apiKey
    in: header
    name: Authorization
  api_key:
    type: apiKey
    in: header
    name: x-api-key
```
##### Related issues

#3983, #4005
