### ISSUE TITLE
[csharp-client] authentication does not implemented

### ISSUE THREAD

**Issue by iamkarlson** [swagger-api/swagger-codegen#5121]
##### Description

I have security description in my swagger, but I haven't found any security implementations in the client. 

##### Swagger-codegen version

last commit from github

##### Swagger declaration file content or url

<!-- if it is a bug, a json or yaml that produces it.
If you post the code inline, please wrap it with
```yaml
 securityDefinitions: 
     apiKey: 
         type: 'apiKey' 
         description: 'API Key Authentication' 
         name: 'apiKey' 
         in: 'header' 
     oauth2: 
         type: 'oauth2' 
         description: 'OAuth2 Implicit Grant' 
         flow: 'implicit' 
         authorizationUrl: 'http://petstore.swagger.wordnik.com/api/oauth/dialog' 
         tokenUrl: 'https://tempuri.org/token' 
         scopes: 
```
##### Command line used for generation

```powershell
java.exe -jar $Global:swaggerJar `
    generate `
    -i $Global:swaggerJsonUrl `
    -l csharp `
    -o $Global:outputFolder `
    -c $Global:config `
    -t $Global:templates `
    --additional-properties $json.'additional-properties'`
```
where $global set to my variables 

##### Suggest a Fix
I suppose it should be similar template as for [java ApiKeyAuth](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/Java/auth/ApiKeyAuth.mustache) but not sure
