### ISSUE TITLE
[JAVA SPRING] Error type generated for enum integer type.

### ISSUE THREAD

**Issue by paranoid945** [swagger-api/swagger-codegen#5177]
##### Description

integer type should generate integer output instead of string.

##### Swagger-codegen version

2.2.2

##### Swagger declaration file content or url
```yaml
definitions:
  BaseModel:
    discriminator: baseModelType
    properties:
      code:
        type: integer
        format: int32
        default: 0
        enum: [0, 1]
        description:  0 normal, 1 error.
    required:
      - code
      - baseModelType
```

##### Command line used for generation
-l spring --library spring-mvc

##### Generated Java Model

```java

public class BaseModel   {
  /**
   * 0 normal, 1 error.
   */
  public enum CodeEnum {
    NUMBER_0(0),
    
    NUMBER_1(1);

    private Integer value;

    CodeEnum(Integer value) {
      this.value = value;
    }

    @Override
    @JsonValue
    public String toString() {
      return String.valueOf(value);
    }
```

which output string json value instead of integer:

```json
{
  "code": "0"
}
```
