### ISSUE TITLE
[JAVA][SPRING] Swagger codegen generates wrong java object for json objects with additional properties 

### ISSUE THREAD

**Issue by pumpadump** [swagger-api/swagger-codegen#5187]
##### Description
Swagger Codegen generates a java model object that extends HashMap for json objects that have the ` additionalProperties:` property set. This leads to jackson only serealizing the properties added to the hashmap and ignoring all additional properties that are set explicitly in the java file. 
##### Swagger-codegen version
2.2.2
##### Swagger declaration file content or url
```yaml
 Datavalue:
    type: object
    description: The individual dataelements 
    required:
      - id
    properties:
      id:
        type: string
      source:
        type: string
      target:
        type: string
    additionalProperties:
      type: string
```
This generates a model object that starts like this:
```java
public class Datavalue extends HashMap<String, String>  {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("source")
  private String source = null;

  @JsonProperty("target")
  private String target = null;

  public Datavalue id(String id) {
    this.id = id;
    return this;
  }
```

Serializing this objects leads to a json that is missing the explicitly set properties (id, source, target).
http://stackoverflow.com/questions/31320983/jackson-serialise-map-with-extra-fields

I think instead it should generate a java object that has a hashmap as a variable and the following annotated getter and setter methods, similar to this:
```java
public class Datavalue   {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("source")
  private String source = null;

  @JsonProperty("target")
  private String target = null;

  protected Map<String,String> otherProperties = new HashMap<String,String>();

  public Datavalue id(String id) {
    this.id = id;
    return this;
  }
  @JsonAnyGetter
  public Map<String, String> any() {
   return this.otherProperties;
  }

  @JsonAnySetter
  public void set(String name, String value) {
   this.otherProperties.put(name, value);
  }
```
as Explained here: http://www.cowtowncoder.com/blog/archives/2011/07/entry_458.html

**Comment by cbornet** [comment]
Yes, seems better. Would you do the PR ? Maybe against 2.3.0 branch since that it's a breaking change.
Also `additionalProperties` would be better than `otherProperties` for the field name

**Comment by cbornet** [comment]
And ideally that would be done for all Java based codegens.

**Comment by pumpadump** [comment]
Ok i will try to figure out where to add such changes and create a PR. Can you point me to a good starting point?

**Comment by ePaul** [comment]
@pumpadump 
I think one starting point would be src/main/resources/Java/pojo.mustache.

There we see 

> ```public class {{classname}} {{#parent}}extends {{{parent}}} {{/parent}}{{#parcelableModel}}implements Parcelable {{#serializableModel}}, Serializable {{/serializableModel}}{{/parcelableModel}}{{^parcelableModel}}{{#serializableModel}}implements Serializable {{/serializableModel}}{{/parcelableModel}}{```

... the extends logic thus comes from the existence of a parent item in the CodegenModel object.

Somewhere in DefaultCodegen or AbstractJavaCodegen this likely is done.

**Comment by Kdoki** [comment]
Hello, 

Is there any news about this issue ? or a workaround ? 

Regards,

**Comment by cbornet** [comment]
There are several things to consider here:
- what should we do if there is only `additionalProperties` and no `properties` ? Keep the HashMap inheritance or add the JsonAnyGetter/JsonAnySetter ?
- this will not work with gson. Not a problem for Spring codegen but it could be one for the java client ones.

Note : to change the behavior, override the [addAdditionPropertiesToCodeGenModel](https://github.com/swagger-api/swagger-codegen/blob/794bb07cf7382f3f31286b775e2bf76267ce75e2/modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java#L1486) method and fill the [additionalPropertiesType](https://github.com/swagger-api/swagger-codegen/blob/40f1de8a5889fc43022536be934cb720c1421121/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/TypeScriptJqueryClientCodegen.java#L146) property

**Comment by cbornet** [comment]
@wing328 WDYT ?

**Comment by wing328** [comment]
```
 Datavalue:
    type: object
    description: The individual dataelements 
    required:
      - id
    properties:
      id:
        type: string
      source:
        type: string
      target:
        type: string
    additionalProperties:
      type: string
```

@pumpadump what does the JSON payload looks like? I want to ensure it's defined correctly.
