### ISSUE TITLE
[All?] examples for string definitions are over-quoted

### ISSUE THREAD

**Issue by reece** [swagger-api/swagger-codegen#5460]
##### Description

In a `definition` section, examples for string objects are over-quoted. For example, this stanza from an input yaml

```yaml
# input yaml
definitions:
  Id:
    type: string
    example: example from def
```

is rewritten by swagger-codegen as

```yaml
# resulting yaml from swagger-codegen
  Id:
    type: "string"
    example: "\"example from def\""
```

Explicitly quoting the input `example` text has no effect.

The above example is for python-flask and nodejs-server. I suspect other servers generate the same yaml.

This bug does *not* occur for examples within `object` definitions. For example, the following stanza works as expected:

```yaml
  Allele:
    type: "object"
    properties:
      id:
        $ref: "#/definitions/Id"
      location_id:
        $ref: "#/definitions/Id"
      replacement:
        $ref: "#/definitions/Sequence"
    example:
      id: "Allele example"
      location_id: "Allele example"
      replacement: "Allele example"
```

##### Swagger-codegen version

2.2.2

##### Swagger declaration file content or url

https://github.com/reece/vmc-openapi/blob/master/spec/vmc.yaml

##### Command line used for generation

`swagger-codegen generate -l python-flask -i ../spec/vmc.yaml -o python-flask`

##### Steps to reproduce

* Install swagger-codegen 2.2.2 (other versions untested)
* Run command line as above.

##### Related issues

The following issues are vaguely related.

* #5458 
* #1641
* #4611

**Comment by wing328** [comment]
@reece thanks for reporting the issue. When I clicked on https://github.com/reece/vmc-openapi/blob/master/spec/vmc.yaml, I got a 404.

If you've time, I would suggest you to try the latest master as well to see if there's by any chance the issue may have been addressed already.

**Comment by reece** [comment]
@wing328: Yes, this affects latest master (42a5a13fe) as well.

I worked up an minimal example at https://gist.github.com/reece/7d343afd3638fc530c3d3607b57ababd. 

```yaml
definitions:
  Def1:
    type: "string"
    example: word
  Def2:
    type: "string"
    example: two words
  Def3:
    type: "string"
    example: "quotedword"
  Def4:
    type: "string"
    example: "two quoted words"
  Def5:
    type: "object"
    properties:
      namespace:
        type: "string"
        example: "NCBI"
      accession:
        type: "string"
        example: "ENST000001234.5"
```

With the command line `swagger-codegen generate -l python-flask -o 5460 -i 5460.yaml` (2.2.2 and master), I see this:

```
$ grep example 5460/swagger_server/swagger/swagger.yaml 
    example: "\"word\""
    example: "\"two words\""
    example: "\"quotedword\""
    example: "\"two quoted words\""
        example: "NCBI"
        example: "ENST000001234.5"
```

**Comment by JFCote** [comment]
@wing328 and @reece : I've noticed this problem too when generating json format in the JavaPlayFramework codegen. I don't know where this "json" is generated so I could not fix it myself.

I use this code in the generator:

```
@Override
    public Map<String, Object> postProcessSupportingFileData(Map<String, Object> objs) {
        Swagger swagger = (Swagger)objs.get("swagger");
        System.out.println("swagger" + swagger.toString());
        if(swagger != null) {
            try {
                objs.put("swagger-json", Json.pretty().writeValueAsString(swagger));
            } catch (JsonProcessingException e) {
                LOGGER.error(e.getMessage(), e);
            }
        }
        return super.postProcessSupportingFileData(objs);
    }
```

And use it like this in the .mustache file:

`{{{swagger-json}}}`


yaml like this
```yaml
ReturnStatus:
  type: string
  enum:
    - NotReturned
    - Recycled
    - Trashed
    - InTransit
    - InvestigationPending
    - Lost
  description: "Device's return status"
  example: InTransit
```

return json like this
```json
"ReturnStatus" : {
      "type" : "string",
      "description" : "Device's return status",
      "example" : "\"InTransit\"",
      "enum" : [ "NotReturned", "Recycled", "Trashed", "InTransit", "InvestigationPending", "Lost" ]
    },
```
