### ISSUE TITLE
why x-spring-paginated  vender extentions doesn't work for me?

### ISSUE THREAD

**Issue by zzsoszz** [swagger-api/swagger-codegen#5506]
##### Description
https://github.com/swagger-api/swagger-codegen/issues/3353
https://github.com/swagger-api/swagger-codegen/pull/3357

json code
```json
  "/pet/findByStatus": {
      "get": {
        "tags": [
          "pet"
        ],
        "summary": "Finds Pets by status",
        "description": "Multiple status values can be provided with comma seperated strings",
        "operationId": "findPetsByStatus",
		"x-spring-paginated": true,
        "produces": [
          "application/json",
          "application/xml"
        ],
        "parameters": [
          {
            "name": "status",
            "in": "query",
            "description": "Status values that need to be considered for filter",
            "required": false,
            "type": "array",
            "items": {
              "type": "string",
              "enum": ["available", "pending", "sold"]
            },
            "collectionFormat": "multi",
            "default": "available"
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Pet"
              }
            },
            "examples": {
              "application/json": {
                "name": "Puma",
                "type": "Dog",
                "color": "Black",
                "gender": "Female",
                "breed": "Mixed"
              }
            }
          },
          "400": {
            "description": "Invalid status value"
          }
        },
        "security": [
          {
            "petstore_auth": [
              "write:pets",
              "read:pets"
            ]
          }
        ]
      }
    }
```

generated java source
```java
    public ResponseEntity<List<Pet>> findPetsByStatus( @ApiParam(value = "Status values that need to be considered for filter", allowableValues = "AVAILABLE, PENDING, SOLD", defaultValue = "available") @RequestParam(value = "status", required = false, defaultValue="available") List<String> status) {
        // do some magic!
        return new ResponseEntity<List<Pet>>(HttpStatus.OK);
    }
```

**Comment by wing328** [comment]
@zzsoszz looks like it's removed somehow 😞 

@cbornet @diyfr would you please take a look when you've time?

**Comment by mkatircioglu** [comment]
Is there any update on this? @wing328

**Comment by cbornet** [comment]
It seems @diyfr ‘s PR was never merged

**Comment by mkatircioglu** [comment]
What should we do now? @cbornet Can we merge @diyfr 's PR on the behalf of him?

**Comment by mikhail-putilov** [comment]
Hey guys, is there any update? This issue is a big deal for me since my team and I use spring-mvc rather extensively and this is the only issue that stops me from trying codegen in production.

**Comment by T9FC8FY** [comment]
Hi, is there a update? In our project we want to generate our APIs, but the Pageable and Page objects are the reason why we still dont do this.

**Comment by diyfr** [comment]
this feature has not been finalized because it's very specific to SpringFramework. If you think it's necessary, I'll see if I can find some time to implement it. If not, in my projects I treat it this way
Add query parameters for each resources :
```yml
      parameters:
        - $ref: '#/parameters/ppage'
        - $ref: '#/parameters/psize'
        - $ref: '#/parameters/psort'
```
Don't miss to add a partial response
```yml
        '206':
          description: 'Résultat complet'
          schema:
            type: 'array'
            items:
              $ref: '#/definitions/Pet
```
or   (see best practise)
```yml
        '206':
          description: 'Résultat partiel'
          schema:
            $ref: '#/definitions/Pets'
```
Define parameters for all project 
```yml
parameters:
  ppage:
    name: 'page'
    in: 'query'
    description: 'Results page you want to retrieve (0..N)'
    type: 'integer'
  psize:
    name: 'size'
    in: 'query'
    description: 'Number of records per page.'
    type: 'integer'
  psort:
    name: 'sort'
    in: 'query'
    description: 'Sorting criteria property(,asc|desc) Default sort order is ascending. Multiple sort criteria are supported.'
    uniqueItems: true
    collectionFormat: 'pipes'
    type: 'array'
    items:
      type: 'string'
```

Best practise encapsulate your paginated response : 
```yml
  Pets:
    type: 'object'
    properties:
      page:
        type: 'integer'
        format: 'int32'
      size:
        type: 'integer'
        format: 'int32'
      sort:
        type: 'string'
      total:
        type: 'integer'
        format: 'int64'
      count:
        type: 'integer'
        format: 'int32'
      results:
        type: 'array'
        items:
          $ref: '#/definitions/Pet'
```
it's more standard, and applicable for all generators
