### ISSUE TITLE
[Swift3] string/binary and string/byte are both being Base64 encoded

### ISSUE THREAD

**Issue by TeMob** [swagger-api/swagger-codegen#5507]
##### Description
In the generated Swift code body-parameters of type "string/byte" und "string/binary" are both generating code where the parameter is of type 'Data'. This itself is correct, but Data is always being encoded to Base64, even when I choose 'binary' as a format instead of 'byte'.

##### Swagger-codegen version

2.2.2

##### Swagger declaration file content or url

<!-- if it is a bug, a json or yaml that produces it.
If you post the code inline, please wrap it with
```yaml
get:
      parameters:
        - in: body
          name: imageBinary
          required: true
          type: string
          format: binary
```
