### ISSUE TITLE
[Maven] How to split swagger spec file?

### ISSUE THREAD

**Issue by cthiebault** [swagger-api/swagger-codegen#5529]
Using `swagger-codegen-maven-plugin:2.2.2`, I can't find a way to split my swagger spec file (swagger.yaml & pet.yaml).

pom.xml
```
<plugin>
  <groupId>io.swagger</groupId>
  <artifactId>swagger-codegen-maven-plugin</artifactId>
  <version>2.2.2</version>
  <executions>
    <execution>
      <goals>
        <goal>generate</goal>
      </goals>
      <configuration>
        <inputSpec>swagger.yaml</inputSpec>
        <language>spring</language>
          <configOptions>
            <interfaceOnly>true</interfaceOnly>
            <dateLibrary>java8</dateLibrary>
         </configOptions>
      </configuration>
    </execution>
  </executions>
</plugin>
```

swagger.yaml

```
paths:
  /pet:
    post:
        parameters:
      - in: "body"
        description: "Pet object that needs to be added to the store"
          schema:
          $ref: "pet.yaml#/Pet"
```

pet.yaml

```
Pet:
  type: "object"
  properties:
    id:
      type: "integer"
      format: "int64"
    name:
      type: "string"
      example: "doggie"

```

Log 

```
[ERROR] swagger-test/target/generated-sources/swagger/src/main/java/io/swagger/api/PetApi.java:[3,24] cannot find symbol
  symbol:   class PetYamlPet
  location: package io.swagger.model
```
Here is the Gist to reproduce this:
https://gist.github.com/cthiebault/c3007781b9ba17600411c86ea25c2d4a

Is this feature supported by Java/Maven plugin?
