### ISSUE TITLE
Access vendor extensions from Mustache template

### ISSUE THREAD

**Issue by vagy13** [swagger-api/swagger-codegen#5532]
##### Description
Say we define a vendor extension 'x-myExt' as part of a Swagger Definition like: 

```
...
definitions:
  MyDef:
    type: object
    properties:
      ...
    x-myExt:
      varA: 'A'
      varB: 'B'
...
```

How do we then access this extension in a Mustache template?
I've tried the following:
```
{{vendorExtensions.x-myExt.varA}} 

{{#vendorExtensions.x-myExt}}{{varA}}{{/vendorExtensions.x-myExt}}

{{#vendorExtensions}}{{#x-myExt}}{{varA}}{{/x-myExt}}{{/vendorExtensions}}
```
but none works as expected. 

If in the Mustache template I write:
```
{{{vendorExtensions}}}
```
in the generated file I get:
```
{x-myExt={"varA":"A" ,"varB":"B"}}
```
Shouldn't this be:
```
{"x-myExt":{"varA":"A" ,"varB":"B"}}
```
?
##### Swagger-codegen version

2.2.2

**Comment by vagy13** [comment]
Anyone please?

**Comment by tomblench** [comment]
FWIW, I've got the same issue. We'd like to store a complex structure under a vendor extension and I assumed this would just work. Our structure is slightly different (an array of key/value pairs):
```yaml
  x-scenarios:
    - description: 'GET /database and return 200'
      type: 'path'
      path: 'db'
      value: 'database'
    - description: 'GET /non_existent_database and return 404'
      type: 'path'
      path: 'db'
      value: 'non_existent_database'
```
The idea behind this structure is to automatically generate test code with multiple scenarios per endpoint. Each scenario has values used to generate the request path, query parameters, body, or some combination to provoke a certain behaviour.

The [spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md) says
```
The value can be null, a primitive, an array or an object
```
each time vendor extensions are mentioned.
