### ISSUE TITLE
[Swift3]Classes with no properties but with additionalProperties are not correctly created

### ISSUE THREAD

**Issue by wuf810** [swagger-api/swagger-codegen#5535]
##### Description

If a class has no properties defined but does have additionalProperties defined, it is incorrectly created as an empty "typealias" and not a concrete class

##### Swagger-codegen version

Latest Master 4512619acfca303c6ebce02ae8177ccd61cb2275

2.2.2

##### Swagger declaration file content or url

YAML which generates the issue :
```
UserRequest:
    type: object
    description: Request user model
    additionalProperties:
      type: string
```
##### Command line used for generation

generate --input-spec https://example/swagger.json --lang swift3 --output /Users/michaelkaye/swagger/gen/swift 

##### Steps to reproduce

Create a YAML with a class defined as above with no static properties but with additionalProperties.

##### Related issues

Related to the issue reported here:

https://github.com/swagger-api/swagger-codegen/issues/4907

##### Suggest a Fix

I have already created a fix and will raise a PR in a moment.
