### ISSUE TITLE
[Java][Spring] Add support for custom validation messages in Beanvalidation annotations

### ISSUE THREAD

**Issue by TomSoflow321** [swagger-api/swagger-codegen#5643]
The PR #4600 added support for beanvalidation annotations, which work fine, but generated annotations also support a `message` property to specify a custom error message if the validation for that annotation fails.
This can look like this:

    @ApiModelProperty(example = "VGVzdA==", value = "")
    @Pattern(regexp="^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=|[A-Za-z0-9+/]{4})$", message = "The provided String is not Base64 encoded")
    public String getFoo() {
        return foo;
    }

Are there plans to add support for such a message? It might be possible to add it to the declaration file like:

    foo:
        type: string
        pattern: "^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=|[A-Za-z0-9+/]{4})$"
            message: "The provided String is not Base64 encoded"
        example: "VGVzdA=="

I guess this feature must be added in the `beanValidationCore.mustache` template (in `swagger-codegen/src/main/java/resources/`), but I'm not proficient enough with that template language to do that myself.

(I've tested the release version of 2.2.0 and the current master version, but both don't support these message properties)

**Comment by cartick** [comment]
+1

**Comment by shexbeer** [comment]
+2

**Comment by gmgk93** [comment]
+1

**Comment by unphon** [comment]
+1 very important, our clients are getting a ton of regex instead of a readable error message

**Comment by HugoMario** [comment]
Hello @TomSoflow321 @cartick @shexbeer @gmgk93 @unphon 

i can implement this using vendor extensions. 
```
foo:
    type: string
    pattern: "^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2} ..."
    x-message: "The provided String is not Base64 encoded"
    example: "VGVzdA=="
```

I would update templates to read the `x-message` field. Please let me know what you think about that.

**Comment by JeffGoderie** [comment]
@HugoMario,

While I do think that the use of vendor extensions might work for this, your suggestion might be problematic when multiple constraints are required (e.g. minLength + maxLength). It might also be hard to relate this to 'required' constraints, since these are separated from the field declaration.

One option that I see is to still use vendor extensions, but have one per constraint:
```
properties
foo:
    type: string
    pattern: "^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2} ..."
    x-pattern-message: "The provided String is not Base64 encoded"
    x-required-message: "The provided String cannot be null"
    example: "VGVzdA=="
required:
    - foo
```

What are your thoughts on this?
