### ISSUE TITLE
[JAVA] Problem generating template using the `required` array of object properties

### ISSUE THREAD

**Issue by aaronschwartz** [swagger-api/swagger-codegen#5737]
First of all thank you very much for the library. 
##### Description

My end goal: To validate objects returned by my API. If they are marked as required in the `required` array property of an object, I want to fail validation if it does not exist in the response returned by the API call. Since the serializer is very lenient on json parsing, I'm trying to find another way to tell if an object in the response is missing altogether.

What I'm trying: I've modified `pojo.mustache` to use the `{{#required}}...{{/required}}` property to set an annotation on the property setter methods.

My problem: `{{required}}` is evaluating to `false` for properties that are `object` types even when the object is in the required list (see `complex` in definition file below). For array types and simple types it appears `{{required}}` correctly evaluates depending on the required list. 

##### Swagger-codegen version

2.2.2

##### Swagger declaration file content or url

```yaml
schema:
    type: object
    properties:
      data:
        type: object
        required:
          - complex
          - simple
        properties:
          complex:
            type: object
              properties:
                ...
          simple:
            type: string
```

##### Command line used for generation

Using the swagger-codegen-maven-plugin with default `JAVA` language options.

##### Steps to reproduce
* Modify `pojo.mustache` to use the `{{required}}` variable
* Generate JAVA client code
* Note that properties that are `object` types are not being marked as required even if they are in the required list (e.g `complex` in the definition). Note that simple types do correctly appear required (e.g `simple` in the definition).

##### Suggest a Fix

It would be nice if I can know which properties are required or not when generating client code (including objects).
