### ISSUE TITLE
Java CL has compiler error if model has (\n) in its definition text.

### ISSUE THREAD

**Issue by suguptaxbox** [swagger-api/swagger-codegen#577]
If the description of the model has new line characters in the text, the generated client library has invalid code and hence cause compile time error.

Repro:
1. Open the Swagger Editor http://editor.swagger.io/#/
2. In the editor (assuming you have yaml editor) add the following definition to the end of the file.
```yaml
  TestingNewLineCompilerError:
    description: "First line\nSecond line."
    required:
      - message
    properties:
      message:
        type: string
```
3. Now generated the java client library.
    click on Generate Client->Java
4. Download the generated source code and open the model file for TestingNewLineCompilerError
    Open file: src/main/java/io/swagger/client/model/TestingNewLineCompilerError.java
5. Verify the code in the file and observe that it is incorrect where description of ApiModel attribute has java string on two different lines. Therefore if you compile the code it will cause compile time error because there is no '+' plus sign in between two lines.

/**
 * First line
Second line.
 **/
@ApiModel(description = "First line
Second line.")
public class TestingNewLineCompilerError  {

Actual behavior:
When compiling the generated code there is compile time error.

Expected:
When compiling the generated code there should not be any error.
