### ISSUE TITLE
[QT5][CPP] does handle `additionalProperties`

### ISSUE THREAD

**Issue by manuc66** [swagger-api/swagger-codegen#5876]
##### Description

The `qt5cpp` generation does handle `additionalProperties`, see: https://gist.github.com/manuc66/730be9e25488450ebf99ba69196790db

##### Swagger-codegen version

master (next 2.2.3) on 06/18/2017

##### Swagger declaration file content or url

```yaml
  Error:
    type: object
    required:
      - _type
      - key
      - message
    additionalProperties:
      type: object
    properties:
      _type:
        type: string
        default: Error
        readOnly: true
      key:
        type: string
      message:
        type: string
```

##### Command line used for generation

```bash
docker run -it -v %curpath%:/swagger-api/ swaggerapi/swagger-codegen-cli:latest generate  -i /swagger-api/swagger.yaml  -l qt5cpp -o /swagger-api/
```
