### ISSUE TITLE
[NANCYFX] Enum models are generated as empty classes with compilation errors

### ISSUE THREAD

**Issue by rubms** [swagger-api/swagger-codegen#5910]
##### Description

Type definitions declared as enum are generated as general c# classes, without the enumeration values, and with compilation errors.

##### Swagger-codegen version

The error is reproduced in Swagger-codegen v2.2.2

##### Swagger declaration file content or url

The bug can be reproduced with a swagger specification containing a definition like this one:
```yaml
  AccountStatusEnum:
    type: string
    enum:
      - New
      - Confirmed
      - Active
      - Blocked
```
The generation of the corresponding model will result in a general C# class, without the enumeration values and compilation errors.

##### Command line used for generation

generate -i swagger.json -l nancyfx -o .\gentemp\

##### Suggest a Fix

I suggest to update the model.mustache template in nancyfx in order to difference between general classes and enumerations, in a similar way it is done in the C# client generation. I provide a pull request for the fix.
