### ISSUE TITLE
[JAVA] Enum character escaping bug

### ISSUE THREAD

**Issue by wingsofovnia** [swagger-api/swagger-codegen#5914]
##### Description

Java Enum Codegen escapes both + (plus) and - (minus) with "_". In some cases, it can cause duplicated Enum names that are prohibited by JLS.

##### Swagger-codegen version

Online Editor

##### Swagger declaration file content or url

```yaml
  definitions: 
    BuggedCodeGen: 
      type: "object"
      properties: 
        timeZone:
          type: "string"
          enum:
          - "Etc/GMT+1"
          - "Etc/GMT-1"
```

Results in:
```java
public enum TestEnum {
    GMT_1("Etc/GMT+1"),
    GMT_1("Etc/GMT-1");
    // ...
}
```

##### Suggest a Fix
Replace + with PLUS and - with MINUS
