### ISSUE TITLE
Headers do not appear in static html documentation

### ISSUE THREAD

**Issue by arketec** [swagger-api/swagger-codegen#5930]
##### Description
StaticHtmlGenerator does not include custom header definitions. I have an endpoint that may pass a token in a custom header 'x-access-token' or as a query parameter 'token'

In the swagger.yaml file:

```yaml(
parameters: 
        - name: x-access-token
          in: header
          type: string
          required: false
        - name: token
          in: query
          type: string
          required: false

```

This works in the swagger editor, as well as through an HTTP client (like SOAP UI)

However, when I generate the static HTML docs, the header section is blank.

##### Swagger-codegen version

swagger-codegen-cli 2.2.2
##### Command line used for generation
java -jar ./swagger-codegen-cli.jar generate -l html -i ./api/swagger/swagger.yaml

##### Steps to reproduce
Run the above command
