### ISSUE TITLE
[Spring] Special characters in query parameter names

### ISSUE THREAD

**Issue by ok11** [swagger-api/swagger-codegen#6132]
##### Description

If modeling query parameters, containing $ as a part of the name (an example is $top to express pagination semantics), the server stub, generated by the Spring generator, contains the query parameter names (`@RequestParam`) without that character (`@RequestParam(value= "top")`). For characters, complaint to RFC 3986 (URI syntax), the value must be retained in the query parameter. It requires a separation of logic between generation or query parameter names and names of variables that hold the value, because the character can be valid from URI point of view, but invalid from the perspective of target programming language syntax, and vice versa.  

##### Swagger-codegen version

2.2.2

##### Swagger declaration file content or url

```yaml
paths:

  /products:
    get:
      summary: Returns a list of existing Products
      description: |
        Returns a list of Products. The list is pageable.
      tags:
        - Product
      parameters:
        - name: $top
          in:  query
          type: integer
          format: int32
          default: 32
          required: false
          description: number of Products to return in the page
```

##### Command line used for generation

Maven plugin
```xml
<configuration>
  <language>spring</language>
  <configOptions>
    <sourceFolder>...</sourceFolder>
    <dateLibrary>java8</dateLibrary>
    <interfaceOnly>true</interfaceOnly>
    <basePackage>com.samples.shoppinglist</basePackage>
    <configPackage>com.samples.shoppinglist.config</configPackage>
   </configOptions>
   <output>...</output>
</configuration>
```

##### Steps to reproduce

Just generate an API interface or a REST controller with the given input

##### Suggest a fix/enhancement

As said above, current logic apparently mixes the concerns for generation of query parameter names and variable names, which potentially have different validation rules.
