### ISSUE TITLE
[BASH] Bug generating access_token when 'in: query'

### ISSUE THREAD

**Issue by tavoda** [swagger-api/swagger-codegen#6141]
##### Description
When security definition looks like (_in: query_)
```
securityDefinitions:
  accessToken:
    type: apiKey
    description: The access_token returned by a call to ``/login`` or ``/register``
    name: access_token
    in: query
```
Generated script doesn't include access_token into query parameters.

##### Swagger-codegen version
version: 2.2.2

##### Command line used for generation
`java -jar swagger-codegen-cli.jar generate -l bash -o bash/ -c config-bash.json -i matrix-new-swagger.json
`
#### config-bash.json
```
{
  "processMarkdown": true,
  "curlOptions": "-sS --tlsv1.2",
  "scriptName": "matrix-cli",
  "generateBashCompletion": true,
  "generateZshCompletion": true,
  "hostEnvironmentVariable": "MATRIX_HOST",
  "basicAuthEnvironmentVariable": "MATRIX_BASIC_AUTH",
  "apiKeyAuthEnvironmentVariable": "MATRIX_API_KEY"
}
```

##### Suggest a fix/enhancement
From what I see in template file _client.mustache_ access_token is supported only when *isKeyInHeader* there is no code for case *isKeyInQuery* except help.
