### ISSUE TITLE
[Swift3] Array of string appears broken

### ISSUE THREAD

**Issue by julienfouilhe** [swagger-api/swagger-codegen#6238]
##### Description

Hi guys,
Arrays of strings appear broken in the swift 3 client. Using the swagger declaration below, it generates the following file:

```swift
public typealias UserInstruments = []
```
When it should be
```swift
public typealias UserInstruments = [String]
```

And in the Decoders:

```swift
        // Decoder for UserInstruments
        Decoders.addDecoder(clazz: UserInstruments.self) { (source: AnyObject, instance: AnyObject?) -> UserInstruments in
            let sourceArray = source as! [AnyObject]
            return sourceArray.map({ Decoders.decode(clazz: .self, source: $0, instance: nil) })
        }
```

When it should be:

```swift
        // Decoder for UserInstruments
        Decoders.addDecoder(clazz: UserInstruments.self) { (source: AnyObject, instance: AnyObject?) -> UserInstruments in
            let sourceArray = source as! [AnyObject]
            return sourceArray.map({ Decoders.decode(clazz: String.self, source: $0, instance: nil) })
        }
```

Still trying to spot the problem, but if someone that actually coded the client could have a look I would greatly appreciate it!

Thanks!

##### Swagger-codegen version

2.2.3

##### Swagger declaration file content or url

```yaml
  UserInstruments:
    type: array
    description: |
      An array of the instrument identifiers that the user plays.
    items:
      type: string
      pattern: ^[a-z]+\.[a-z]+$
    example:
    - keyboards.grand-piano
    - brass.trumpet
    - strings.violin
```

##### Command line used for generation

swagger-codegen generate -i https://url.com -l swift3 -o ../api-client-swift3 -c conf.json
