### ISSUE TITLE
[JAVA] - Consider regex for path params (subresource operation)

### ISSUE THREAD

**Issue by oliveirasevandro** [swagger-api/swagger-codegen#6263]
##### Description

I'm trying to generate resource endpoints which contain some sort of regex to validate the path params. Fox example: @Path(/resource/{res:[a-zA-z]})

Couldn't find a way to produce that kind of souce code. Does anyone know if this feature is already implemented?

##### Swagger-codegen version

2.2.2

**Comment by wing328** [comment]
@oliveirasevandro in your spec, do you use `pattern` for the path parameters?

**Comment by oliveirasevandro** [comment]
@wing328 Yes, I do. My parameter specification is something like this:

```
parameters:  
  param:
    name: <parameter_name>
    in: path
    required: true
    type: string
    description: <some_description>
    pattern: ^(A|B|C)$
```
