### ISSUE TITLE
JavaSpring useOptional Not Working

### ISSUE THREAD

**Issue by SingleShot** [swagger-api/swagger-codegen#6320]
I generate code via the `swagger-codegen-maven-plugin`. I've tried `2.2.3` and `2.3.0-SNAPSHOT`.

Example spec:
```
...
  Product:
    type: "object"
    required:
      - "name"
    properties:
      name:
        type: "string"
      description:
        type: "string"
...
```

Example config in Maven:
```
<plugin>
  <groupId>io.swagger</groupId>
  <artifactId>swagger-codegen-maven-plugin</artifactId>
  <version>2.2.3</version>
  <!--<version>2.3.0-SNAPSHOT</version>-->
  <executions>
    <execution>
      <phase>generate-sources</phase>
      <goals>
        <goal>generate</goal>
      </goals>
      <configuration>
        <configOptions>
          <hideGenerationTimestamp>true</hideGenerationTimestamp>
          <interfaceOnly>true</interfaceOnly>
          <java8>true</java8>
          <useOptional>true</useOptional>
        </configOptions>
        <generateSupportingFiles>false</generateSupportingFiles>
        <inputSpec>src/main/resources/swagger/api.yml</inputSpec>
        <language>spring</language>
      </configuration>
    </execution>
  </executions>
</plugin>
```

I expect the description of the resulting model object to be `Optional`.
