### ISSUE TITLE
[Java-Vertx] Server : EnumModel generation is broken 

### ISSUE THREAD

**Issue by phiz71** [swagger-api/swagger-codegen#6427]
Hello,

it seems that there is a little problem in enumModel generation in swagger-codegen 2.2.3

**Steps to reproduce:**

1. Add enum model definition to API, e.g.:
```yaml
  ErrorCode:
    type: string
    enum:
      - "REQUIRED_RESOURCE_ID_NOT_SET"
      - "REQUIRED_RESOURCE_NOT_FOUND"
      - "ALREADY_EXISTS"
      - "SOMETHING_ELSE"
```
2. Generate Server -> java-vertx.
3. Observe generated file for ErrorCode enum:
```java
package io.swagger.server.api.model;

import java.util.Objects;

public enum ErrorCode {
    {values&#x3D;[REQUIRED_RESOURCE_ID_NOT_SET, REQUIRED_RESOURCE_NOT_FOUND, ALREADY_EXISTS, SOMETHING_ELSE], enumVars&#x3D;[{name&#x3D;REQUIRED_RESOURCE_ID_NOT_SET, value&#x3D;&quot;REQUIRED_RESOURCE_ID_NOT_SET&quot;}, {name&#x3D;REQUIRED_RESOURCE_NOT_FOUND, value&#x3D;&quot;REQUIRED_RESOURCE_NOT_FOUND&quot;}, {name&#x3D;ALREADY_EXISTS, value&#x3D;&quot;ALREADY_EXISTS&quot;}, {name&#x3D;SOMETHING_ELSE, value&#x3D;&quot;SOMETHING_ELSE&quot;}]}, 
}
```

This issue has been created here https://github.com/phiz71/vertx-swagger/issues/74 by @codersam

**To resolve it**
The `enumOuterClass.mustache` template should be modified
