### ISSUE TITLE
[Python][Flask] Generate enum constants

### ISSUE THREAD

**Issue by calbach** [swagger-api/swagger-codegen#6529]
##### Description

No constants generated for swagger enums.

##### Swagger-codegen version

2.2.3

##### Swagger declaration file content or url

```
definitions
  FooEnum:
    type: string
    enum:
      - baz
      - bar
```

yields just a stub model file

##### Command line used for generation

`java -jar swagger-codegen-cli.jar generate  -l python-flask`

##### Suggest a fix/enhancement

Produce enum constants as is done in the python client models.
