### ISSUE TITLE
[JavaScript] CodeGen for Docs Camelizes Variables Without My Consent

### ISSUE THREAD

**Issue by brandonfuller** [swagger-api/swagger-codegen#6530]
##### Description

We just found that our JavaScript docs being created by Swagger are incorrect.  Our API takes variables like "grant_type" in the POST body.  However, the SDK docs tell the user to use "grantType".  We see that the Javascript CodeGen camelizes all the variables for the documentation, which confuses the dev reading the documentation.

Here is a sample documentation page:
https://github.com/bluejeans/api-rest-onvideo/blob/master/libs/javascript/docs/GrantRequestClient.md

##### Swagger-codegen version

2.2.3.  Looks to have always been this way.

##### Swagger declaration file content or url

```yaml
  GrantRequestClient:
    type: object
    properties:
      grant_type:
        type: string
        default: client_credentials
        description: The type of access token you are requesting.
      client_id:
        type: string
        description: The value given within the BlueJeans Enterprise Administration console.
      client_secret:
        type: string
        description: The value given within the BlueJeans Enterprise Administration console.
    required:
      - grant_type
      - client_id
      - client_secret
```

##### Command line used for generation

java -jar swagger-codegen-cli.jar generate -i ../swagger.yaml -l javascript -o ../libs/javascript --config config.javascript.json

Config just contains:

{
	"moduleName":"X",
	"projectName":"Y",
	"projectDescription":"Z",
	"projectLicenseName":"MIT",
	"gitUserId":"A",
	"gitRepoId":"B#npm-repo"
}

##### Steps to reproduce

1. Generate code via command line
2. View documentation file of a model that uses _ in a variable name

##### Suggest a fix/enhancement

Can we stop camelizing variables in the docs that should not be modified?
