### ISSUE TITLE
readOnly on nested objects

### ISSUE THREAD

**Issue by joerghaubrichs** [swagger-api/swagger-codegen#6537]
##### Description

Apparently the readOnly property is ignored for definitions of type object. In my example, SomeDefinition has a property someSubObject, which is an object and should be readOnly. So I would expect someSubObject to be in the list of readOnlyVars for SomeDefinition, but instead I find it in the readWriteVars list.

The other readOnly property, someString, is correctly listed in readOnlyVars and not in readWriteVars.

Is there something wrong with the definition, or is this a bug?

##### Swagger-codegen version

2.2.3

##### Swagger declaration file content or url

```yaml
definitions:
  SomeDefinition:
    type: object
    properties:
      someString:
        readOnly: true
        type: string
      someSubObject:
        readOnly: true
        type: object
        properties:
          someProperty:
            type: string
```
