### ISSUE TITLE
[JAVA][JAXRS] DecimalMin annotation does not respect exclusiveMinimum

### ISSUE THREAD

**Issue by tobymurray** [swagger-api/swagger-codegen#6718]
##### Description
Specifying a `number` property with `exclusiveMin` set to `true` does not create the corresponding `inclusive = false` on a `DecimalMin` annotation.

###### Expected
```
public class User   {
...
  /**
   * Get id
   * minimum: 10
   * @return id
   **/
  @JsonProperty("id")
  @ApiModelProperty(value = "")
 @DecimalMin("10", inclusive = false)  public BigDecimal getId() {
    return id;
  }
...
```
###### Actual

```
public class User   {
...
  /**
   * Get id
   * minimum: 10
   * @return id
   **/
  @JsonProperty("id")
  @ApiModelProperty(value = "")
 @DecimalMin("10")  public BigDecimal getId() {
    return id;
  }
```

##### Swagger-codegen version

Tried in 2.2.3, 2.2.1, and on the head of `master`

##### Swagger declaration file content or url
Modifying the pet store example, picking any definition. 
```
...
definitions:
  User:
    type: "object"
    properties:
      id:
        type: "number"
        minimum: 10
        exclusiveMinimum: true
...
```

##### Command line used for generation

With the following configuration:
```json
{
  "library":"jersey2"
}
```

java -jar swagger-codegen-cli-2.2.1.jar generate -c config.json -l java -i "D:/swaggerFile.json"

##### Steps to reproduce

1. Take the pet store swagger file
1. Change `User` `id` property to be a `number` with `exclusiveMinimum: true`
1. Generate the `jaxrs` server files
