### ISSUE TITLE
[Java] Bug: Path parameter of type ENUM generates faulty code with JavaSpring api.mustache template

### ISSUE THREAD

**Issue by RikEnde** [swagger-api/swagger-codegen#6795]
##### Description

Path parameter of type ENUM generates faulty code with JavaSpring api.mustache template

Corresponding code is generated correctly if the in: parameter is changed from path to query

Actual:
```
        default ResponseEntity<List<Foo>> fooTypeFooNumberGet(@ApiParam(value = "The identifier",required=true ) @PathVariable("nr") String nr,@ApiParam(value = "The type.",required=true, allowableValues="{values=[DOG, CAT], enumVars=[{name=DOG, value="CAT"}, {name=DOG, value="CAT"}]}" ) @PathVariable("type") String type) {
        // do some magic!
        return new ResponseEntity<List<Foo>>(HttpStatus.OK);
        }
```

Expected:
```
        default ResponseEntity<List<Foo>> fooTypeFooNumberGet(@ApiParam(value = "The identifier",required=true ) @PathVariable("nr") String nr,@ApiParam(value = "The type.",required=true, allowableValues="DOG, CAT" ) @PathVariable("type") String type) {
        // do some magic!
        return new ResponseEntity<List<Foo>>(HttpStatus.OK);
        }
```
##### Swagger-codegen version

2.2.3

##### Swagger declaration file content or url

```
  '/foo/{type}/{nr}':
    parameters:
      - name: nr
        in: path
        description: The number
        required: true
        type: string
        x-example: '123'
      - name: type
        in: path
        description: The type.
        required: true
        type: string
        enum: ["DOG","CAT"]
        x-example: 'DOG'
```
##### Command line used for generation

swagger-codegen-gradle-plugin: id 'org.detoeuf.swagger-codegen' version '1.7.4'

```
##### Steps to reproduce

Generate a ApiControllerInterface from api.mustache with an enum as path variable

##### Related issues/PRs

did not find one
