### ISSUE TITLE
[Typescript][Angular] bug: Enum generates empty name.

### ISSUE THREAD

**Issue by HermenOtter** [swagger-api/swagger-codegen#6822]
##### Description

I think something went wrong when the enum generation [recently changed](https://github.com/swagger-api/swagger-codegen/issues/6206). It currently generates empty names?

##### Swagger-codegen version

The current(time of writing) master (commit f78d958ec01917353fa43aad49ad4f6744843bdb ))

##### Swagger declaration file content or url
**The defined enum:**
```yaml
indicatie_actief:
    type: "string"
    maxLength: 1
    description: "Indication whether the object is active or not"
    enum: 
    - J
    - N
```

**Referenced in:**
```yaml
responses:
        200:
          description: "Status 200"
          schema:
            type: "object"
            properties:
              items:
                type: "array"
                items:
                  type: "object"
                  allOf:
                  - type: "object"
                    properties:
                      ...more props...
                      indicatie_actief:
                        $ref: "#/definitions/indicatie_actief"
```

**Results in:**
```export type  = 'J' | 'N';

export const  = {
    J: 'J' as ,
    N: 'N' as 
}

```
**Bug: The names are missing**
Any ideas how to fix?

##### Command line used for generation

generate -i <url> -l typescript-angular

**Comment by macjohnny** [comment]
@bedag-moo could you have a look at this?

**Comment by bedag-moo** [comment]
That is not my code; emitting this const was added by @kenisteward in f7471add70f1cabdd597aecc304fd131016cae3e

**Comment by kenisteward** [comment]
I'll take a look at this. Could you give me the complete example of your yaml or is this it?

**Comment by kenisteward** [comment]
Also could you give me the full model generation so I can make sure I know what is wrong

**Comment by kenisteward** [comment]
@hermenOtter I have a feeling it is because I used enum name somewhere I should have used class name but when I get your fully generated model example and a yaml to go off I can check for sure

**Comment by kenisteward** [comment]
@HermenOtter Please check #6833 changes on my forked repo to see if it fixes your issue

**Comment by HermenOtter** [comment]
I had issues with generation inside an allOf before, so I tried to define it outside of the response, but that didn't work either. I am still looking for a solution or a work around.

@sebastianhaas I have seen you working on the typescript-angular generation, maybe you have an idea?

**Comment by HermenOtter** [comment]
Thank you all for the fast responses. @kenisteward I tried your pull request with mvn clean package, but it didn't seem to work when I generated code from the new build(it had a ton of warnings btw, not sure if that is relevant). 

I am not sure how much of the yaml file and the models I can post, I am checking that currently and will report back.

**Comment by kenisteward** [comment]
Just give me the bare bone properly configures yaml file while making sure
you replace all the names. I'm using enums as well and not having this
issue so I need an example to debug .

**Comment by kenisteward** [comment]
Also I just wanna make sure. It is generating the type part but not the
const part.

Also could you try it outside of the all of with my branch ?

**Comment by HermenOtter** [comment]
**I forgot to post this:**
```yaml
definitions:
  indicatie_actief:
    type: "string"
    description: "Indication whether the object is active or not"
    enum: 
      - "J"
      - "N"
  indicatie_uniek:
    type: "string"
    description: "Indication whether the object is unique or not"
    enum: 
      - "J"
      - "N"
```
@kenisteward I have been researching the issues and it seems you can't declare a enum in the root of a defintion or something with the allOf like you said.

I will try a code generation without using allOf and then report back to you.
