### ISSUE TITLE
[CPPREST][C++]Accessors for boolean fields are not given a method name starting with "is"

### ISSUE THREAD

**Issue by javakrieg** [swagger-api/swagger-codegen#6854]
##### Description

If you have a boolean property in a definition file (e.g. "fixed"), the Java code generator will produce a setter called "setFixed" and a getter called "isFixed".  This is expected.  However, the CppRest/C++ code generator will produce a setter called "setFixed" but the getter will be called "getFixed".  This is incorrect.  It too should be "isFixed".

##### Swagger-codegen version

2.2.3

##### Swagger declaration file content or url

```yaml
  Parameter:
    type: object
    properties:
      name:
        type: string
      fixed:
        type: boolean
        description: True if the parameter cannot be changed, false otherwise.
```
