### ISSUE TITLE
[javascript-closure-angular]File uploads not working

### ISSUE THREAD

**Issue by zihengcai** [swagger-api/swagger-codegen#6875]
##### Description

The javascript-closure-angular client generated by swagger maven plugin and online swagger editor can’t upload file.

##### Swagger-codegen version

online swagger editor and swagger maven plugin version 2.2.2

##### Swagger declaration file content or url

```yaml
put:
      consumes:
        - multipart/form-data
      parameters:
        - name: name
          in: query
          required: true
          type: string
        - name: schemaVersion
          in: query
          required: true
          type: string
        - name: dataVersion
          in: query
          required: true
          type: string
        - name: file
          in: formData
          required: true
          type: file
```
```generates client code
headerParams['Content-Type'] = 'application/x-www-form-urlencoded';
 formParams['file'] = file;
  /** @type {!Object} */
  var httpRequestParams = {
    method: 'PUT',
    url: path,
    json: false,
        data: this.httpParamSerializer(formParams),
    params: queryParameters,
    headers: headerParams
  };
```

##### Command line used for generation

<groupId>io.swagger</groupId>
                <artifactId>swagger-codegen-maven-plugin</artifactId>
                <version>${swagger-codegen-maven-plugin.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>${basedir}/../csputility/src/main/resources/api/servorch.yaml</inputSpec>
                            <language>javascript-closure-angular</language>
                            <output>${basedir}/src/main/webapp/lib/swagger/</output>
                        </configuration>
                    </execution>
                </executions>
##### Suggest a fix/enhancement

When I upload the file ,the response status code is always 415,and I can't push any file.
The generated client of angular for file uploading is different form $http in traditional angular,because the troditional one works well.
