### ISSUE TITLE
[java] enforcement of "required" fields in Definitions

### ISSUE THREAD

**Issue by sashank** [swagger-api/swagger-codegen#6883]
Not really bug rather a question and suggestion , 
Lets say two fields are marked as required in the Definition of the Object like below.

```yaml  Pet:
    type: "object"
    required:
    - "name"
    - "photoUrls"
```

How is this enforced while generating the code ? I don't see any restrictions for making it mandatory in the generated code. 

On related topic , no constructors for models are generated apart from set and get methods. May be required fields could be used and an auto generator could be created. 

FYI , I have used code-gen 2.3.0 with java as language
