### ISSUE TITLE
[Typescript-Fetch] incorrect handling of nullable for additionalProperties

### ISSUE THREAD

**Issue by arhont375** [swagger-api/swagger-codegen#7013]
##### Description

It will create same code for additional properties with nullable and non nullable elements.

Generated code:
```ts
export interface EnvVars {
    works?: { [key: string]: string; };
    notworks?: { [key: string]: string; };
}
```
How I think it should be
```ts
export interface EnvVars {
    works?: { [key: string]: string | null; };
    notworks?: { [key: string]: string | null; };
}
```

##### Swagger-codegen version

Latest stable 2.2.3
And latest 3 (Tue Nov 14 06:42:44 UTC 2017)

##### Swagger declaration file content or url
Try to generate with adding somewhere such definitions
```yaml
definitions:
  envVars:
    description: description
    type: object
    properties:
      works:
        type: object
        additionalProperties:
          type: string
          x-nullable: false
      notworks:
        type: object
        additionalProperties:
          type: string
          x-nullable: true
```
##### Command line used for generation

```bash
java -jar ./swagger-codegen-cli.jar generate -l typescript-fetch -i ./spec/swagger.yml -DnpmName=client-ts -DnpmVersion=0.1.0 -o ts-gen
````

##### Steps to reproduce

Try to generate with provided yaml

##### Related issues/PRs

Can't find same problem.

##### Suggest a fix/enhancement

Golang not affected.
