### ISSUE TITLE
[cpprest] HTTP Request body always treated as "application/json"

### ISSUE THREAD

**Issue by etherealjoy** [swagger-api/swagger-codegen#7101]
##### Description

When Swagger model is specified to consume
        - "text/plain"
        - "application/octet-stream"
Code is always generated to use "application/json"
##### Swagger-codegen version

2.3.0
3.0.0

##### Swagger declaration file content or url

``` yaml
  /images/create:
    post:
      summary: "Create an image"
      description: "Create an image by either pulling it from a registry or importing it."
      operationId: "ImageCreate"
      consumes:
        - "text/plain"
        - "application/octet-stream"
```
##### Command line used for generation

java -jar /home/dev/swagger-codegen/modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i /home/dev/gen-test/yaml/docker-v132-subset.yaml  -o /home/dev/gen-test/gen  -l cpprest
