### ISSUE TITLE
[Rust] UUID path parameters generates broken code

### ISSUE THREAD

**Issue by aykutakin** [swagger-api/swagger-codegen#7107]
##### Description
String type can be used for body, formData and query parameters but not for path parameters. As of now, if you want to use String path parameter, generated code can not be compiled since String is marked in models module.

Please see the last function:
```rust
pub trait PetApi {
    fn add_pet(&self, body: ::models::Pet) -> Box<Future<Item = (), Error = Error>>;
    fn delete_pet(&self, pet_id: i64, api_key: &str) -> Box<Future<Item = (), Error = Error>>;
    fn find_pets_by_status(&self, status: Vec<String>) -> Box<Future<Item = Vec<::models::Pet>, Error = Error>>;
    fn find_pets_by_tags(&self, tags: Vec<String>) -> Box<Future<Item = Vec<::models::Pet>, Error = Error>>;
    fn get_pet_by_id(&self, pet_id: i64) -> Box<Future<Item = ::models::Pet, Error = Error>>;
    fn update_pet(&self, body: ::models::Pet) -> Box<Future<Item = (), Error = Error>>;
    fn update_pet_with_form(&self, pet_id: i64, name: &str, status: &str) -> Box<Future<Item = (), Error = Error>>;
    fn upload_file(&self, pet_id: ::models::String, additional_metadata: &str, file: ::models::File) -> Box<Future<Item = ::models::ApiResponse, Error = Error>>;
}
```

##### Swagger-codegen version
Tested with latest master branch as of 61e706ba6f6b75d68651028d1796a2b12e2034f2
And Public Pre-built Docker images https://hub.docker.com/r/swaggerapi/swagger-codegen-cli/ 

##### Swagger declaration file content or url
```yaml
  /pet/{petId}/uploadImage:
    post:
      tags:
      - "pet"
      summary: "uploads an image"
      description: ""
      operationId: "uploadFile"
      consumes:
      - "multipart/form-data"
      produces:
      - "application/json"
      parameters:
      - name: "petId"
        in: "path"
        description: "ID of pet to update"
        required: true
        type: "string"
        format: "uuid"
```
##### Command line used for generation
```bash
java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate \
   -i ~/rust-test/swagger.yaml \
   -l rust \
   -o ~/rust-test/petstore-client
```
##### Steps to reproduce
First change pet store example as given in file content and save it under `~/rust-test/` folder. Then, run the command given in above section.

##### Related issues/PRs
Haven't found any

##### Suggest a fix/enhancement
Produced code related to the [this line](https://github.com/swagger-api/swagger-codegen/blob/5e9d977a03756b0445f026dec0a4f1b6095ff8b1/modules/swagger-codegen/src/main/resources/rust/api.mustache#L27)

**Comment by aykutakin** [comment]
Further investigation showed that, below yaml is processed correctly:
```yaml
  /pet/{petId}/uploadImage:
    post:
      tags:
      - "pet"
      summary: "uploads an image"
      description: ""
      operationId: "uploadFile"
      consumes:
      - "multipart/form-data"
      produces:
      - "application/json"
      parameters:
      - name: "petId"
        in: "path"
        description: "ID of pet to update"
        required: true
        type: "string"
```
Problem occurs only if `format` is set as `UUID` like:
```yaml
  /pet/{petId}/uploadImage:
    post:
      tags:
      - "pet"
      summary: "uploads an image"
      description: ""
      operationId: "uploadFile"
      consumes:
      - "multipart/form-data"
      produces:
      - "application/json"
      parameters:
      - name: "petId"
        in: "path"
        description: "ID of pet to update"
        required: true
        type: "string"
        format: "uuid"
```
The reason is the separate control flow for UUID format:
https://github.com/swagger-api/swagger-codegen/blob/01a076c3fe3a44b370804db58270fc853adf06a8/modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java#L3587-L3595
