### ISSUE TITLE
JaxRS - Header parameters not in ApiOriginFilter.java

### ISSUE THREAD

**Issue by asgerjensen** [swagger-api/swagger-codegen#7118]
##### Description
When generating a server using the JaxRS generator, the resulting code emits an ApiOriginFilter.java file that does not take into account any header parameters defined in the spec.

The generated ApiOriginFilter.java will not contain this `X-Custom-Header` as an allowed header, meaning CORS errors when client connects.

##### Swagger-codegen version
2.2.1

##### Swagger declaration file content or url
```yaml
parameters:
    name: X-Custom-Header
    description: is a header
    type: boolean
    default: false
    in: header


// referenced from model
```

##### Suggest a fix/enhancement

Any parameters with 'in: header' should automatically be allowed to be sent to the service, and should therefore be in the generated ApiOriginFilter.java class.

I checked the .mustache file in this repo, and can see the current generated code is not configurable, or depending on anything, and I know too little about the mustache thing to know where to even start
