### ISSUE TITLE
Is it possible to customize generation of a client model properties?

### ISSUE THREAD

**Issue by a-voronov** [swagger-api/swagger-codegen#7143]
I'd like to migrate iOS client to swagger, but I'm trying to avoid changing existing code.
Unfortunately 'network' models are used everywhere inside the app, so there's no mapping from 'network' models to 'business' models yet.
Is it possible to have a custom 'mapping' of openapi spec models to those, that I want to be generated for a client?

Imagine I have an openapi model User:
```
User:
  type: object
  properties:
    firstName:
      type: string
    lastName:
      type: string
    userName:
      type: string
```

But corresponding `userName` property is currently named as a `nickName` on a client.
So I imagine having something like mapping spec that might help me to express this:
```
User:
  map:
    userName: nickName
```

Is there something like this? 
Or maybe you can suggest any alternatives to this solution?
Or maybe this idea should be treated as a band-aid to a bigger issue, that I should consider solving first? :)
