### ISSUE TITLE
SpringMVC template is ignoring the required attribute in swagger definition when generating @RequestHeader annotation

### ISSUE THREAD

**Issue by swinz** [swagger-api/swagger-codegen#719]
Given a param definition like this: 
```
  ifNoneMatchHeaderParameter:
    name: If-None-Match
    in: header
    description: https://tools.ietf.org/html/rfc7232#section-3.2
    required: false
    type: string
    format: https://tools.ietf.org/html/rfc7232#section-3.2
```
the current code generated (SpringMVC) for the `RequestHeader` is this: 

```java
@RequestHeader("ifNoneMatch")
```
Since `RequestHeader` has a default value (for required attribute), thus we get a required header when the swagger def defined it as not required.  Instead, I think we want this:

```java
@RequestHeader(value="ifNoneMatch", required=false)
```
The Pull req for this minor change is in #718
