### ISSUE TITLE
[JAVA] Extend classes in generated models not defined in YAML file

### ISSUE THREAD

**Issue by sharmasourabh** [swagger-api/swagger-codegen#7220]
##### Description

I would like to use the class as base class not defined in YAML file. Through import mapping, we can use classes which are not defined in YAML file as a members, but could not figure out how to use them as base class.

##### Swagger-codegen version

2.2.3

##### Swagger declaration file content or url
```yaml
  child:
    description: "Model that extends user defined model."
    allOf:
    - $ref: "UserDefinedModel"
    - type: "object"
      properties:
        childField:
          type: "string"
```

##### Command line used for generation

NA (normal command with required parameters)

##### Steps to reproduce

Not a bug

##### Suggest a fix/enhancement

Need a way to use external class to use as a base class.

**Comment by antonkholodok** [comment]
_import-mappings_ option just tells to code generator not to generate classes mentioned in mapping, but use mapped types in the code imports:

> --import-mappings <import mappings>
            specifies mappings between a given class and the import that should
            be used for that class in the format of type=import,type=import

_$ref_ expects valid JSON reference, either local or external. During the code generation step it has no idea where to look at your base class definition.

I assume you have to provide path to YAML file where your model is defined:
```
child:
    description: "Model that extends user defined model."
    allOf:
    - $ref: "../path/to/model/file/definition.yaml#/definitions/UserDefinedModel"
    - type: "object"
      properties:
        childField:
          type: "string"
```
