### ISSUE TITLE
[Angular-typescript] Regression/bug: Parameters with an _ ignore naming convention 

### ISSUE THREAD

**Issue by HermenOtter** [swagger-api/swagger-codegen#7262]
##### Description
Parameters with an _ ignore naming convention since a few days. This bug occurred a few months ago as well and has been fixed at the time.

##### Swagger-codegen version

master(54ce4caafc3909056630d97b428b2e8a9022a6f9 and  8ae11847d3e2300bc79cc9a08c20c187cd2d4c15) are not working as expected.

##### Swagger declaration file content or url
```yaml
/sadr/v1/soorten_adres/{code_soort_adres}:
    parameters:
    - name: "code_soort_adres"
      in: "path"
      required: true
      type: "string"
```
##### Command line used for generation

```java -jar swagger-codegen-cli.jar generate -i https://api.swaggerhub.com/apis/Centric/Belastingen_Subjecten/0.2.4 -l typescript-angular -c=./SCGConf.md```

**SCGConf.md**
`{"modelPropertyNaming": "original"}`

**Code generation**
Generates `code_soort_adres` as parameter for the method, but when used in that same method it is called as `codeSoortAdres` which obviously doesn't work. 

`public getSoortenAdresByCode(code_soort_adres: string,`
`return this.httpClient.get<any>(${this.basePath}/.../${encodeURIComponent(String(codeSoortAdres))}`

##### Related issues/PRs

[7201, regression](https://github.com/swagger-api/swagger-codegen/issues/7201)

##### Suggest a fix/enhancement

I believe it is has something to do with issue 7201.

@wing328 @JFCote @kenisteward
