### ISSUE TITLE
[Rust] Add support for array schemas in Rust template

### ISSUE THREAD

**Issue by tbourvon** [swagger-api/swagger-codegen#7293]
##### Description

Currently, the Rust template will generate an empty struct when trying to generate a model from an array schema. This is incorrect and undesirable. Instead, we should generate a 1-item tuple like `struct Test(Vec<f64>);`

##### Swagger-codegen version

3.0.0

##### Swagger declaration file content or url

```yaml
components:
  schemas:
    Test:
      type: array
      items:
        type: number
        format: double
```

This currently generates `struct Test { }`.

##### Command line used for generation

```bash
java -jar swagger-codegen/modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate \
   -i apis/gdax/openapi.yaml \
   -l rust \
   -o apis/gdax/generated_api
```

##### Steps to reproduce

Try to generate a model from an array schema for Rust.

##### Suggest a fix/enhancement

A proposed fix is to use `vendorExtensions.x-is-array-model` in the rust template and to generate different code depending on it.
