### ISSUE TITLE
Is there any way to generate example json file?

### ISSUE THREAD

**Issue by tfujita-folio** [swagger-api/swagger-codegen#7449]
Is there any way to generate example json file?

example) `Pet.json`
https://github.com/swagger-api/swagger-codegen/blob/master/samples/yaml/pet.yml#L145

```json
{
  "id": "123456",
  "name": "hoge"
}
```

**Comment by juggernaut0425** [comment]
@tfujita-folio Do you mean you want to convert the yaml file to json? Many tools can achieve this.

**Comment by tfujita-folio** [comment]
@juggernaut0425 
I want to use example data as json file.

```yaml
Pet: 
    id: Pet
    description: "A pet is a person's best friend"
    required: 
      - id
      - name
    properties: 
      id: 
        type: integer
        format: int64
        example: 123456
      tags: 
        type: array
        items: 
          $ref: Tag
      name: 
        type: string
        example: hoge
      status: 
        type: string
        description: pet status in the store
        enum: 
          - available
          - pending
          - sold
        example: available
      category: 
        $ref: Category
      photoUrls: 
        type: array
        items: 
          type: string
```

↓

```json
{
  "id": "123456",
  "name": "hoge",
  "status": "available"
}
```
