### ISSUE TITLE
A Parameter's default value is not flowing from the swagger def to the templates

### ISSUE THREAD

**Issue by swinz** [swagger-api/swagger-codegen#748]
specifying this in a swagger yaml definition:

```
parameters:
  bucketSizeQueryParameter:
    name: bucketSize
    in: query
    description: Number of elements to be returned as a paged set
    default: 50
    required: false
    type: number
    format: double
```
results in the **default** value not being available to the templates. 

This change: #747 moves the value so that it is available, and uses the value to populate the RequestParam.defaultValue SpringMVC annotation
