### ISSUE TITLE
[Android] API Key based Authentication not included in generated client

### ISSUE THREAD

**Issue by bansriyar** [swagger-api/swagger-codegen#7499]
##### Description

I am trying to generate an Android client which has the API key based security schemes defined. The endpoint definitions are also correct (see the snippet). Also, note that I am able to generate the Java and python clients correctly. 

The config that I am using for the android client is as follows:
```json
{
  "artifactId": "rsearch",
  "library": "volley"
}
```

##### Swagger-codegen version

Have tried with both 2.3.0 and 2.3.1. 

##### Swagger declaration file content or url

<!-- if it is a bug, a json or yaml that produces it.

The relevant sections of the yaml is pasted below:
```yaml
securityDefinitions:
  readAppID:
    type: apiKey
    in: header
    name: X-RSearch-App-ID
  authToken:
    type: apiKey
    in: query
    name: auth_token

paths:
  /indexes:
    get:
      tags:
        - rsearch
      description: Fetches indexes
      operationId: getAllIndexes
      produces:
        - application/json
      security:
        - readAppID: []
        - authToken: []
```

##### Command line used for generation

java -jar tools/swagger-codegen-cli-2.3.1.jar generate -i source/rsearch.yaml -l android -o tmp/rsearch-sdk-android -c source/config/android/config.json

##### Steps to reproduce

Generate the client, check documentation and also the generated API Class. 

##### Related issues/PRs

https://github.com/swagger-api/swagger-codegen/issues/7088

##### Suggest a fix/enhancement
Not sure.
