### ISSUE TITLE
Kotlin: Client codegen fails to create valid inner enums (missing data type)

### ISSUE THREAD

**Issue by redwarp** [swagger-api/swagger-codegen#7596]
##### Description

When generating Kotlin client code, the generated code is not proper kotlin code if the class created contains an inner enum. 

##### Swagger-codegen version

2.3.0 - 3.0.0

##### Swagger declaration file content or url

```yaml
description: Recorded vote
schema:
    properties:
        answer_id:
            description: Answer ID voted
            type: string
        helpful_vote_count:
            description: New helpful vote count of the answer
            type: integer
        vote:
            description: Biz User vote to answer
            type: string
            enum:
            - HELPFUL
            - NOT_HELPFUL
    required:
    - answer_id
    - helpful_vote_count
    - vote
    title: AnswerVote
    type: object
```
generates:

```kotlin
/**
 * 
 * @param answer_id Answer ID voted
 * @param helpful_vote_count New helpful vote count of the answer
 * @param vote Biz User vote to answer
 */
data class AnswerVote (
    /* Answer ID voted */
    val answer_id: kotlin.String,
    /* New helpful vote count of the answer */
    val helpful_vote_count: kotlin.Int,
    /* Biz User vote to answer */
    val vote: AnswerVote.Vote
) {

    /**
    * Biz User vote to answer
    * Values: hELPFUL,nOTHELPFUL
    */
    enum class Vote(val value: ){
    
        hELPFUL("HELPFUL"),
    
        nOTHELPFUL("NOT_HELPFUL");
    
    }

}
```

Besides the casing issue, the val value has no type.

##### Suggest a fix/enhancement

I'm creating a pull request right now. It appears that there is something wrong with the mustache template.
