### ISSUE TITLE
[html2] When using array of objects, array initially renders as 'undefined'

### ISSUE THREAD

**Issue by igeryu** [swagger-api/swagger-codegen#7709]
##### Description

If there is a request or response that uses an array of non-primitives, the parameter for that request/response initially renders as an array with the contents of 'undefined'.

##### Swagger-codegen version

Using v2.3.1

##### Swagger declaration file content or url

This can be seen in the petstore example:
```yaml
   - path: /pet/findByTags 
     operations:  
       - method: GET 
         summary: Finds Pets by tags 
         notes: "Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing." 
         type: array 
         items:  
           $ref: Pet 
         nickname: findPetsByTags 
         produces:  
           - application/json 
           - application/xml 
         parameters:  
           - name: tags 
             description: Tags to filter by 
             required: true 
             allowMultiple: true 
             type: string 
             paramType: query 
         responseMessages:  
           - code: 400 
             message: Invalid tag value 
         deprecated: "true" 
```

##### Command line used for generation

Using the 'html2' generation language

##### Steps to reproduce

Generate 'html2' output from a specification that includes an array of objects.

I have tested this with both a reference (the example above) and the explicit definition of the schema object in-line with the array definition, e.g.:
```yaml
   - path: /pet/findByTags 
     operations:  
       - method: GET 
         summary: Finds Pets by tags 
         notes: "Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing." 
         type: array 
         items:  
           type: "object"
                properties:
                   propA:
                       type: "string"
                   propB:
                       type: "string"
         nickname: findPetsByTags 
         produces:  
           - application/json 
           - application/xml 
         parameters:  
           - name: tags 
             description: Tags to filter by 
             required: true 
             allowMultiple: true 
             type: string 
             paramType: query 
         responseMessages:  
           - code: 400 
             message: Invalid tag value 
         deprecated: "true" 
```

##### Related issues/PRs

I can't find any examples or mentions of this issue

##### Suggest a fix/enhancement

Seems to be a discrepancy with the ordering between parsing schema definitions and rendering parameters, since even an in-line schema object is loaded into the ``defs`` object.
