### ISSUE TITLE
[SpringMVC] Upload files Issue

### ISSUE THREAD

**Issue by pulgawang** [swagger-api/swagger-codegen#7753]
## Description

I tried to upload a file to spring server created by swagger-codegen, and crashed, exception below:

>Request processing failed; nested exception is org.springframework.web.multipart.MultipartException: Could not parse multipart servlet request; nested exception is java.lang.IllegalStateException: Unable to process parts as no multi-part configuration has been provided

I have found a old version [issue #1273](https://github.com/swagger-api/swagger-codegen/issues/1273) but I cannot insert the code to SwaggerConfig.java cause of version.

## Swagger-codegen version
2.3.1

## Swagger declaration file content or url

```
consumes:
        - multipart/form-data
      parameters:
        - in: formData
          name: image
          required: true
          type: file
```
