### ISSUE TITLE
isEnum returns false when enum is referenced

### ISSUE THREAD

**Issue by kolisko** [swagger-api/swagger-codegen#7763]
##### Description

When is defined enum as standalone type and is referenced from elsewhere, template var _isEnum_ is set to _false_.

##### Swagger-codegen version

```
<dependency>
            <groupId>io.swagger</groupId>
            <artifactId>swagger-codegen-cli</artifactId>
            <version>2.3.1</version>
        </dependency>
```

##### Swagger declaration file content or url

```
definitions:
 UIDocumentsOverviewLock:
    type: object
    properties:
      action:
        $ref: '#/definitions/InvalidateDocsAction'
 InvalidateDocsAction:
    type: string
    enum:
      - FINAL
      - INDIVIDUALIZED
      - FC_NOT_INDIVIDUALIZED
      - FC_AND_INDIVIDUALIZED
```

##### Steps to reproduce

in mustasche template is isEnum false on property 'action' and should be true because InvalidateDocsAction is defined as enum.

##### Suggest a fix/enhancement

Checking the referenced class type

**Comment by jmini** [comment]
Can you elaborate on this?
I am not not sure that what you are describing is correct.

When the `action` property is generated, it represents a binding to an existing Object: `io.swagger.model.InvalidateDocsAction`.  The `InvalidateDocsAction` class is an enum, the binding is not.

This is different than when the enums values are defined directly in the property:

```
definitions:
  UIDocumentsOverviewLock:
    type: object
    properties:
      action:
        type: string
        enum:
          - FINAL
          - INDIVIDUALIZED
          - FC_NOT_INDIVIDUALIZED
          - FC_AND_INDIVIDUALIZED
```

In this second case, an inner-enum is generated.
