### ISSUE TITLE
[C++] [pistache] Optional integer query parameter is not supported

### ISSUE THREAD

**Issue by yvesdm3000** [swagger-api/swagger-codegen#7817]
##### Description

When I want to use an optional query-parameter as an integer, the generated code uses an pistache::Optional<std::string> instead of a pistache::Optional<int>

##### Swagger-codegen version

2.4_master

##### Swagger declaration file content or url

```yaml
parameters:
  maxParam:
    name: _max
    in: query
    description: Limits the number of returned results
    required: false
    type: integer
    default: 10
```
##### Command line used for generation

java -DdebugModels=true  -jar ../swagger-codegen/modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -v -i swagger.yaml -l pistache-server -o server

##### Suggest a fix/enhancement
See pull request 
https://github.com/swagger-api/swagger-codegen/pull/7816
