### ISSUE TITLE
Custom codegen module not passing operations to model

### ISSUE THREAD

**Issue by jimcullenaus** [swagger-api/swagger-codegen#7829]
##### Description

Using the [instructions in the README for making your own codegen modules](https://github.com/swagger-api/swagger-codegen#making-your-own-codegen-modules), currently my `MyclientcodegenGenerator.java` is pretty much identical to the default version that gets spat out.

##### Swagger-codegen version

2.4.0-SNAPSHOT and whatever else is pulled by default currently when cloning the repo.

##### Swagger declaration file content or url

In api.mustache:

```yaml
package: {{package}}

# operations block
{{#operations}}
classname: {{classname}}
# loop over each operation in the API:
{{#operation}}
# each operation has an `operationId`:
operationId: {{operationId}}
# and parameters:
{{#allParams}}
{{paramName}}: {{dataType}}
{{/allParams}}
{{/operation}}
# end of operations block
{{/operations}}
```

produces (truncated):

```yaml
package: io.swagger.client.api
# operations block
classname: PersonApi
# loop over each operation in the API:
# each operation has an `operationId`:
operationId: personsGet
# and parameters:
pageSize: Integer
pageNumber: Integer
...
# end of operations block
```

when run on a YAML file created as a result of following [this tutorial](https://apihandyman.io/writing-openapi-swagger-specification-tutorial-part-1-introduction/).

That's totally fine, and what I would expect. However, when I also create a `model.mustache` file that looks as follows:

```cs
using System.Collections.Generic;
namespace {{package}}.Model {
    {{#operations}}public class {{classname}} {
    {{#operation}}
        public string {{operationId}}({{#allParams}}{{dataType}} {{paramName}}{{^-last}}, {{/-last}}{{/allParams}});
    }
    {{/operation}}
    {{/operations}}
    {{^operations}}
    // no operations for some reason
    {{/operations}}
}
```

the result is

```cs
using System.Collections.Generic;
namespace io.swagger.client.model.Model {
    // no operations for some reason
}
```

The expected behaviour would have been for each operation to turn into a method with the given parameters, for example

```cs
        public string personsGet(Integer pageSize, Integer pageNumber);
```

##### Suggest a fix/enhancement

Either the docs need to be updated to provide sufficient explanation for *why* this is the correct behaviour and how to access the desired variables in each file, or it is a bug and the `operations` should be passed to the model file.
