### ISSUE TITLE
Backslashes added to long lines for swagger-yaml generation

### ISSUE THREAD

**Issue by john-french** [swagger-api/swagger-codegen#7839]
##### Description
The `swagger-yaml` generation adds backslashes to long lines e.g. this:

```json
    "description" : "Are creatures of the cosmos Rig Veda? Trillion! Made in the interiors of collapsing stars Apollonius of Perga, globular star cluster emerged into consciousness bits of moving fluff brain is the seed of intelligence citizens of distant epochs another world courage of our questions a mote of dust suspended in a sunbeam ship of the imagination, paroxysm of global death intelligent beings? Two ghostly white figures in coveralls and helmets are soflty dancing hearts of the stars brain is the seed of intelligence quasar, Drake Equation billions upon billions and billions upon billions upon billions upon billions upon billions upon billions upon billions!\n",
```
becomes this:

```yaml
  description: "Are creatures of the cosmos Rig Veda? Trillion! Made in the interiors\
    \ of collapsing stars Apollonius of Perga, globular star cluster emerged into\
    \ consciousness bits of moving fluff brain is the seed of intelligence citizens\
    \ of distant epochs another world courage of our questions a mote of dust suspended\
    \ in a sunbeam ship of the imagination, paroxysm of global death intelligent beings?\
    \ Two ghostly white figures in coveralls and helmets are soflty dancing hearts\
    \ of the stars brain is the seed of intelligence quasar, Drake Equation billions\
    \ upon billions and billions upon billions upon billions upon billions upon billions\
    \ upon billions upon billions!\n"```
```

##### Swagger-codegen version

Current version running at generator.swagger.io, 2.3.1 I believe.

##### Swagger declaration file content or url
Here's a [gist](https://gist.github.com/john-french/6510d8c206490be5e8629331bb1d1750#file-petstoreapi-longdescription-json) of a PetStore API with a couple of long descriptions (courtesy of [Sagan Ipsum](http://saganipsum.com/)).

**Comment by HugoMario** [comment]
@john-french this [PR](https://github.com/swagger-api/swagger-codegen/pull/7864) was made to solve this issue. Please check changes and let me know if there is something else to tweak.

**Comment by john-french** [comment]
@HugoMario This resolves the backslash issue but introduces a new issue i'm afraid. Now there are a lot of redundant `null` fields in the `swagger-yaml` output, which weren't present before that PR. Using the same test input API as above, the output yaml file is now 2035 lines, vs. 748 before the fix. 1304 of these lines are null. Here's an example of what a section looks line now:

```yaml
schemes:
- http
consumes: null
produces: null
security: null
paths:
  /pet:
    get: null
    head: null
    post:
      tags:
      - pet
      summary: Add a new pet to the store
      description: null
      operationId: addPet
      schemes: null
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
```
 and here it was before:

```yaml
schemes:
- "http"
paths:
  /pet:
    post:
      tags:
      - "pet"
      summary: "Add a new pet to the store"
      operationId: "addPet"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/json"
      - "application/xml"
```
