### ISSUE TITLE
[typescript-fetch] need help to generate model using command line !

### ISSUE THREAD

**Issue by mike03081972** [swagger-api/swagger-codegen#8107]
What is the correct command line to generate the typescript model outside my swagger.yaml file ?

If I execute the generator, I receive this error message :

    Error (model name matches existing language type) cannot be used as a model name. Renamed to ModelError

Command Line :

java -jar -Dmodels e:\swagger-codegen-cli2.3.1.jar generate -l typescript-fetch -c E:\evs-via\evs-via-timeline-core\config\codegen-config.json -i E:\evs-via\evs-via-timeline-core\tmp\rest-api.yaml -o c:\temp\

[files.zip](https://github.com/swagger-api/swagger-codegen/files/1960940/files.zip)

Target project where I must use the generated models :

NodeJS

My project must auto generate the swagger model for language typescript using nodejs !

**Comment by macjohnny** [comment]
@mike03081972 the problem is the naming of one of your models, i.e. 
```yaml
 Error:
    type: object
    required:
      - _type
      - key
      - message
    properties:
      _type:
        type: string
        default: Error
        example: Error
...
```
since this would generate `interface Error {}` and since `Error` is a reserved keyword, it was renamed to `ModelError`, which works correctly, so this issue should be closed.
