### ISSUE TITLE
[Python] Default NATIVE_TYPES_MAPPING doesn't support unicode type ,so could not deal with Chinese character

### ISSUE THREAD

**Issue by markshao** [swagger-api/swagger-codegen#8299]
##### Description

My server response return the body with chinese character value, and the python client covertion will fail due to it only support the `str(data)` , 

##### Swagger-codegen version

2.3.1

##### Swagger declaration file content or url

The Name property contains the Chinese charascter response , I have customerize the NATIVE_TYPES_MAPPING , mapping the "str" to "unicode" as the work round . But I still need an e2e solution for it , I truely believe it is a common issue

```yaml 
 PersonList:
              type: "object"
              properties:
                PersonObject:
                  type: array
                  items:
                    type: object
                    properties:
                      PersonID:
                        type: string
                      InfoKind:
                        type: integer
                      SourceID:
                        type: string
                      DeviceID:
                        type: string
                      LeftTopX:
                        type: integer
                      LeftTopY:
                        type: integer
                      RightBtmX:
                        type: integer
                      RightBtmY:
                        type: integer
                      LocationMarkTime:
                        type: string
                      PersonAppearTime:
                        type: string
                      PersonDisAppearTime:
                        type: string
                      IDType:
                        type: string
                      IDNumber:
                        type: string
                      Name:
                        type: string
                      UsedName:
                        type: string
                      Alias:
                        type: string
                      GenderCode:
                        type: string
                      AgeUpLimit:
                        type: integer
                      AgeLowerLimit:
                        type: integer
                      EthicCode:
                        type: string
                      NationalityCode:
                        type: string
                      NativeCityCode:
                        type: string
                      ResidenceAdminDivision:
                        type: string
                      ChineseAccentCode:
                        type: string
                      PersonOrg:
                        type: string
                      JobCategory:
                        type: string
                      AccompanyNumber:
                        type: integer
                      HeightUpLimit:
                        type: integer
                      HeightLowerLimit:
                        type: integer
                      BodyType:
                        type: string
                      SkinColor:
                        type: string
                      HairStyle:
                        type: string
                      HairColor:
                        type: string
                      Gesture:
                        type: string
                      Status:
                        type: string
                      FaceStyle:
                        type: string
                      FacialFeature:
                        type: string
                      PhysicalFeature:
                        type: string
                      BodyFeature:
                        type: string
                      HabitualMovement:
                        type: string
                      Behavior:
                        type: string
```

##### Command line used for generation
java -jar bin/swagger-codegen-cli.jar generate -i ./viid_swagger.yaml -l python -o generated
