### ISSUE TITLE
[go][bug] Wrong body format for POST x-www-form-urlencoded

### ISSUE THREAD

**Issue by pinghe** [swagger-api/swagger-codegen#8347]
##### Swagger-codegen version

2.4.0-20180615.003317-272 (swagger-codegen-cli-2.4.0-20180615.003317-272.jar)

##### Swagger declaration file content or url

```yaml
      consumes:
        - "application/x-www-form-urlencoded"
      parameters:
        - in: "formData"
          name: "userName"
          required: true
          type: "string"

        - in: "formData"
          name: "fullName"
          required: true
          type: "string"
```

When the Content-Type is application/x-www-form-urlencoded instead of multipart/form-data, the generated client code is incorrect.

https://swagger.io/docs/specification/2-0/describing-parameters/#form-parameters
Form parameters are used to describe the payload of requests with Content-Type of:
application/x-www-form-urlencoded (used to POST primitive values and arrays of primitive values).
multipart/form-data (used to upload files or a combination of files and primitive data).

This form POSTs data to the form’s endpoint(x-www-form-urlencoded):
POST /survey HTTP/1.1
Host: example.com
Content-Type: application/x-www-form-urlencoded

userName=userName&fullName=fullName
