### ISSUE TITLE
[JAVA] generator cannot handle use of allOf or $ref for defined simple types

### ISSUE THREAD

**Issue by sgeeroms** [swagger-api/swagger-codegen#8498]
##### Description

When I define a common simple type like for example:

```
definitions:
...yaml
  Guid:
    type: string
    format: guid
    pattern: '^[0-9A-Fa-f]{8}(-[0-9A-Fa-f]{4}){3}-[0-9A-Fa-f]{12}$'
    description: |
      A guid identifier. No value can be set as "000000000-0000-0000-0000-00000000000".
    example: '5e0fe30e-3724-42c2-b5b9-0b1594b0b7a3'
    x-example: "5e0fe30e-3724-42c2-b5b9-0b1594b0b7a3"

```
And then I use this type as folllows in a defined obejct type:

```yaml
  MyObjectType:
    type: object
    required:
      - id
    properties:
      id:
        description: |
          the id of the object
        allOf:
          - $ref: "#/definitions/Guid"
```

or even...

```yaml
  MyObjectType:
    type: object
    required:
      - id
    properties:
      id:
        description: |
          the id of the object
        allOf:
          - $ref: "#/definitions/Guid"
```
Then the generated code is not correct.
In the first case the property "id" is simply missing from the "MyObjectType" class.
And in the second case the property is added as a class object property of Class type "Guid"
```java
public class MyObjectType{

  @JsonProperty("id")
  private Guid id= null;

```
but the class "Guid" does not exist, and its should be a String.

This is they way to define commonly used simple types in Swagger. 
Could the generator be changed to be able to handle this?

##### Swagger-codegen version

v2.2.3

##### Command line used for generation

```gradle
        main = 'io.swagger.codegen.SwaggerCodegen'
        args = ["generate",
                "-l", "java",                                                       // language
                "-i", "${project.ext.inputDir}${version}/${project.ext.inputFile}", // input
                "-c", configJson.getAbsolutePath(),                                 // config
                "-o", "${project.ext.sourceset}",                                   // output
        ]
        jvmArgs = ['-Dmodels']                                                      // generate models only
```

##### Suggest a fix/enhancement

When handling a "$ref" or "allOf" reference the type (object, string,...) of the referenced type should be take into account. So not always a class (object) reference is assumed.
