### ISSUE TITLE
Request: add property format url (for server codegen)

### ISSUE THREAD

**Issue by 4n70w4** [swagger-api/swagger-codegen#8500]
##### Description

It would be convenient to have this type for link validation.
for example, in a symfony it can be done in one line:
`@Assert\Url()`

##### Swagger-codegen version

2.3.0

##### Swagger declaration file content or url

```yaml
    properties:
      webhook_url:
        type: string
        format: url
```

##### Command line used for generation

java -jar swagger-codegen-cli.jar generate --input-spec api.swagger.yml --lang php-symfony --output app/bundles
