### ISSUE TITLE
[C#] Warning CS0472 for "required" enum parameters

### ISSUE THREAD

**Issue by sam1018** [swagger-api/swagger-codegen#8519]
##### Description

When marking an enum parameter as required, i am getting the following warning:
```
warning CS0472: The result of the expression is always 'false' since a value of type 'Order.IdEnum' is never equal to 'null' of type 'Order.IdEnum?'
```

##### Swagger-codegen version

It is happening with latest master branch (dbd0a4bb535de0d587c9ccec1465a25c8288ee96).

##### Swagger declaration file content or url

Here is a simplified code to reproduce the issue:
```yaml
definitions:
  Order:
    type: "object"
    required:
      - id
    properties:
      id:
        type: "string"
        enum:
          - Value
```

##### Command line used for generation

java -jar modules\swagger-codegen-cli\target\swagger-codegen-cli.jar generate -i c:\temp\cs_warning.yaml -l csharp -o c:\temp\out

##### Steps to reproduce

Generate C# code with the above yaml code and compile the generated code.
