### ISSUE TITLE
[JAVA] Collection attribute serialized as 'csv' in generated client - style: form, explode: true

### ISSUE THREAD

**Issue by vsvetoslavov** [swagger-api/swagger-codegen#8729]
##### Description

I have a REST service where one of my methods has a List<String> query parameter, which is described with style = "form"(also default value).
Checking the OpenAPI spec [here](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md) I see that by default query parameters have `form` style and for that the default for `explode` is true.
Also spec states that:

> Form style parameters defined by RFC6570. This option replaces collectionFormat with a csv (when explode is false) or multi (when explode is true) value from OpenAPI 2.0.

After generating a Java client, I noticed the following inside the generated DefaultApi.java file:
```java
        if (keywords != null)
        localVarCollectionQueryParams.addAll(apiClient.parameterToPairs("csv", "keywords", keywords));
```
My understanding is that in this situation the conversion type should be "multi", not "csv". 

Another interesting thing is that when converting parameters to CSV, the commas are not escaped, so
an array of "one", "two", "I, Caesar" is converted to "one,two,I Caesar" which is wrong.

##### Swagger-codegen version
swagger-codegen-cli 3.0.0-SNAPSHOT

##### Swagger declaration file content or url

```yaml
  /dv/any:
    get:
      description: Search for records that match one or more of the provided keyword(s). Reason and operator must be provided.
      operationId: searchAny
      parameters:
        - name: keywords
          in: query
          required: true
          style: form
          schema:
            type: array
            items:
              type: string
```

##### Command line used for generation

java -jar swagger-codegen-cli.jar generate -i /home/vsvetoslavov/tmp/datavault-openapi.yaml -o /home/vsvetoslavov/tmp/dv-local-3/ -l java

##### Steps to reproduce

1. Have a REST service with a GET method that has an array[Stirng] parameter in QUERY part. (My service is on WildFly, using JAX-RS annotations and Swagger annotations).
2. Generate a client for that service
3. Use the client in another app to invoke the service
4. The array values are received by the REST service as a single CSV string and commas in values have not been escaped.

##### Suggest a fix/enhancement
Use "multi" for arrays in query, that have form style and explode is true.
