### ISSUE TITLE
[RESOLVED YAML] Generated resolved YAML contains unknown properties for model

### ISSUE THREAD

**Issue by michaelmelodysmartbear** [swagger-api/swagger-codegen#8800]
##### Description

I had the following subsection of a model defined in a swagger 2.0 spec.

```
ClosureResponse:
    description: Contains values calculated over Term Deposit early termination (closure) request.
    properties:
      interestAfterReduction:
        type: number
      marginAfterReduction:
        type: number
        description: The margin after reduction that bank is liable to pay by close date.
```

When generating a yaml resolved spec, the following example properties are generated along with the model:

```
    example:
      interestAfterReduction: 6.02745618307040320615897144307382404804229736328125
      marginAfterReduction: 1.46581298050294517310021547018550336360931396484375
```

##### Swagger-codegen version

3.0.1
