### ISSUE TITLE
[typescript-angular] error TS1345: An expression of type 'void' cannot be tested for truthiness

### ISSUE THREAD

**Issue by itsTeknas** [swagger-api/swagger-codegen#8836]
##### Description

The generated typescript client fails in angular 7 build when there seems to be any sort of file field.

Typescript version 

"typescript": "^3.1.3"

##### Swagger-codegen version

The latest online version

##### Swagger declaration file content or url

```yaml
parameters:
        - name: attachment1
          type: file
          in: formData
          required: false
```

Produces:

```
if (attachment1 !== undefined) {
            formParams = formParams.append('attachment1', <any>attachment1) || formParams;
}
```

The definition of append tracks down to 

```
let formParams: { append(param: string, value: any): void; };
```

<img width="654" alt="screenshot 2018-10-22 at 2 13 46 pm" src="https://user-images.githubusercontent.com/6565602/47284378-c2ba4280-d604-11e8-8b45-bbe369b6d0ad.png">

##### Steps to reproduce

Generate a new client with angular-typescript selected.
