### ISSUE TITLE
Swift4: Add additional initializer for initializing model object with *only* required properties

### ISSUE THREAD

**Issue by nashish** [swagger-api/swagger-codegen#8852]
##### Description

In a previous feature, you added init() methods that include all properties declared in the schema. My request is to provide an option for an init() method with *only* the required properties from the schema.

##### Swagger-codegen version

3.0.2

##### Swagger declaration file content or url

```yaml
Foo:
      required:
      - id
      properties:
        id:  # the init() function would only have this property 
          type: string
        color:
          type: string
```

##### Related issues/PRs

https://github.com/swagger-api/swagger-codegen/issues/6641
