### ISSUE TITLE
[Rust] Generated models compiler warnings

### ISSUE THREAD

**Issue by destruktiw** [swagger-api/swagger-codegen#8929]
##### Description

I encountered two issues with rust generator ('rust' one, not 'rust-server'). I generated models for [Docker API](https://github.com/moby/moby/tree/master/api).

Problems:
1. Uppercase fields and variables:
```yaml
BuildCache:
    type: "object"
    properties:
      ID:
        type: "string"
    ...
```
gives
```rust
#[derive(Debug, Serialize, Deserialize)]
pub struct BuildCache {
    #[serde(rename = "ID")]
    ID: Option<String>,
    ...
}
```
getters, setters etc. of this field also have uppercase ID. It results with many compiler warnings.

2. Double underscore.
```yaml
LogConfig:
  type: "object"
  description: "The logging configuration for this container"
  properties:
    Type:
      type: "string"
      enum:
        - "json-file"
        - "syslog"
        - "journald"
        - "gelf"
        ...
```
produces
```rust
#[derive(Debug, Serialize, Deserialize)]
pub struct HostConfigLogConfig {
    #[serde(rename = "Type")]
    _type: Option<String>,
    ...
}
```
Problem is that names for `_type` methods have incorrect names for rust: `set__type`, `get__type`. Maybe it should be `_set_type` insted.

##### Swagger-codegen version

2.3.1
