### ISSUE TITLE
[JAVA] Codegen for multi server

### ISSUE THREAD

**Issue by Ale92b** [swagger-api/swagger-codegen#8944]
##### Description

I want to generate a client for a yaml that handle different server urls depending on where I want to test. My client only gets the first url from the yaml. Is there a way to say what url is used for this client. Maybe to insert in the bash call?

##### Swagger-codegen version

swagger-codegen-cli-3.0.3-20181125.212437-36.jar

##### Swagger declaration file content or url

```yaml
servers:
  - url: 'https://staging.jaxx.com/api/jpf'
    description: Staging system
  - url: 'https://dev.jackpot-freunde.de/api/jpf'
    description: Dev system
```
  -->

##### Command line used for generation

java -jar swagger-codegen-cli-3.jar generate -i api.yaml -l java -o api-client --group-id de.api --artifact-id api-client --git-repo-id api 

##### Steps to reproduce

Add second server url and generate code
