### ISSUE TITLE
[CPPREST] default values unused

### ISSUE THREAD

**Issue by mathieu** [swagger-api/swagger-codegen#8960]
##### Description

Default values are unused in the generated classes constructors.

##### Swagger-codegen version

2.3.1

##### Swagger declaration file content

```yaml
definitions:
  MyData:
    required:
      - name
      - status
    properties:
      name:
        type: string
        default: 'unset'
      status:
        type: boolean
        default: true
```

will generate this code : 
```cpp
MyData:: MyData()
{
    m_ name = utility::conversions::to_string_t("");
    m_ status = false;
}
```

while I would like it to be:
```cpp
MyData:: MyData()
{
    m_ name = utility::conversions::to_string_t("unset");
    m_ status = true;
}
```
##### Suggest a fix/enhancement

I've got a fix that I'll submit as a PR to this issue
