### ISSUE TITLE
[JAVA] Generated code contains value which is expressed as integer but is too large for integer.

### ISSUE THREAD

**Issue by cpo** [swagger-api/swagger-codegen#8967]
##### Description

We use a swagger file which contains the following field definition:

```yaml
          number:
            type: integer
            description: >-
              The unique identification of an action discount for an insurance
              policy.
            maximum: 1e+10
            minimum: 0
            exclusiveMaximum: true
```

The java file generated contains this code:

```java
@Min(0) @Max(10000000000) 
  public Long getNumber() {
    return number;
  }
```
The java compiler complains about the value `10000000000` because it is too big to be expressed as an integer. 

The code generation should generate `10000000000L` instead.

##### Swagger-codegen version

2.3.1

##### Swagger declaration file content or url

See description.

##### Command line used for generation

Generated from Maven:

```
                    <execution>
                        <id>generate-model</id>
                        <phase>generate-test-sources</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>src/main/resources/swagger/swagger.yaml</inputSpec>
                            <apiPackage>nl.xxx.gen.yyy.api</apiPackage>
                            <modelPackage>nl.xxx.gen.yyy.model</modelPackage>
                            <generateApis>false</generateApis>
                            <language>spring</language>
                            <configOptions>
                                <dateLibrary>java8</dateLibrary>
                                <interfaceOnly>true</interfaceOnly>
                            </configOptions>
                            <library>spring-mvc</library>
                        </configuration>
                    </execution>
```

##### Steps to reproduce

Use this field in swagger definition:
```yaml
          number:
            type: integer
            description: >-
              The unique identification of an action discount for an insurance
              policy.
            maximum: 1e+10
            minimum: 0
            exclusiveMaximum: true
```

Generate the model using this maven configuration:

```
                    <execution>
                        <id>generate-model</id>
                        <phase>generate-test-sources</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>src/main/resources/swagger/swagger.yaml</inputSpec>
                            <apiPackage>nl.xxx.gen.yyy.api</apiPackage>
                            <modelPackage>nl.xxx.gen.yyy.model</modelPackage>
                            <generateApis>false</generateApis>
                            <language>spring</language>
                            <configOptions>
                                <dateLibrary>java8</dateLibrary>
                                <interfaceOnly>true</interfaceOnly>
                            </configOptions>
                            <library>spring-mvc</library>
                        </configuration>
                    </execution>
```

##### Related issues/PRs

-

##### Suggest a fix/enhancement

When the underlying data type is `Long`, always generate the validation rules using the "L suffix" notation for java.

E.g: not `10000000000000` but `10000000000000L`
