### ISSUE TITLE
Wrong parameter and method names generated for single quoted properties containing @ sign

### ISSUE THREAD

**Issue by jgrabowski** [swagger-api/swagger-codegen#9001]
##### Description
Codegen on swaggerhub generates Jersey and Resteasy code that doesn't compile when properties contain '@' sign.
Codegen generates improper Java fields. Eg. for '@baseType' swagger property definition there is @BaseType field name generated, and also getter/setter names are broken.

##### Swagger declaration file content or url

I came across this issue while trying to implement TMF 655 Swagger API: https://raw.githubusercontent.com/tmforum-apis/TMF655_ChangeManagement/master/Change_Management.admin.swagger.json.

```yaml
properties:
   '@baseType':
          type: string
          default: 'Attachment'
          description: The base type for use in polymorphic collections
```

##### Command line used for generation

Not applicable. I was using online codegen from swagger.io. I'll make tests on "standalone" version soon.

##### Steps to reproduce

Export -> Server stub -> jaxrs-jersey or jaxrs-resteasy

##### Suggest a fix/enhancement

Codegen should "sanitize" such property names and exclude not allowed chars from field and getter/setter names. @JsonProperty annotation should be sufficient to reflect swagger contract for such properties.
I'll try to make a fix in codegen and post my solution soon.
