### ISSUE TITLE
[Typescript][AngularJS] Enum creates invalid method header

### ISSUE THREAD

**Issue by julianuphoff** [swagger-api/swagger-codegen#9043]
##### Description

I've created a POST method with the following parameter and generated the typescript-angularjs client via editor.swagger.io

```
parameters:
        - in: query
          name: foo
          enum:
            - 'test'
            - 'hallo'
          description: image
          required: true
          type: string
```

The resulting method header in typescript is invalid:

```
public test (foo: models.'test' | 'hallo', extraHttpRequestParams?: any ) : ng.IHttpPromise<string> {
...
}
```

##### Swagger-codegen version

editor.swagger.io

##### Swagger declaration file content or url

```
parameters:
        - in: query
          name: foo
          enum:
            - 'test'
            - 'hallo'
          description: image
          required: true
          type: string
```
##### Command line used for generation

editor.swagger.io

##### Steps to reproduce

- create a method with an enum parameter
- generate typescript-angularjs client

##### Suggest a fix/enhancement
The generated method header should look like this:
```
public test (foo: 'test' | 'hallo', extraHttpRequestParams?: any ) : ng.IHttpPromise<string> {
...
}
```
