### ISSUE TITLE
[Swift4] Schema with inner objects with required properties are marked optional

### ISSUE THREAD

**Issue by thomasjoulin** [swagger-api/swagger-codegen#9106]
##### Description

See examples below

##### Swagger-codegen version

3.0.3

##### Swagger declaration file content or url

```yaml
    Person:
      required:
        - name
      type: object
      properties: 
        name:
          type: object
          required:
            - first
            - last
          properties:
            first: 
              type: string
            last:
              type: string
```

Generates:

```swift
public struct Person: Codable {


    public var name: PersonName
    public init(name: PersonName) { 
        self.name = name
    }

}

public struct PersonName: Codable {


    public var first: String?

    public var last: String?
    public init(first: String?, last: String?) { 
        self.first = first
        self.last = last
    }

}
```

It's unexpected that first and last name are optional since they are marked required. On the other hand, using refs it works:

```yaml
    Person:
      required:
        - name
      type: object
      properties: 
        name:
          $ref: '#/components/schemas/Name'
    Name:
      required:
        - first
        - last
      type: object
      properties:
        first: 
          type: string
        last:
          type: string
```

Generates:

```swift
public struct Person: Codable {


    public var name: Name
    public init(name: Name) { 
        self.name = name
    }

}

public struct Name: Codable {


    public var first: String

    public var last: String
    public init(first: String, last: String) { 
        self.first = first
        self.last = last
    }

}
```

##### Command line used for generation

```bash
swagger-codegen generate -i test.yaml -l swift4 -Dmodels
```
