### ISSUE TITLE
[Javascript] codegen produces broken models for types inherited from primitive

### ISSUE THREAD

**Issue by fed239** [swagger-api/swagger-codegen#9113]
##### Description

Javascript codegen produces broken models (not using data at all) for types inherited from primitive types like the following.

##### Swagger-codegen version

Tested with 2.4.1 and 2.3.1, not a regression

##### Swagger declaration file content or url

```yaml
  ResourceId:
    description: Identifier assigned for further use of the created resource through API calls
    type: string
    pattern: '^([a-zA-Z0-9 /\-?:\()\.,'']{1,35})$'
    readOnly: true
```

##### Related issues/PRs

https://github.com/swagger-api/swagger-codegen/pull/9112

##### Suggest a fix/enhancement

Checking if parent type is primitive
