### ISSUE TITLE
[PHP] [SymfonyServerCodegen] Bug: Validator ignore all annotation-asserts for Models

### ISSUE THREAD

**Issue by 4n70w4** [swagger-api/swagger-codegen#9122]
##### Description

subj.

##### Swagger-codegen version

2.4.1

##### Swagger declaration file content or url

```
definitions:

  FiltersRow:
    type: object
    properties:
      script:
        type: string
      arguments:
        type: string
        pattern: '^[a-z0-9-_ ]*$'
```

```
class FiltersRow 
{

    /**
     * @var string|null
     * @SerializedName("arguments")
     * @Assert\Type("string")
     * @Type("string")
     * @Assert\Regex("/^[a-z0-9-_ ]*$/")
     */
    protected $arguments;
```

But all @Assert\* skipping because validator configured without AnnotationMapping and pass overwrited $asserts array to `$this->validate()` in controller.

##### Suggest a fix/enhancement

For enable validator annotation-asserts need:

1) replace in php-symfony/validation/SymfonyValidator.mustache

from `$this->validator = Validation::createValidator();`
to: `$this->validator = (new ValidatorBuilder())->enableAnnotationMapping()->getValidator();`

2) in php-symfony/api_input_validation.mustache need dont generate $asserts array and dont pass $asserts to `$response = $this->validate(${{paramName}});` for models with annotaions-asserts only.

Maybe there is a more correct way. I do not know.
