### ISSUE TITLE
Codegen is merging nested models

### ISSUE THREAD

**Issue by leonshaw** [swagger-api/swagger-codegen#9186]
##### Description

When multiple nested models have identical contents, codegen automatically merges them and generates only one model. This is not expected because these models are unrelated. Need an option to disable merging.

##### Swagger-codegen version

2.4.1

##### Swagger declaration file content or url

```yaml
definitions:
  outer1:
    type: object
    properties:
      inner1:
        type: object
        properties:
          foo:
            type: string
  outer2:
    type: object
    properties:
      inner2:
        type: object
        properties:
          foo:
            type: string
```

##### Command line used for generation

`java -jar swagger-codegen-cli-2.4.1.jar generate -i api.yaml -l jaxrs-spec`

##### Steps to reproduce

Just generate code. Inner1 is generated as `Outer1Inner1`, but inner2 is not being generated. `Outer2` now has a field `Outer1Inner1 inner2`, which is not expected.
It's not language-specific.
