### ISSUE TITLE
[spring] @RequestPart should use "{{basename}}" instead of "file" and observe "required" attribute

### ISSUE THREAD

**Issue by 6d77** [swagger-api/swagger-codegen#9250]
##### Description

When generating a spring-boot server for a POST processing multipart form data to upload one or several files, then the generated @RequestPart annotation always uses the fixed string "file" instead of the name of the part. Additionally, the required attribute is not considerd when building the @RequestPart annotation, so that file upload parameters are always required even if not defined to be so in the Swagger yaml file.

##### Swagger-codegen version

swagger-codegen-cli-2.4.2.jar

##### Swagger declaration file content or url

If you post the code inline, please wrap it with
```yaml
  /kpack/jsonld:
    post:
      operationId: "uploadJsonld"
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - name: jsonld
          in: formData
          type: file
          description: "JSON-LD graph file"
          required: true
```

##### Command line used for generation

```bash
java -jar ./swagger-codegen-cli.jar generate \
	-i api.yaml \
	-l spring 
```

##### Steps to reproduce

Create code with command given above. Check generated Api and Controller.

##### Suggest a fix/enhancement

In https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/JavaSpring/formParams.mustache change the fixed "file" and replace it by "{{basename}}". Additionally fill the "required" attribute of this annotation.
