### ISSUE TITLE
[Javascript] File is not uploaded.

### ISSUE THREAD

**Issue by NullP0interEx** [swagger-api/swagger-codegen#9253]
##### Description

The request is not executed correctly. The file will not be uploaded. The parameter "file" is just the file name, instead of the binary data.

##### Swagger-codegen version

openapi-generator-cli-3.3.4.jar

##### Swagger declaration file content or url

Swagger .yaml:

```yaml
  /orders/upload:
    post:
      operationId: "orderUploadPart"
      summary: "upload a textual or audio part of an order"
      tags:
        - "orders"
      description: "This funktion uploads a textual or audio part of an order to the sense.ai.tion cloud system. 
      The result is the resource identifier, that must be used in the order request."
      consumes:
        - multipart/form-data
      parameters:
        - in: "formData"
          name: "file"
          type: "file"
          required: true
          description: "the file to upload"
        - in: "formData"
          name: "media"
          type: "string"
          enum:
            - "text"
            - "wav"
            - "mp3"
          required: true
          description: "the media type of the the upload, can be ***text***, ***wav*** or ***mp3***"
```
Code:

`var apiInstance = new SenseaitionApi.OrdersApi();
var file = "/path/to/file"; // File | the file to upload
var media = "media_example"; // String | the media type of the the upload, can be ***text***, ***wav*** or ***mp3***
var callback = function(error, data, response) {
  if (error) {
    console.error(error);
  } else {
    console.log('API called successfully. Returned data: ' + data);
  }
};
apiInstance.orderUploadPart(file, media, callback);
`

![image](https://user-images.githubusercontent.com/8757449/54109749-d3b2f700-43df-11e9-877d-1a3a0c656894.png)

##### Command line used for generation

`java -jar ${GOPATH}/bin/openapi-generator-cli.jar generate -i service_js_api.yaml -g javascript -o clients/javascript/senseaition-api-js -Dio.swagger.parser.util.RemoteUrl.trustAll=true`

##### Steps to reproduce

just run sample code
