### ISSUE TITLE
[RUST] Add support for HTTPS

### ISSUE THREAD

**Issue by brycefisher** [swagger-api/swagger-codegen#9277]
##### Description

Currently, the Rust client code generated will reject any REST endpoint using the "https" scheme. 

Its very difficult to figure out how to support HTTPS / TLS using an older version of hyper used by swagger-codegen (0.11.27). The current version of hyper is 0.12.x (this was a major breaking change). 

##### Swagger-codegen version

Swagger editor at https://editor.swagger.io/

##### Swagger declaration file content or url

Petstore yaml

##### Command line used for generation

Rust Client

##### Steps to reproduce

Try to use the generated rust client. Minimal code sample:

```toml
# Cargo.toml
[package]
name = "swagger_demo"
version = "0.1.0"
authors = ["Bryce Fisher-Fleig <email@domain.com>"]
edition = "2018"

[dependencies]
futures = "0.1.25"
hyper = { version = "0.11.27" }
swagger = { path = "../swagger" }
tokio-core = { version = "0.1.17" }
```

```rs
// src/main.rs
use futures::future::Future;
use hyper::client::Client;
use swagger::apis::{
    configuration::Configuration,
    client::APIClient,
    Error,
    PetApi
};
use tokio_core::reactor::Core;

fn main() {
    let core = Core::new().unwrap();
    let handle = core.handle();
    let mut client = Client::new(&handle);
    let mut c = Configuration::new(client);

    // Use anything with HTTPS
    c.base_path = "https://localhost/api".into();

    let api_client = APIClient::new(c);
    let pet_client = api_client.pet_api();
    let result = pet_client.get_pet_by_id(1i64).wait();
    match result {
        Err(Error::Hyper(err)) => println!("Hyper Error: {:?}", err.description()),
        Err(Error::Serde(err)) => println!("Serde Error: {:?}", err.description()),
        Err(Error::ApiError(err)) => println!("Api Error: {:?}", err),
       _ => println!("Something else"),
    };
}
```

Running this code via `cargo run` results in the following output:

> "Hyper Error: invalid URL, scheme must be http"

##### Related issues/PRs

https://github.com/swagger-api/swagger-codegen/issues/6250 -- the first bullet of including usage documentation

##### Suggest a fix/enhancement

I can tink of two possible paths forward:

 1. Document _how_ to make TLS work somewhere in the generated output
 2. Upgrade to use a more recent version of hyper
