### ISSUE TITLE
[Kotlin] Swagger date type mapped to localdatetime instead of localdate

### ISSUE THREAD

**Issue by jkgentry** [swagger-api/swagger-codegen#9285]
##### Swagger-codegen version
3.0.5 

##### Swagger declaration file content or url
Example
```yaml
              presentation_start_date:
                type: string
                format: date
```

Configuration
```
{
  "dateLibrary":"java8",
  "sourceFolder": "build/generated/swagger/",
  "enumPropertyNaming": "UPPERCASE"
}
```
##### Steps to reproduce

Generate code
```
java -Dmodels -DmodelDocs=false -Dio.swagger.parser.util.RemoteUrl.trustAll=true -jar swagger-codegen-cli-3.0.5.jar \
-i  ./contract.yml \
-l kotlin-client \
-c $kotlin_config_loc \
--model-package com.something
```
Get this
```
    val presentationStartDate: java.time.LocalDateTime? = null`
```
