### ISSUE TITLE
[CSharp] Spaces in enum generates uncompilable code

### ISSUE THREAD

**Issue by dbowles** [swagger-api/swagger-codegen#9357]
##### Description

If there is an enum, with a value of ' ' (SPACE), then the resulting C# code is invalid and doesn't build

The invalid code looks like

/// <summary>
/// Enum  for value:  
/// </summary>
[EnumMember(Value = " ")]
 = 1,

##### Swagger-codegen version

2.4.5-SNAPSHOT

##### Swagger declaration file content or url
```yaml
      SomeType:
        type: string
        description: |
          Some Type
          > Possible values include:
            * Y - Yes
            * N - No
            * Space - Not Supplied
        enum:
          - Y
          - N
          - ' '
```
##### Command line used for generation

java -jar .\swagger-codegen-cli.jar generate -i .\MySample.yaml -l csharp

##### Steps to reproduce

Define an enum with a value of ' '

##### Related issues/PRs

I looked through issues, but didn't spot this being previously reported

##### Suggest a fix/enhancement

io.swagger.codegen.languages.CSharpClientCodegen#toEnumVarName

    @Override
    public String toEnumVarName(String value, String datatype) {
        if (value.length() == 0) {
            return "Empty";
        }

// New code added to return a constant that isn't whitespace
        if (value.trim().length() == 0)
        {
            return "SPACE";
        }
...

This then produces code that can be compiled, example

/// <summary>
/// Enum SPACE for value:  
/// </summary>
[EnumMember(Value = " ")]
SPACE = 1,
