### ISSUE TITLE
Integer Enum in Array is not generated correctly in 3.0.7

### ISSUE THREAD

**Issue by tsiukaris** [swagger-api/swagger-codegen#9358]
There was very similar issue with generating Array of STRING Enums:
https://github.com/swagger-api/swagger-codegen/issues/7377

In 3.0.7 Swagger-Codegen version with 1.0.7 Swagger-Codegen-Generators the List<CustomEnum> is generated correctly for String type of Enum, but not for Integer type.
If I specify type of enum "integer", the enum values generated in Java Class still are generated as  String values. See below
If I specify enum in yaml:
```
TbProductFilter:
  type: object
  properties:
    productType:
      type: array
      items:
        type: integer
        enum:
          - 0
          - 1
          - 2
          - 3
```
Enum in Java Class:
```
public enum ProductTypeEnum {
    _0("0"),
    
    _1("1"),
    
    _2("2"),
    
    _3("3");

    private Integer value;

    ProductTypeEnum(Integer value) {
      this.value = value;
    }

    @Override
    @JsonValue
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ProductTypeEnum fromValue(String text) {
      for (ProductTypeEnum b : ProductTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }
  @JsonProperty("productType")
  @Valid
  private List<ProductTypeEnum> productType = null;
```

And ofcourse the code doesn't compile - values are strings, but everywhere else Integers are expected.
