### ISSUE TITLE
[Scala] error: type Map takes type parameters

### ISSUE THREAD

**Issue by hotdog929** [swagger-api/swagger-codegen#938]
```
  schema:
    type: object
    additionalProperties:
      type: object
      additionalProperties:
        type: string
```

https://github.com/swagger-api/swagger-codegen/blob/develop_2.0/modules/swagger-codegen/src/main/resources/scala/api.mustache#L81

```
[ERROR]            Some(ApiInvoker.deserialize(s, "map", classOf[Map]).asInstanceOf[Map[String, Map[String, String]]])
[ERROR]                                                          ^
```
