### ISSUE TITLE
[JAVA][RxJava][Retrofit2] Query parameters are generated as path parameters

### ISSUE THREAD

**Issue by Wrakor** [swagger-api/swagger-codegen#9419]
##### Description

The Java code generator is generating Query parameters as if they were path parameters.

##### Swagger-codegen version
3.0.8

##### Swagger declaration file content or url

```yaml
/Reference/Countries:
    get:
      tags:
        - Reference
      description: 'TODO: Add Description'
      operationId: CountryDialingCodesGet
      parameters:
        - name: CountryCode
          in: query
          description: ''
          required: false
          style: form
          explode: true
          schema:
            type: string
        - name: CountryName
          in: query
          description: ''
          required: false
          style: form
          explode: true
          schema:
            type: string
```

##### Command line used for generation
java -jar swagger-codegen-cli-3.0.8.jar generate  -i "custom.json" -l java  -o samples/client/java --library retrofit2 -c "swagger_rxjava_config.json"

With the config being:
```json
{
  "library": "retrofit2",
  "artifactId": "swagger-petstore-retrofit2-rx2",
  "useRxJava": true,
  "hideGenerationTimestamp": true
}
```

And this is the generated code:
```java
public interface ReferenceApi {
  /**
   * 
   * TODO: Add Description
   * @param countryCode  (optional)
   * @param countryName  (optional)
   * @return Call&lt;CountryDialingCodes&gt;
   */
  @GET("Reference/Countries")
  Observable<CountryDialingCodes> countryDialingCodesGet(
          @Path("CountryCode") String countryCode, @Path("CountryName") String countryName
  );
}
```

##### Suggest a fix/enhancement

The generated code should have 
```java 
@Query
```
 instead of 
```java
@Path
```
