### ISSUE TITLE
[html2] generated api documentation section headers are white on white on mouseover

### ISSUE THREAD

**Issue by joshdutcher** [swagger-api/swagger-codegen#9454]
##### Description

The html2 documentation generated by codegen creates navigation section headers ("API SUMMARY", "API METHODS - DEFAULT", etc) which, on mouseover, become white text on a white background.

##### Swagger-codegen version

3.0.8

##### Swagger declaration file content or url

N/A - using api.swaggerhub.com

##### Command line used for generation

N/A - using api.swaggerhub.com

##### Steps to reproduce

1. Create a valid OAS API in SwaggerHub online
1. Download autogenerated documentation by clicking `Export > Documentation > html2`
1. Open the resulting `index.html` file in a browser
1. Note the navigation section headers in the upper left (white text on blue background)
1. Hover over them with the mouse
1. Note the css :hover effect: background turns white, but text remains white and so disappears

##### Related issues/PRs

None found

##### Suggest a fix/enhancement

In [styles.mustache](https://github.com/swagger-api/swagger-codegen/blob/dedb5ce36d54495365da9a7d88d1e6e056cfe29f/modules/swagger-codegen/src/main/resources/htmlDocs2/styles.mustache#L301), after

```css
  .sidenav > li > a:hover {
    background-color: #ffffff;
  }
```
(around line 304), a class could be added as follows:
```css
  .sidenav > li.nav-header > a:hover {
    color: #4c8eca;
  }
```
