### ISSUE TITLE
[Java] Validations missing on method parameters

### ISSUE THREAD

**Issue by vojtech-sefler** [swagger-api/swagger-codegen#9506]
##### Description
When specifying constraints (minLength, minItems) on method parameters, annotation validations are missing in generated .java interface. Validations are generated only for model objects.

##### Swagger-codegen version
1.0.11

##### Swagger declaration file content or url
```yaml
/foo:
  get:
    parameters:
      - name: id
        in: query
        required: true
        type: array
        minItems: 1
        items:
          type: string
          minLength: 1
      - name: description
        in: query
        required: true
        type: string
        minLength: 1
```

##### Command line used for generation
`java  -Dgenerator.dir.data=${WORKSPACE}  -Dstub.for=server -jar swagger-gen.jar`

##### Steps to reproduce
- create yaml swagger definition with above mentioned operation
- generate java interface with 1.0.11 swagger-gen

##### Related issues/PRs
none

##### Suggest a fix/enhancement
There should be the same validation generation as with model objects (@Size and @Notnull annotations).
