### ISSUE TITLE
custom property attribute

### ISSUE THREAD

**Issue by oleksabor** [swagger-api/swagger-codegen#9508]
Please help me with a question about source code generation.

##### Description

I have custom attribute implemented in my source code, like `LostAttribute`. I'd like to add this custom attribute on the object property using the swagger generator. Is it possible?
May be using the [specificationExtensions](https://swagger.io/specification/#specificationExtensions). Is there a way to achieve this for codegen ? 

For example, using something like `x-attribute` (whatever) to ask codegen to mark `ErrorDetails.Message` property with `Lost` attribute

##### Swagger declaration file content or url

I'd like to get from the definition like below
```yaml
  ErrorDetails:
    type: object
      Message:
        type: string
        x-attribute: Lost
```

result to be like
````CSharp
public class ErrorDetails
{
    [Lost]
    public string Message { get; set; }
}
````

Is there any possibility to get it? Like with codegen addon whatever?
