### ISSUE TITLE
[JAVA] Refs with depth greater than 2 are not resolved properly

### ISSUE THREAD

**Issue by upcFrost** [swagger-api/swagger-codegen#9547]
##### Description

Refs having file depth greater than 2 are not resolved properly.

##### Swagger-codegen version

2.4.6

##### Swagger declaration file content or url
First file (test.yaml)
```yaml
definitions:
  test:
    type: 'object'
    properties:
      test:
        $ref: 'test2.yaml#/definitions/MyTestCluster'
```

Second file (test2.yaml)
```yaml
definitions:
  MyTestCluster:
    $ref: 'test3.yaml#/definitions/my.test.Cluster'
```

Third file (test3.yaml)
```yaml
definitions:
  my.test.Cluster:
      type: 'object'
      properties:
        value:
          type: 'integer'
          format: 'int64'
```

##### Command line used for generation

```java -jar swagger-codegen-cli.jar generate -l java -i test.yaml -o out/```

##### Steps to reproduce

Create 3 files with refs chaining from the first file to the third and try to generate java code.

##### Suggest a fix/enhancement

Will try to debug, for now it look like there's a problem in DefinitionsProcessor.processDefinitions method.

**Comment by upcFrost** [comment]
There's one more thing about deep refs. though I'm struggling to make a simple example out of it.

Given 4 different files, if property gets linked from more than one file there's a chance it'll have its name duplicated, like `MyString_2`. And this duplicate will be empty,

As cheap and dirty fix it can be solved by adding one more condition into `ExternalRefProcessor.processRefToExternalDefinition`

```java
            if(existingModel instanceof RefModel) {
                // use the new model
                existingModel = null;
            }else if (model instanceof RefModel
                    && resolutionCache.get(((RefModel) model).get$ref()) == existingModel) {
                // Use existing model
            } else {
                //We add a number at the end of the definition name
           ....
```

The problem occurs when the model found is a previously unknown ref (with its base file different from any other ref)

Here's the best example i've managed to come up with

`test.yaml`
```yaml
definitions:
  test:
    $ref: 'test2.yaml#/definitions/MyTestCluster'
  my.test.Cluster:
    type: 'integer'
    format: 'int64'
```

`test2.yaml`
```yaml
definitions:
  MyTestCluster:
          $ref: 'test.yaml#/definitions/my.test.Cluster'
```

The error will refer the class called `my.test.Cluster_2`, though it's pretty obvious there should be no `_2`
