### ISSUE TITLE
[aspnetcore] exampleJson invalid template generation of \\" for array of strings

### ISSUE THREAD

**Issue by copperorange** [swagger-api/swagger-codegen#9581]
##### Description

When generating aspnetcore server code, the controller template for exampleJson renders incorrect escaped output. Double Backslash followed by quote which breaks the build. It seems to be when inside an array and where the values are string not integer.

exampleJson = .... Shortened

`\"metadata\" : [ [ {\n      \"values\" : [ \"[\\"Value 1\\",\\"Value 2\\",\\"Value 3\\"]\", \"[\\"Value 1\\",\\"Value 2\\",\\"Value 3\\"]\" ],\n      \"key\" : \"Key 1\"\n    },`

note the \\"

##### Swagger-codegen version

3.0.10

##### Swagger declaration file content or url

```yaml
MetaData:
      type: object
      properties:
        key:
          type: string
          example: Key 1
        values:
          type: array
          items:
            type: string
            example: 
              - Value 1
              - Value 2
              - Value 3
```

##### Command line used for generation

swagger-codegen generate \
     -i ./conferences.yaml \
     -l aspnetcore \
     --aspnet-core-version 2.2 \
     --interface-controller \
     -c config.json \
     -o ../

##### Steps to reproduce

- run command
- examine output
- look at incorrect quotes
- note - it only seems to be with strings in arrays of this pattern

##### Related issues/PRs

Similar template issues but not exact

##### Suggest a fix/enhancement

Looked at AbstractCSharpCodegen.java as possible candidate but wanted to check if there is an obvious reason first. 

`if (operation.examples != null){
                        for (Map<String, String> example : operation.examples)
                        {
                            for (Map.Entry<String, String> entry : example.entrySet())
                            {
                                // Replace " with \", \r, \n with \\r, \\n
                                String val = entry.getValue().replace("\"", "\\\"")
                                    .replace("\r","\\r")
                                    .replace("\n","\\n");
                                entry.setValue(val);
                            }
                        }
                    }`
