### ISSUE TITLE
Use Arrays.equal in spring java pojo generation.

### ISSUE THREAD

**Issue by Wandakin** [swagger-api/swagger-codegen#9625]
##### Description
Sping Java bug generating equals method when there is an Array property
The pojo.mustache template in the equals method always uses Objects.equal
When dealing with an array property, as generated by  "type: string format: byte", Arrays.equal should be used instead.
##### Swagger-codegen version
swagger-codegen-cli 2.4.5

##### Swagger declaration file content or url

```yaml
ImageData:
  type: object
  properties:
    data:
      description: BASE 64 file data
      type: string
      format: byte
```
##### Command line used for generation
maven openapi-generator-maven-plugin
