### ISSUE TITLE
Custom function property for security scheme is ignored

### ISSUE THREAD

**Issue by bpmcl** [swagger-api/swagger-codegen#9651]
When writing a definition file to convert, I want to be able to specify the function called when a bearer token is passed. To do this, I provide the `x-bearerInfoFunc` property in the security scheme. However, after generating the `swagger.yaml`, this property is ignored and the default function name is inserted instead.

Swagger-codegen version: 3.0.10

Here is the definition I am providing:
```yaml
...
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      x-bearerInfoFunc: <module path>.my_controller.my_function_name
...
```

And this is how it is rendered in `swagger.yaml`:
```yaml
...
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      x-bearerInfoFunc: <module path>.authorization_controller.check_bearerAuth
...
```

Command line used for generation:
`java -jar swagger-codegen-cli-3.0.10.jar generate -i ./<module path>/swagger/definitions.yaml -l python-flask -o python-flask-server`

Is this a bug/oversight, or is there a reason why this property is ignored?
