### ISSUE TITLE
[Python] Generated incomplete models for schema that has arrays

### ISSUE THREAD

**Issue by mandeepsandhu** [swagger-api/swagger-codegen#9664]
##### Description

When using python-flask, models generated for schema definitions which have arrays types, have _possibly_ incomplete model classes.

Eg, a schema defined as:
```yaml
  schemas:
    testresponse:
      type: array
      items:
        type: string
```
produces a python model class without `self.swagger_types` & `self.attribute_map` set:
```python
class Testresponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self):  # noqa: E501
        """Testresponse - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'Testresponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The testresponse of this Testresponse.  # noqa: E501
        :rtype: Testresponse
        """
        return util.deserialize_model(dikt, cls)
```

##### Swagger-codegen version

`3.0.10`

##### Swagger declaration file content or url

```yaml
openapi: '3.0.0'
info:
  version: '1.0.0'
  title: 'Test AWS API Gateway'
 
servers:
  - url: https://example.mydomain.com/v1
paths:
  /test:
    get:
      summary: Returns test data
      operationId: getTestData
      responses:
        '200':
          description: Returns test data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/testresponse'
components:
  schemas:
    testresponse:
      type: array
      items:
        type: string
```

##### Command line used for generation

```bash
java -jar swagger-codegen-cli.jar generate -i test.yml  -l python-flask -o swagger-python-flask
```

##### Steps to reproduce
* Generate flask server using the above commandline
* Inspect the `models` directory
* Verify that the `self.swagger_types` and  `self.attribute_map` are empty.

**Note:** The same issue happens for schemas with `additionalProperties` defined (i.e the corresponding model class does not have swagger types):
```yaml
testaddprop:
  type: object
  additionalProperties:
    type: string
```

**Comment by mandeepsandhu** [comment]
Ok, this is an issue with my spec. The response schema needs an "anchor name" for swagger to be able to generate the resulting model with correct types (since thats how it internally stores the schema - with an attribute name and type). In my original example I did not have any attribute name for the list of strings I wanted to return, resulting in the model not having the required swagger attributes set.

The correct (IMO) way to write the response would be:
```yaml
schemas:
    testresponse:
      type: object
      properties:
        data:
          type: array
          items:
            type: string
```
With the above schema, the generated model has the required swagger type & attributes set.
```python
        self.swagger_types = {
            'data': List[str]
        }

        self.attribute_map = {
            'data': 'data'
        }
```
Please CMIIW.
