### ISSUE TITLE
[csharp] Generate a List<Guid> Model property instead of List<Guid?>

### ISSUE THREAD

**Issue by nerdpad** [swagger-api/swagger-codegen#9677]
##### Description

The following model generates a class with a UUIDs property, but the type of the property is `List<Guid?>`. How can I generate a `List<Guid>`?

##### Swagger-codegen version
2.2.3

##### Swagger declaration file content or url

```yaml
  SearchModel:
    type: object
    description: A request model.
    required: [uuids]
    properties:
      uuids:
        type: array
        items:
          type: string
          format: uuid
          description: The unique identifier.
```

##### Command line used for generation
```
  java -Dapis -Dmodels -DsupportingFiles -DapiTests=false -DmodelDocs=true -DmodelTests=false 2>>%4 -jar %5\swagger-codegen-cli-2.2.3.jar generate -i "%%f" -l csharp -o %2 --config %3 -t %5\templates
```
##### Output
The above yaml generates a Model with the following UUIDs property.
```
/// <summary>
/// Gets or Sets Uuids
/// </summary>
[DataMember(Name="uuids", EmitDefaultValue=false)]
public List<Guid?> Uuids { get; set; }
```
