### ISSUE TITLE
How to view the APIs in SwaggerEditor / SwaggerHub and even to generate server code while it needs several files? 

### ISSUE THREAD

**Issue by ruozhixian** [swagger-api/swagger-codegen#9707]
For example, I define the Category in root yaml file as:
```
(openapi: 3.0.0)
components:
  schemas:
    Category:
      $ref: 'openapi-petstore-category.yml#/components/schemas/Category'
```
and the specific content of Category is defined in another file: openapi-petstore-category.yml.

It works well when I use the swagger-codegen-cli to generate spring server, just like
`java -jar swagger-codegen-cli-3.0.11.jar generate -i ./oas3/root-petstore.yml -l spring -o petstore/test1/`

However, if I want to see the APIs information in SwaggerEditor / SwaggerHub, it is allowed to just upload one file. And the root yaml file in SwaggerEditor / SwaggerHub appears the error `"Could not resolve reference: Tried to resolve a relative URL , without having a basePath. path 'openapi-petstore-category.yml' basePath: 'undefined'"`

Then I attempt to add the file's path in my computer as 'basePath', but it doesn't work.
