### ISSUE TITLE
oneOf or allOf or anyOf would generate spring or java model empty class

### ISSUE THREAD

**Issue by Jovons** [swagger-api/swagger-codegen#9720]
For openapi yaml files that contain `anyOf` or `oneOf` or `allOf`, it would generate java model class with no fields, but just equals or toString. Once they are removed, java model would be generated with fields.

**Comment by HugoMario** [comment]
hello @Jovons can you please share an example of wrong output?

**Comment by gdarrigo** [comment]
Hi have the same issue (swagger-codegen v3.0.11).

OpenApi part of component:
<img width="343" alt="Schermata 2019-10-07 alle 15 17 02" src="https://user-images.githubusercontent.com/23381147/66315254-b1ea0600-e915-11e9-9d5b-46249793fca7.png">

Generated model:
<img width="1190" alt="Schermata 2019-10-07 alle 15 21 17" src="https://user-images.githubusercontent.com/23381147/66315469-291f9a00-e916-11e9-953a-fdf8c36d4a9f.png">

Thanks for a response.

Gabriele

**Comment by netbeansuser2019** [comment]
Tested in context of : "library" set to "okhttp-gson".

There is even seen generated empty interface or placing parent class two wrong place like to position where should be just interface interface or as ", ," (so missing). 

So in case of multi-parent and java it should leads to:
- error in code generation phase to not continue
- or creation one top class with all such field

**Comment by gracekarina** [comment]
Hi can you please share a spec exposing the issue? and also please test with last version of codegen thanks

**Comment by ishan-work** [comment]
Tested with 3.0.14 (current stable) and jersey2 library. Get the same result as @gdarrigo.
Spec file:
[openapi3.zip](https://github.com/swagger-api/swagger-codegen/files/3911723/openapi3.zip)

**Comment by hkosova** [comment]
@gdarrigo your `StatoTessera` schema is not valid because an instance cannot be `type: object` and `type: string` at the same time.

**Comment by HugoMario** [comment]
hello @Jovons @gdarrigo @gdarrigo 
please, keep in mind that for sample:
```yaml
variable-value:
      anyOf:
        - type: boolean
        - type: integer
        - type: number
        - type: string
        - type: array
          items:
            anyOf:
              - type: boolean
              - type: integer
              - type: number
              - type: string
```
we're saying that for java language `Variable-value`, can be a boolean, a integer, a number, a string or an array. this is not defined as an object
