### ISSUE TITLE
[Python] Query parameter sent as "None" when it is passed as None

### ISSUE THREAD

**Issue by slash-arun** [swagger-api/swagger-codegen#9766]
##### Description

When the query parameter is optional, if the parameter is passed as None it is sent as the string None

##### Swagger-codegen version

2.4.8

##### Swagger declaration file content or url

```yaml
/pets:
    get:
      summary: List all pets
      operationId: listPets
      tags:
        - pets
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
```

##### Command line used for generation

```
swagger-codegen generate -i http://petstore.swagger.io/v2/swagger.json -l python -o /tmp/test/
```

##### Steps to reproduce

Pass `limit` as `None` in get pets API. The limit is passed as `host.com/pets?limit=None`

##### Related issues/PRs

Did not find any

##### Suggest a fix/enhancement

When an optional query param is None, do not pass the value as 'None' rather don't pass the variable
