### ISSUE TITLE
[JavaScript] Generated code doesn't set default value for header params per swagger spec

### ISSUE THREAD

**Issue by jmartin-sul** [swagger-api/swagger-codegen#9842]
##### Description

When a default value is specified for a header parameter (e.g. a `Link` header), the generated JavaScript code allows the user to specify a value (correct), but does not provide a default value if an explicit value is not given (seemingly incorrect).

##### Swagger-codegen version

2.4.x (tried on 2.4.0, 2.4.2, 2.4.8, 2.4.9)

##### Swagger declaration file content or url

https://github.com/LD4P/sinopia_server/blob/e3283b3e87e020a3f29793f4076ddb8c73cf46d5/swagger.yaml#L68-L73

##### Command line used for generation

java -jar swagger-codegen-cli-2.4.8.jar generate -i swagger.yaml -l javascript --additional-properties usePromises=true -o sinopia_client/

##### Steps to reproduce

run the aforementioned command on the above linked swagger spec.

get generated JS code that results in having to manually implement the default, e.g.:
https://github.com/LD4P/sinopia_server/blob/e3283b3e87e020a3f29793f4076ddb8c73cf46d5/sinopia_client/src/api/LDPApi.js#L84

##### Suggest a fix/enhancement

it would be great if the autogenerated code would allow the user to specify header param values as it does, while also providing a default value if the swagger spec lists one and the user provides no explicit value.

**Comment by NA-Dev** [comment]
+1 I also have a case where I tried to use a default param value to no avail. I tried two different ways on the latest codegen for Python...

```
- name: response_type
  schema:
    type: string
    default: code
  in: query
  description: The type of response. Always set to code.
  required: false


- name: response_type
  schema:
    type: string
  default: code
  in: query
  description: The type of response. Always set to code.
  required: false
```
