### ISSUE TITLE
[PHP] minimum/maximum not reflected

### ISSUE THREAD

**Issue by flowl** [swagger-api/swagger-codegen#9997]
##### Description

`minimum` and `maximum` values on properties do not get reflected to the PHP classes.

##### Swagger-codegen version

Docker CLI container

```
docker run --rm -v ${PWD}:/local swaggerapi/swagger-codegen-cli-v3 generate \
    -i /local/out/quantities.yml \
    -l php \
    --api-package Quantities \
    -o /local/out/quantities
```

##### Swagger declaration file content or url

https://swagger.io/docs/specification/data-models/inheritance-and-polymorphism/

```yaml
properties:
       quantity:
          type: integer
          minimum: 100
          maximum: 600
```

The output does not reflect any >= 100 <= 600 comparison.

When type = string and instead of minimum/maximum we add `enum` with some values, there is getting a lot of stuff into the PHP classes (with a method `getQuantityAllowableValues()` on the model). There is no such thing with integer and minimum/maximum.
